penrose/penrose

.circleci/config.yml
Makefile
docker/README.md

Added a couple minor fixes, README pointers, and a stop command to the Docker manifest.

[ready to merge] Additional docker/readme edits

---

src/Dsll.hs
src/Env.hs
src/ShadowMain.hs
src/Substance.hs
src/dsll/setTheory.dsl
src/linear-algebra-domain/linear-algebra.dsl
src/mesh-domain/mesh.dsl
src/real-analysis-domain/real-analysis.dsl

**Not fully done yet, not ready to merge!**
Related issues: #192 

Element revisions for TOG paper

---

src/react-renderer/src/App.tsx
stack.yaml

Build failed due to duplicate entry in `stack.yaml`

[dep-dedup] de-duplicated aeson dep

---

.circleci/config.yml

Otherwise, CircleCI would fail

[circleci-patch] Remove AWS service update for now, as we're using ELB

---

src/react-renderer/package-lock.json
src/react-renderer/package.json

via `npm update` and `npm audit fix`

[audited] Bump versions (automatically) of vulnerable packages

---

src/react-renderer/src/Canvas.tsx

So that one can set the SVG filename

[ready to merge] Add optional title param to allow for file renaming

---

src/Server.hs
src/react-renderer/src/App.tsx

Frontend can properly handle this as well.

Send packet on connect to keep server health monitors aware

---

react-renderer/index.d.ts
react-renderer/src/module.tsx

Fixed #265 via https://github.com/babel/babel/issues/8361
Related issues: # (issue)

[fix/265] Fix #265

---

.circleci/config.yml

This should catch frontend failures in the future like #265

Add frontend build job to circleci

---

react-renderer/src/packets.tsx

[packetfix] Add stepuntilconvergence again

---

examples/set-theory-domain/twosets.sub
penrose-web/index.d.ts
penrose-web/package-lock.json
penrose-web/package.json
penrose-web/src/App.tsx
penrose-web/src/Protocol.tsx
penrose-web/src/contrib/Constraints.ts
penrose-web/src/engine/Autodiff.ts
penrose-web/src/engine/Optimizer.ts
penrose-web/src/engine/PropagateUpdate.ts
penrose-web/src/shapes/Draggable.tsx
penrose-web/src/ui/Canvas.tsx

Related issues: #242 
Since we ported the runtime to TS, the old code for drag events is no longer functional. This PR ports the drag event handling to work with the new runtime.
* `PropagateUpdate` module includes updated functions for updating the state given drag updates.
* `tslog` is no longer used. `consola` is our new logging library. 

Draggable shapes in TS runtime

---

examples/linear-algebra-domain/twoVectorsPerp-unsugared.sub
packages/browser-ui/public/index.html
packages/core/src/renderer/Arrow.ts

fix: #481 - wrong NS attribute

---

packages/browser-ui/src/App.tsx

quick fix due to #487 regression

fix: render sizing due to container

---

packages/core/estrella.js
packages/core/package.json
packages/core/tsconfig.json

build: emit typescript declarations in watch

---

examples/set-theory-domain/twosets-simple.sub

fix: twosets-simple example

---

package.json

build: add top-level build script for the IDE

---

packages/core/src/parser/Substance.ne

This fixes an issue introduced by #740.

fix: Replace Substance undefined symbol usage

---

packages/browser-ui/src/inspector/views/mod/LabeledInput.tsx
packages/core/src/index.ts

Cherry-picked from #694. Original error introduced some time earlier in main.

fix: `toHex` usage in `mod`

---

.github/workflows/build.yml

This PR continues trying to do what #778 already tried to do.

fix: GitHub Actions canary release

---

packages/components/src/stories/PenrosePrograms.tsx

The Domain syntax update broke storybook examples (mostly continueous map). This PR updates the examples.

fix: update examples in storybook

---

.prettierrc
packages/automator/README.md
packages/automator/index.tsx
packages/automator/package.json
packages/automator/template.pug
packages/automator/vis.js
packages/browser-ui/src/inspector/views/Opt.tsx

@joshsunshine will be using `@penrose/automator` for performance testing. This PR fixes some flaky path resolution code in the automator, and adds a `--cross-energy` for enabling the CIEE test explicitly.

fix: path resolution in `automator`

---

packages/docs-site/docs/tutorial/basics.md
packages/docs-site/docs/tutorial/functions.md

docs: Fix more links in the tutorials

---

examples/full-moon/full-moon.dsl
examples/full-moon/full-moon.sty
examples/full-moon/full-moon.sub

Added an illustrative example of a simple L-system.
Run `npx roger watch full-moon.sub full-moon.sty full-moon.dsl` in folder `examples/full-moon`.
Is there an efficient way to compute Minkowski signed distance function for fractals defined by iterated function system?

feat: L-system example 

---

packages/core/src/engine/Autodiff.test.ts
packages/core/src/engine/Autodiff.ts
packages/core/src/engine/AutodiffFunctions.ts
packages/core/src/types/ad.ts

refactor: Clean up a few minor autodiff things

---

.github/workflows/lint-pr.yml

See https://github.com/penrose/penrose/pull/931#discussion_r853415183.

ci: Lint PR on pull_request_target only

---

packages/editor/src/components/DiagramPanel.tsx

Replaced the previous IDE Easter Egg with @keenancrane's recent WIRED video.
- Load the IDE
- :: the secret incantation ::
- See a cool video (like before), but now it's about fractals!

feat: Update the Easter Egg

---

packages/docs-site/src/pages/index.js

This PR updates the home page to use the new e-mail address @joshsunshine  created this afternoon.

fix: Update team e-mail address

---

packages/core/src/parser/Style.ne

Fixes #985 
https://penrose.cs.cmu.edu/try/?gist=80a8c2a48fc1cdf67e01be918cfba404 works locally

feat: allow anonymous shapes in Style rules

---

packages/editor/package.json

build: Give Vite 8 GiB in editor

---

packages/docs-site/docs/tutorial/constraints.md
packages/docs-site/docs/tutorial/predicates.md
packages/examples/src/tutorials/solutions/tutorial3.md

Various minor documentation fixes in the tutorial
N/A
N/A
N/A

fix: Various docs fixes

---

AUTHORS

This PR deletes `AUTHORS` (following up on a conversation @wodeni and I had earlier today). It's unclear what purpose it serves.

chore: Delete AUTHORS

---

packages/docs-site/docs/team.mdx
packages/docs-site/src/components/TeamProfile.tsx

Adding @liangyiliang to the team page (sorry about the delay!) and some other personal updates. 
N/A
See preview deployment
N/A

chore: update team profiles

---

packages/editor/src/components/DiagramPanel.tsx

Related issue/PR: #524
As much as we love vectorized images, rasterized images are sometimes needed for compatibility with other tools. This PR adds support for PNG export via canvas.
* Attempted [canvg] first, but the support for `<marker>` is not great. See example: 
* Following the approach from [SO post](https://stackoverflow.com/questions/28226677/save-inline-svg-as-jpeg-png-svg) (thanks!), we use canvas's `drawImage` instead. 
* The exported png is true-to-scale. I did add a `scale` argument to `DownloadPng` so the UI can surface scale options in the future.
* The main catch is: __drawImage__ requires the SVG to have non-percentage width and height attributes.
* https://bugzilla.mozilla.org/show_bug.cgi?id=700533
* https://stackoverflow.com/questions/3768565/drawing-an-svg-file-on-a- …

feat: export rasterized diagrams in `editor`

---

packages/components/package.json
packages/docs-site/package.json
packages/editor/package.json
packages/synthesizer-ui/package.json

This PR should fix the second item from #1096, using the same technique as #497.

build: Use cross-env

---

CONTRIBUTING.md

This PR makes a documentation change I forgot to make in #1142.

docs: Update registry command for Nx

---

packages/core/src/engine/Autodiff.test.ts

See https://github.com/penrose/penrose/pull/977#discussion_r1030914898.

test: Correctly identify quintic polynomial test

---

.github/workflows/edgeworth.yml

ci: fix Edgeworth job

---

packages/components/src/editing/EditorPane.tsx
packages/editor/src/components/ProgramEditor.tsx

Now you can run `:w` to recompile in the editor when in vim mode!
(closes #1046)

feat: compile on vim write (resolves #1046)

---

packages/examples/src/registry.json

Adds the caffein structural formula to the registry.

chore: add a new example to the registry

---

packages/components/README.md

Related issue/PR: #1226 
This PR adds small tweaks to the README for `components` to keep it up-to-date and ready for our v2 release.
* Need to make sure the link to storybook works. Do we want storybook to be under `penrose.cs.cmu.edu`?

docs: update README for `components`

---

packages/automator/package.json

In preparation for v2.0, since we just don't have any nice way to package it for npm.

build: make `automator` private

---

packages/optimizer/README.md

docs: link from optimizer README to core

---

.github/PULL_REQUEST_TEMPLATE.md

See https://github.com/penrose/penrose/pull/1239#issuecomment-1396085821.

chore: clarify "related issue" part of PR template

---

packages/core/src/utils/Graph.ts

chore: clarify a couple `Graph` method docstrings

---

packages/vscode/package.json

build: fix VS Code extension packaging

---

packages/examples/src/registry.json

Adds group-theory example to registry (no other changes).

feat: Add group-theory example to registry

---

.github/workflows/build.yml

Resolves #1267 using [action-has-permission](https://github.com/marketplace/actions/has-permission).

ci: check for write permission in registry job

---

.github/actions/setup/action.yml
.github/workflows/release.yml

Followup to https://github.com/penrose/penrose/pull/1318#discussion_r1114303216.

ci: deduplicate `actions/setup-node`

---

.prettierignore

One of these items is a followup to #1223, the other is just an oversight.

chore: add more stuff to `.prettierignore`

---

packages/docs-site/docs/tutorial/welcome.md

docs: remove "installation instructions" phrase

---

packages/examples/src/graph-domain/textbook/sec5/ex30.substance
packages/examples/src/graph-domain/textbook/sec5/ex31.substance
packages/examples/src/graph-domain/textbook/sec5/ex32.substance
packages/examples/src/graph-domain/textbook/sec5/ex33.substance
packages/examples/src/graph-domain/textbook/sec5/ex34.substance
packages/examples/src/graph-domain/textbook/sec5/ex35.substance
packages/examples/src/graph-domain/textbook/sec5/ex36.substance
packages/examples/src/graph-domain/textbook/sec5/ex47a.substance
packages/examples/src/graph-domain/textbook/sec5/ex47b.substance
packages/examples/src/graph-domain/textbook/sec5/ex47c.substance
packages/examples/src/graph-domain/textbook/sec5/ex47d.substance
packages/synthesizer-ui/src/examples.ts

The Petersen graph example from #1336 is too difficult, so this PR switches it out for an easier one.

chore: choose easier Hamilton circuit example

---

packages/core/src/compiler/Style.ts

I wrote this code in #984 but it's pointlessly confusing. This PR makes it a bit less confusing.

refactor: don't concatenate tag in `updateExpr`

---

.github/workflows/delete-branches.yml

Followup to #1375 because it currently doesn't work. I tested this command so hopefully it'll actually work this time.

ci: delete branches directly using Git CLI

---

packages/examples/package.json

Followup on #1393. See [the docs](https://git-scm.com/docs/git-clean).

build: don't delete untracked trios in codegen

---

.github/actions/setup/action.yml
CONTRIBUTING.md

Followup to #1412 since I forgot to update the docs.

docs: remove obsolete VS Code workspace stuff

---

packages/solids/package.json

chore: remove dead Nx config in `@penrose/solids`

---

.vscode/settings.json
packages/optimizer/src/lib.rs

refactor: use Clippy

---

yarn.lock

build(deps-dev): consolidate Vite versions

---

yarn.lock

This PR deletes a bunch of stuff from our `yarn.lock` by running [the following command](https://github.com/scinos/yarn-deduplicate/tree/v6.0.2#installation):
```sh
npx yarn-deduplicate yarn.lock
```

build(deps): run `yarn-deduplicate`

---

packages/editor/src/components/DiagramPanel.tsx
packages/editor/src/state/atoms.ts

fix: reuse resolver when example becomes local

---

packages/roger/README.md
packages/roger/index.ts
packages/roger/watch.ts

Followup to #1280 now that we're in breaking-change time.

feat!: remove old file extensions from Roger

---

packages/core/README.md
packages/docs-site/docs/tutorial/basics.md
packages/docs-site/docs/tutorial/functions.md
packages/docs-site/docs/tutorial/predicates.md
packages/editor/src/state/callbacks.ts
packages/examples/src/registry.json
packages/examples/src/tutorials/code/tutorial1/trio.json
packages/examples/src/tutorials/code/tutorial1/twoSets.style
packages/examples/src/tutorials/code/tutorial2/trio.json
packages/examples/src/tutorials/code/tutorial3/trio.json
packages/examples/src/tutorials/solutions/tutorial2.md
packages/examples/src/tutorials/solutions/tutorial3.md
packages/examples/src/tutorials/tutorial1.trio.json
packages/examples/src/tutorials/tutorial2.trio.json
packages/examples/src/tutorials/tutorial3.trio.json

The tutorials broke down some over time. This PR fixes them up.

docs: fix the tutorial

---

CODE_OF_CONDUCT.md

This PR creates a community code of conduct for our project based on https://www.contributor-covenant.org/version/2/0/code_of_conduct/.

docs: create `CODE_OF_CONDUCT.md`

---

packages/core/src/compiler/shapeChecker/CheckShapeHierarchyProps.ts
packages/core/src/engine/EngineUtils.ts
packages/core/src/renderer/AttrHelper.ts
packages/core/src/shapes/Circle.ts
packages/core/src/shapes/Ellipse.ts
packages/core/src/shapes/Equation.ts
packages/core/src/shapes/Group.ts
packages/core/src/shapes/Image.ts
packages/core/src/shapes/Line.ts
packages/core/src/shapes/Path.ts
packages/core/src/shapes/Polygon.ts
packages/core/src/shapes/Polyline.ts
packages/core/src/shapes/Rectangle.ts
packages/core/src/shapes/Text.ts
packages/core/src/types/shapes.ts
packages/examples/src/registry.json
packages/examples/src/spectral-graphs/colors.style
packages/examples/src/spectral-graphs/examples/hypercube.trio.json
packages/examples/src/structural-formula/background.svg
packages/examples/src/structural-formula/node-shading.svg
packages/examples/src/structural-formula/pseudo-3d.style

fix: `style` passthrough in `core` renderer

---

packages/docs-site/blog/2023/06/30/wasm.md

chore: fix a couple blogpost typos

---

packages/docs-site/docs/ref/constraints.md

docs: revise constr/obj doc page

---

packages/docs-site/docs/team.md

This PR updates the team list, sorts the team members, and updates URLs for some team members

chore: update team list

---

packages/docs-site/docs/team.md

Updated my website URL on the Team page: should be [this](https://rijuljain.com) now.

chore: Update `team.md` with new website URL for Rijul Jain

---

packages/docs-site/docs/tutorial/basics.md

`substance` -> `domain`
Resolves #issue.

docs: Correct domain code snippet type

---

packages/roger/tsconfig.json

chore: enable strict TS checking in `roger`

---

packages/examples/src/spectral-graphs/examples/4x4-sudoku-graph.trio.json
packages/examples/src/spectral-graphs/examples/7d-cube.trio.json
packages/examples/src/spectral-graphs/examples/dodecahedral-graph.trio.json
packages/examples/src/spectral-graphs/examples/hexagonal-lattice.trio.json
packages/examples/src/spectral-graphs/examples/hypercube.trio.json
packages/examples/src/spectral-graphs/examples/periodic-hexagonal-lattice.trio.json
packages/examples/src/spectral-graphs/examples/torus.trio.json
packages/examples/src/spectral-graphs/examples/truncated-cube-graph.trio.json

Just tidying up a bit after looking at #1550.

style: replace `./..` with just `..`

---

packages/components/src/editing/languages/StyleConfig.ts
packages/core/src/compiler/Style.test.ts
packages/core/src/compiler/Style.ts
packages/core/src/parser/Style.ne
packages/core/src/parser/StyleParser.test.ts
packages/core/src/types/errors.ts
packages/core/src/types/style.ts
packages/core/src/utils/Error.ts
packages/docs-site/docs/ref/style/usage.md
packages/vscode/syntaxes/style.tmGrammar.json

Resolves #1577.
We add two keywords, `numberof` and `nameof`, to give us access to more metadata about the style-substance substitutions.
If `xs` is a substance variable collection, then `numberof xs` gives us a `FloatV` with the number of elements in the collection. This can be useful in computing, for example, the spacing between two objects arranged in a line.
If `x` is a Style variable, then `nameof x` gives us a `StrV` with the name of the Substance variable that is matched by `x`. This can potentially be useful for showing errors as a part of the diagram. For example, we might want to show an error when a set is both a subset and not a subset of another set. We can write,
```
forall Set a; Set b
where IsSubset(a, b); Not(IsSubset(a, b)) {
errorMessage = Text {
string: "Set " + …
```

feat: `numberof` and `nameof`

---

packages/docs-site/blog/tailoring-graph-domain.md

Fixed the date from July 27 to August 1, and completed an incomplete sentence.

chore: graphs blog post fixes

---

packages/examples/src/dinoshade/dinoshade.trio.json
packages/examples/src/registry.json

Add `examples/dinoshade` trio and registry entry.

feat: Add dinoshade example to registry

---

CONTRIBUTING.md
rust-toolchain.toml

build: revert "build: add rust-toolchain.toml for automatic toolchain installation"

---

packages/docs-site/.vitepress/config.ts

Very minor followup to #1590 and #1594.

docs: put graph domain blog post in August

---

packages/docs-site/docs/ref/style/usage.md

Resolves #1628.
We add the documentations for `repeatable` both in selector and in collector.

docs: `repeatable` keyword

---

packages/examples/src/Dynamics/Lyapunov.trio.json
packages/examples/src/Dynamics/LyapunovExp.domain
packages/examples/src/Dynamics/LyapunovExp.style
packages/examples/src/Dynamics/LyapunovExp.substance
packages/examples/src/registry.json

This change adds a /Dynamics/ folder  to the .../examples/src/ folder. Included in the /Dynamics/ folders are three files, LyapunovExp.style .substance and .domain implementing an example of a Lyapunov Exponent diagram in Penrose. 
The diagram uses 6 randomly generated points to create two curves using the interpolateQuadratic function available in Penrose. The constraints on the diagram are minimal, and it is sometimes necessary to resample a number of times to obtain an example that looks good. 
- The code has minimal comments, happy to edit them however you see fit!

feat: Lyapunov Exponent Example

---

packages/examples/src/registry.json
packages/examples/src/spectral-graphs/3d-disco.style
packages/examples/src/spectral-graphs/3d.style
packages/examples/src/spectral-graphs/examples/box.trio.json
packages/examples/src/spectral-graphs/examples/grid.trio.json
packages/examples/src/spectral-graphs/examples/mobius.trio.json
packages/examples/src/spectral-graphs/examples/star-graph.trio.json
packages/examples/src/spectral-graphs/examples/truncated-cube-graph.substance
packages/examples/src/spectral-graphs/examples/watts-strogatz-graph.substance

Addresses open question from #1550. 
- Added correct perspective to 3D spectral graph example and update some graph substances. 
- Added new 3D spectral graph style with variable colors.
- Replace duplicate graph in registry.
- Perspective using matrix functions from  #1538
- Substance simplification uses collections from #1390

feat: Update spectral graph examples

---

.github/workflows/build.yml

Reverts #1235. See https://github.com/penrose/penrose/issues/1246#issuecomment-1749835420.

ci: remove optimizer Wasm artifact

---

packages/solids/src/util.ts

As per @hsharriman's request (sorry for taking so long!).

docs: comment SolidJS `sample` function

---

packages/examples/src/registry.test.ts

Useful for #1657, for instance.

test: write out registry stats after every diagram

---

packages/roger/index.ts

Followup to #1499 I guess? Not really sure how these got here, to be honest.

chore: delete deprecated file extensions from Roger

---

CONTRIBUTING.md

Following up on #1704 to document the need for Node 18+.

docs: update CONTRIBUTING.md to require Node 18+

---

packages/examples/src/geometry-domain/geometry.domain

This PR adds comments to each type, constructor, function, and predicate in the geometry domain, explaining its usage with a description and example program. For example, for a `Segment`:
```
constructor Segment(Point p, Point q) -- This constructor creates a line segment from two points. Example usage: 
-- Point A, B
-- Segment AB := Segment(A, B)
-- AutoLabel A, B
```

refactor: commented geometry domain

---

packages/editor/src/components/SavedBrowser.tsx
packages/editor/src/components/TopBar.tsx
packages/editor/src/state/atoms.ts
packages/editor/src/state/callbacks.ts

Resolves issue #1738 
Creates a blue "new workspace" button the nav bar that creates an untitled diagram on click. 
Do not merge yet, further testing is necessary

feat: workspace button

---

packages/editor/src/worker/worker.ts

Previously, `worker.ts` queued optimization steps using `setTimeout(..., 0)` to allow incoming messages to be processed first. However, even with a 0ms delay, `setTimeout` is not performant, and slowed down optimization from the earlier `SharedMemoryBuffer` approach. This PR instead queues optimization steps with a `MesssageChannel`, which performs much better as demonstrated [here](https://stackoverflow.com/questions/61338780/is-there-a-faster-way-to-yield-to-javascript-event-loop-than-settimeout0/61339234#61339234).

perf: optimizer worker speed up

---

CONTRIBUTING.md

docs: remove `wasm-bindgen` instructions

---

packages/components/src/editing/parser/domain/domainLanguage.ts
packages/components/src/editing/parser/substance/substanceLanguage.ts

fix: comment shortcut

---

packages/docs-site/.vitepress/theme/index.ts
packages/docs-site/blog/bloom.md
packages/docs-site/docs/bloom/tutorial/getting_started.md
packages/docs-site/docs/bloom/tutorial/hello_diagram.md
packages/docs-site/src/bloom-examples/eigen.tsx

Fixed syntax highlighting issues and enforce light mode in Bloom blog.

docs: last minute Bloom blog fixes

---

packages/docs-site/.vitepress/config.ts

Update Bloom blog date to September.

docs: update bloom blog date

---

packages/docs-site/.vitepress/config.ts
packages/docs-site/blog/bloom.md

Updates Bloom Blog date to September 24, 2024.

docs: Bloom blog date, v2

---

packages/docs-site/.vitepress/config.ts
packages/docs-site/blog/bloom.md

Updates Bloom blog date to the 23rd (I can't read a calendar, apparently).

docs: Bloom blog date, v3

---

packages/docs-site/blog/bloom.md

Followup on #1858, correcting the month from July to September.

chore: correct Bloom post date

---

packages/core/src/engine/Autodiff.ts

fix: `floor`
