penrose/penrose

.gitignore, src/Functions.hs, src/Runtime.hs, src/Style.hs, src/Substance.hs, src/Utils.hs, src/client.js, src/sty/surjection.sty, src/sty/tree.sty, src/sty/venn_comp_simple.sty
Refactored `procBlock` and some aliasing for readability of `Style`
* added underscore to all internal ids for labels
* modified tree.sty due to changes in label definition
* separated out selector logic.
* different `procBlock` cases
* case 1: just one `global` selector -> process objs and constrs
once
* case 2: just one selector -> the original logic
* case 3: a list of comma separated selectors -> objs and constrs only and compute valid combinations among the selctors
=> Refactoring `procBlock`

src/react-renderer/package-lock.json, src/react-renderer/package.json, src/react-renderer/src/App.tsx, src/react-renderer/src/ButtonBar.tsx, src/react-renderer/src/Canvas.tsx, src/react-renderer/src/Image.tsx, src/react-renderer/src/Label.tsx, src/react-renderer/src/Util.tsx
**BEFORE MERGING**: please try importing the SVG in
[illustration (12).zip](https://github.com/penrose/penrose/files/2906903/illustration.12.zip) into Illustrator. Make sure the brackets/parens show up, it should look like this:
A quick hack to substitute inline SVG `<image>`s with their contents to allow for export portability. Puts all xlinks in the external images into their own unique namespaces.
Related issues: penrose/penrose-ide#6
Inline image before:
```svg
<image href="left-bracket.svg" x="490.5946350097656" y="340" width="10" height="20"></image>
```
Inline image after:
```svg
<g xmlns="http://www.w3.org/2000/svg" transform="translate(150.78616333007812,340)"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="10" height="20" viewBox="0 0 6 …
```
=> Image path exporting hotfix

.dockerignore, Makefile, docker-compose-dev.yml, docker/Dockerfile-domains.dev, docker/Dockerfile-penrose.dev, docker/Dockerfile-renderer.dev, docker/README.md
This pull adds a `docker-compose` orchestration and set of `Makefile` commands that should increase the portability of Penrose as a development environment via Docker.
Docker adds a system-level abstraction over the environment that Penrose is developed in. The correct version of `stack`, `nodejs`, etc are all included in the box.
All build and run commands executed through `make` are sent to docker containers via a virtual shell. There is also a shell command available that allows one to, essentially, `ssh` into the docker container and run additional tools like `ghc`'s profiling tool. The system doesn't have to be rebuilt every time a code change is made, since this setup mounts the local copy inside of the docker containers. `stack build` etc, when executed via shell or Makefile, …
=> Add Docker Development Environment

.circleci/config.yml, Dockerfile.circleci, README.md, scripts/domain-server.sh
This adds circleci support to our repository. There are two features:
* **Automated building and testing**: we can create binaries and test our builds automatically.
* **Continuous tagged deployment**: If you tag your commit (preferably before pushing) following the format `vx.x` where `x` is an integer, Circleci will deploy the tagged commit to our AWS cluster.
=> Add Circleci Support

.circleci/config.yml, Dockerfile.circleci
Our production image (`Dockerfile.circleci`) broke because some linked system library changed. We use the generic `ubuntu` base image so a new pull probably caused the error to manifest:
```
./penrose: error while loading shared libraries: libblas.so.3: cannot open shared object file: No such file or directory
```
(You can reproduce this by going to circleci and downloading the `penrose-bin` build artifact. Rename it to `penrose` and put it in TOP, then run `docker build -f Dockerfile.circleci .`. Then `docker run -it [the hash]`.)
The solution (though heavy-handed) is to switch our base image so that we inherit from one that has lots of Haskell deps preinstalled: `fpco/stack-build:lts-9.10`. I'm sure there's a lightweight production copy around somewhere too but I'd rather be safe for …
=> [ready to merge] Changed base image for production

docker/Dockerfile-penrose.dev
The `-e` flag was causing errors in the docker container.
=> [echo-flag] Remove ostensibly useless echo flag

src/react-renderer/src/Canvas.tsx, src/react-renderer/src/Circle.tsx, src/react-renderer/src/CircleTransform.tsx
When supplied with some metadata (there are defaults as well), the renderer can add more info to the SVG for accessibility and traceability when the file goes out in the "wild".
Example:
```html
<desc>This diagram was created with Penrose (https://penrose.ink) on 2019-06-12. If you have any suggestions on making this diagram more accessible, please contact us.
Produced with the substance code:
"Set A, B, C, D, E, F, G
IsSubset(B, A)
IsSubset(C, A)
IsSubset(D, B)
IsSubset(E, B)
IsSubset(F, C)
IsSubset(G, C)
NotIntersecting(E, D)
NotIntersecting(F, G)
NotIntersecting(B, C)
AutoLabel All
"
Using style program "tree".
Using element program "set theory".
</desc>
```
The first line appears on all exports, and the next three sections depend on what the IDE supplies.
Once style, element, and …
=> (ready to merge) Add rudimentary metadata interfaces

.circleci/config.yml, Dockerfile.circleci, docker/Dockerfile-penrose.dev
This PR changes the base images used for deployment to AWS (`stack-build` := `stack-build-small`) which I believe will be significant enough of a change to make AWS happy again.
=> Make docker image smaller

src/Server.hs
To make the packet passing faster on production
=> Extend WS server options with PermessageDeflateCompression

opt-config/default.json, react-renderer/src/Util.tsx
Related issues: #207 TOG-paper request
This PR adds another style for arrows, which is modeled after arrow #2 of Illustrator.
- Started using `auto-start-reverse` to avoid manual rotation of marker paths
- As a result, unified `Start/EndArrowhead` into just `Arrowhead` with auto-orientation
- Added another arrowhead style
- Arrow styles can now be added to a dictionary located in `Util.tsx` called `arrows`, and the `Arrowhead` component takes in an extra property `style: string` that specifies which arrowhead to use. The arrowheads are indexed by string values. The current convention is `arrowhead-[0-9]+`. The default value is `arrowhead-2`, which is the new style. 
- The arrowhead style property is currently not propagated to the Style level
The current implementation will not place …
=> New arrow style

examples/archive/sty/known_hard_cases/curves_containment.sty, examples/archive/sty/transform-curve.sty, examples/archive/sty/transform-line.sty, examples/geometry-domain/euclidean.sty, examples/geometry-domain/spherical.sty, examples/linear-algebra-domain/linear-algebra.sty, examples/real-analysis-domain/parallel-RA.sty, examples/real-analysis-domain/perpendicular-RA.sty, examples/real-analysis-domain/real-analysis-image.sty, react-renderer/src/Arc.tsx, react-renderer/src/Arrow.tsx, react-renderer/src/Curve.tsx, react-renderer/src/CurveTransform.tsx, react-renderer/src/Line.tsx, react-renderer/src/LineTransform.tsx, react-renderer/src/Util.tsx, src/Penrose/Shapes.hs
Related issues: #255 
This PR contains a more generalized solution to arrowheads:
* Two styles of built-in arrowhead style in `Util.tsx`. One can easily add more styles by expanding `Util.arrowheads`
* New properties for `Line`, `Curve`, `Arc`, `Arrow`: `arrowheadStyle` and `arrowheadSize`
* `arrowheadStyle :: String`: a string literal that correspond to the keys in `Util.arrowheads`. The current convention is `arrowhead-[0-9]+`. The default is `1.0` (1x the strokewidth)
* `arrowheadStyle :: Float`: a float that determines the size of the arrowhead(s) relative to the stroke width. The default is `arrowhead-2`.
TODO
* Original: 
* Changing the arrowhead style of the y-axis to `arrowhead-1`:
* Changing the arrowhead size to `2.0`:
* ...and increasing the strokeWidth from `2.0` to `4.0`:
A …
=> Customization of arrowheads

examples/linear-algebra-domain/linear-algebra-paper.sty, examples/linear-algebra-domain/linear-algebra.sty, examples/linear-algebra-domain/twoVectorsPerp.sub, src/Penrose/Functions.hs
Add support for unit vector marks and port the perpendicular mark to no longer use transforms (deprecated). 
Unit vector mark implementation is pretty messy because it requires a lot of inline vector operations, which style can't handle, and needs to know about the presence of the orthogonal vector so it doesn't overlap. Not sure how to resolve.
`runpenrose linear-algebra-domain/twoVectorsPerp.sub linear-algebra-domain/linear-algebra-paper.sty linear-algebra-domain/linear-algebra.dsl`
* Clean up unit mark implementation
=> Improve linalg paper style to match paper example

examples/set-theory-domain/continuousmap.sub
f^{-1} should be in the domain, not the codomain. Per Munkres: "A function f \colon X \to Y is said to be continuous if for each open subset V of Y, the set f^{-1}(V) is an open subset of X."
Before:
After:
=> Fix continuous map example.

react-renderer/src/utills/CollectLabels.tsx
Due to MathJax v3 not supporting newlines (bug report: https://github.com/mathjax/MathJax/issues/2418), several examples (eg `linearMap_add.sub`) cannot optimize fully due to their horizontal length.
=> Fix newline support for MathJax v3

examples/set-theory-domain/venn-opt-test.sty, examples/vizdoc/near.sty, examples/vizdoc/near.sub, examples/vizdoc/shapes.dsl, react-renderer/src/Evaluator.ts
Issue #355 
Previously in web-runtime, shapes were not being sorted by ordering after each optimizer step, which caused layering keywords like `above` to behave unexpectedly when rendering diagrams. The fix ensures shape sorting after each step. I also updated the set theory example (`runpenrose set-theory-domain/tree.sub set-theory-domain/venn-opt-test.sty set-theory-domain/setTheory.dsl`) to explicitly define layering relationship between a Set shape and a Set text, which became necessary after the fix. I also included the original diagram mentioned in the relevant issue to show that the problem is fixed (`runpenrose vizdoc/near.sub vizdoc/near.sty vizdoc/shapes.dsl 
`).
Copied the function used in Canvas to originally sort the shapes to the Evaluator inside the `evalTranslation` …
=> Fixing layering issues in web-runtime

.gitignore, UserGuide.md, examples/ThoughtsAndIssues.txt, examples/hyperbolic-domain/PoincareDisk.sty, examples/hyperbolic-domain/hyperbolic-example.sub, examples/hyperbolic-domain/hyperbolic.dsl, examples/runHyperbolic, examples/set-theory-domain/venn.sty, react-renderer/.dir-locals.el, react-renderer/package-lock.json, react-renderer/src/Canvas.tsx, react-renderer/src/Circle.tsx, react-renderer/src/Computations.ts, react-renderer/src/Constraints.ts, react-renderer/src/EngineUtils.ts, react-renderer/src/Evaluator.ts, react-renderer/src/Optimizer.ts, react-renderer/src/PropagateUpdate.ts, react-renderer/src/Util.tsx, react-renderer/src/types/types.d.ts, react-renderer/tsconfig.json, react-renderer/tsfmt.json
Previously, the "engine" had the option of using `number` or `Tensor` types in the evaluator via the `autodiff` flag, because we needed the former type for displaying shapes (evaluating the translation) and the latter type for optimization (evaluating the energy).
While concise, the design started to cause some challenges:
* Computations appear in both kinds of evaluation, thus had to be written with both numeric types
* Lots of code duplication in the evaluator, since it needs to interpret expressions on both numeric types and deal with mismatches
* Hard to debug if a single number of the wrong type gets into the wrong evaluation phase (e.g. `number`s in the optimization)
Therefore, this PR changes all evaluation + optimization-related functions and types to be on autodiff types only (in …
=> Change "engine" to run on autodiff types only

USAGE.txt, src/Penrose/ShadowMain.hs
Related issues: #360 
This pull request change the way the input files are handled in the command line. The type of the source file was previously associated according to their order in the command line. With this change the type will be derived from the file extension. Each type is required to have only one associated input file.
=> Use file extensions instead of order in command line arguments

penrose-web/src/inspector/README.md, penrose-web/src/inspector/views/mod/LabeledInput.tsx, penrose-web/src/inspector/views/mod/shapedefs/arrow.json, penrose-web/src/inspector/views/mod/shapedefs/circle.json, penrose-web/src/inspector/views/mod/shapedefs/curve.json, penrose-web/src/inspector/views/mod/shapedefs/ellipse.json, penrose-web/src/inspector/views/mod/shapedefs/image.json, penrose-web/src/inspector/views/mod/shapedefs/line.json, penrose-web/src/inspector/views/mod/shapedefs/rectangle.json, penrose-web/src/inspector/views/mod/shapedefs/square.json, penrose-web/src/inspector/views/mod/shapedefs/text.json
Related issues: #409 
Shape definitions were changed in `ShapeDef.ts`, and the JSON shapedef files for the Mod tab no longer worked. I've updated them to match the new definitions and also added necessary support to render them in `LabeledInput.tsx`. 
The new changes fixed the original issue (`linear-algebra-domain/twoVectorsPerp.sub linear-algebra-domain/linear-algebra-paper-simple.sty linear-algebra-domain/linear-algebra.dsl`), and I also tested it on the first few example diagrams [here](https://github.com/penrose/penrose/wiki/Example-diagrams).
=> Updated mod shapedefs to correspond with new definitions

penrose-web/package-lock.json, penrose-web/package.json, penrose-web/src/__tests__/env.json, penrose-web/src/compiler/Domain.test.ts, penrose-web/src/compiler/Domain.ts, penrose-web/src/parser/Domain.ne, penrose-web/src/parser/DomainParser.test.ts, penrose-web/src/parser/DomainParser.ts, penrose-web/src/parser/ParserUtil.ts, penrose-web/src/parser/Style.ne, penrose-web/src/parser/StyleParser.ts, penrose-web/src/types/errors.d.ts, penrose-web/src/types/types.d.ts, penrose-web/src/utils/Error.ts, src/Penrose/Element.hs, src/Penrose/Substance.hs
Related issue/PR: #419 
This PR contains the parser for the Domain language written in TypeScript.
* Revise the Domain AST to include source locations and simplify overly nested types
* Remove dependent types from the grammar
* Add a test suite for the parser
* Automatic parser generation upon `npm run/build/build-lib/start`
* Run `npm test`, which will trigger a `pretest` script that builds all parsers (see below)
* To manually build all parsers, run `npm run build:parsers`
* Example: AST for `set-theory-domain/setTheory.dsl`: https://gist.github.com/wodeni/c135c2e67da0397db3d11a8b945791e7
=> Porting the Domain parser and semantic checker

packages/penrose-core/src/compiler/Domain.ts, packages/penrose-core/src/compiler/Style.ts, packages/penrose-core/src/compiler/Substance.test.ts, packages/penrose-core/src/compiler/Substance.ts, packages/penrose-core/src/parser/SubstanceParser.test.ts
Related issue/PR: #470 
As described in the issue.
* Call `feed('\n')` after parsing every program in all 3 parsers.
* Add tests
=> fix: allow trailing comments without newline at the end

packages/penrose-core/src/compiler/Domain.test.ts, packages/penrose-core/src/compiler/Style.ts, packages/penrose-core/src/compiler/Substance.test.ts, packages/penrose-core/src/engine/Evaluator.ts, packages/penrose-core/src/parser/DomainParser.test.ts, packages/penrose-core/src/parser/StyleParser.test.ts, packages/penrose-core/src/parser/SubstanceParser.test.ts, packages/penrose-core/src/utils/Util.tsx
Related issue/PR:  #466
For testing, added a global random seed in `Util.tsx` to enfore global pseudorandomness.
Call `seedrandom` with `global` option on.
N/A
=> fix: add global pseudorandomness

examples/geometry-domain/euclidean-simple.sty, examples/mesh-set-domain/DomainInterop.sty, examples/set-theory-domain/venn.sty, packages/penrose-core/src/App.tsx, packages/penrose-core/src/compiler/Style.test.ts, packages/penrose-core/src/compiler/Style.ts, packages/penrose-core/src/engine/EngineUtils.ts, packages/penrose-core/src/parser/DomainParser.ts, packages/penrose-core/src/parser/StyleParser.ts, packages/penrose-core/src/parser/SubstanceParser.ts, packages/penrose-core/src/types/errors.d.ts, packages/penrose-core/src/types/types.d.ts, packages/penrose-core/src/utils/Error.ts
Related issue/PR: #446 
This PR improves the Style compiler error-handling so that all existing errors are modeled and reported separately, and adds tests for most of them.
Note that this is a **first pass** at cleaning up the errors that **already exist** in the Style compiler; I anticipate that actually using the system will help us discover many more kinds of errors that should be reported, and in other parts of the system, especially at runtime.
The PR follows the strategy broadly described in https://github.com/penrose/penrose/pull/446#issuecomment-772064166. 
It extends `errors.d.ts` with error types and `showError` in `Error.ts` with error-printing code. Tests are in `Style.test.ts`. Runtime errors are in `insertExpr`.
Errors are roughly split up between misc errors, selector …
=> Improve Style compiler error-handling

examples/set-theory-domain/venn-3d.sty, examples/set-theory-domain/venn.sty, packages/browser-ui/src/App.tsx, packages/core/src/compiler/Style.test.ts, packages/core/src/compiler/Style.ts, packages/core/src/compiler/venn-3d-test.sty, packages/core/src/engine/EngineUtils.ts, packages/core/src/engine/Evaluator.ts, packages/core/src/index.ts, packages/core/src/types/errors.d.ts, packages/core/src/utils/Error.ts
**Motivation**: Currently Style does not fail if code does not run, just like JS. So if there is some wrong Style code that does not appear in the energy graph or the shape graph, we don’t report errors. Also, errors are currently thrown at eval-time (JS runtime) and mostly unchecked, so they result in cryptic messages from the JS runtime. 
**Proposal**: Check correctness of the blocks while making the translation, as well as the whole translation before evaluating it, and give people better errors ahead of time, that refer to source locations.
**Implementation**: This PR adds more static checking to Style and the translation:
1. Check the Style AST to make sure all shape, objective, constraint, and function names exist.
2. Check the initialized translation to make sure that all …
=> Do more Style/translation checking statically

packages/browser-ui/src/App.tsx, packages/browser-ui/src/inspector/Errors.tsx, packages/browser-ui/src/inspector/Inspector.tsx, packages/browser-ui/src/inspector/views/Frames.tsx, packages/browser-ui/src/inspector/views/IViewProps.tsx, packages/browser-ui/src/inspector/views/viewMap.tsx, packages/core/src/compiler/Domain.test.ts, packages/core/src/compiler/Domain.ts, packages/core/src/compiler/Style.test.ts, packages/core/src/compiler/Style.ts, packages/core/src/compiler/Substance.test.ts, packages/core/src/compiler/Substance.ts, packages/core/src/engine/EngineUtils.ts, packages/core/src/index.ts, packages/core/src/renderer/Circle.ts, packages/core/src/types/errors.ts, packages/core/src/types/types.d.ts, packages/core/src/utils/Error.ts
Related: #486 
* Adds `errors (1)` panel to inspector
* Shuffles error types around so that they can be exported by core
=> Better error handling for browser-ui

examples/linear-algebra-domain/linear-algebra-paper-simple.sty, packages/browser-ui/src/App.tsx, packages/core/src/compiler/Style.ts, packages/core/src/engine/EngineUtils.ts
Minor fixes in Style checking so LA example works.
Related issue/PR: #489 
* Style does not support variables as indices for now, e.g. `a = 3; myMatrix[a][1]` is not allowed
* `findExpr` deals correctly with list lookups
* Style does not support color accessors, e.g. `color.r`, `color.g`, `color.b`, `color.a`
`roger watch linear-algebra-domain/twoVectorsPerp-unsugared.sub linear-algebra-domain/linear-algebra-paper-simple.sty linear-algebra-domain/linear-algebra.dsl`
Maybe add Style support for those minor unsupported language features in the future.
=> fix: style path validation code or remove unsupported style program features so LA example works

packages/core/src/compiler/Style.test.ts, packages/core/src/engine/EngineUtils.ts
Skip access path checks for `u.vector[0]` to work in Style.
=> fix: skip static check for access paths

examples/graph-domain/graph-theory-extended.dsl, examples/graph-domain/graph-theory.dsl, examples/graph-domain/graph-theory.sty, examples/graph-domain/graph1-extended.sub, examples/graph-domain/graph1.sub, examples/graph-domain/notes.md, examples/set-theory-domain/continuousmap.sty, packages/core/src/contrib/Constraints.ts, packages/core/src/contrib/Functions.ts, packages/core/src/engine/Autodiff.ts, packages/core/src/engine/Evaluator.ts, packages/core/src/engine/Optimizer.ts
Related issue/PR: #434 #367 #319 #120
This PR adds a basic graph domain (with pure Penrose layout) and more standard library functions for Style (incl. functions, constraints, objectives, autodiff primitives). 
This reasons are to pilot the user study [e.g. building stdlib, reporting errors], to have a more complicated layout test case, and because it’s just a useful domain to have, since we've been wanting to build it since last summer.
For further documentation, see 2/25/21 meeting notes.
in `graph-domain`, run `roger watch graph1.sub graph-theory.sty graph-theory.dsl`
Added to the working examples page.
Also,
- Improve the graph layout; see TODOs in the Style file
- Especially address incorporating bbox dimensions (and why it slows down the opt a lot)
- Add more shapes: curved …
=> feat: Add basic graph domain and more standard library functions for Style

packages/core/src/compiler/Domain.ts, packages/core/src/compiler/Style.ts, packages/core/src/compiler/Substance.ts, packages/core/src/parser/ParserUtil.ts, packages/core/src/parser/StyleParser.test.ts, packages/core/src/types/errors.ts, packages/core/src/utils/Error.ts
Related issue/PR: #509 
Add `SourceLoc` to `ParserError` so the frontends can highlight the location. Also handle non-termination of parsers by checking `results`. See:  https://github.com/kach/nearley/issues/306
* new util function `lastLocation` that gets the last parsed location from `lexerState`
* refactored `ParserError`
* One new test case in `StyleParser.test`
=> fix: add source loc to parser errors; report unexpected EOF

packages/core/src/__tests__/overall.test.ts, packages/core/src/engine/Autodiff.ts, packages/core/src/engine/Evaluator.ts, packages/core/src/engine/Optimizer.ts, packages/core/src/index.ts, packages/core/src/types/types.d.ts
Related issue/PR: #511 #512
We need more granular codegen + evaluation for improving our solver, and for other uses like diagram generation.
Changes: Add a new API function `evalFns` to evaluate individual functions on the state (with no weights). Also, precompile each obj/constrfn and cache its energy and gradient in the state in `prepareState`.
- add a new API function for `evalFns`
- add `genFn` based on `genOptProblem`
- write a new version of `evalEnergyOnCustom` without the weight node stuff, and only on a single objective or constraint
- change existing `energyAndGradCompiled` so it accepts `MaybeVal<WeightInfo>`
- write a `genFns` wrapper that looks at all opt functions in the state and caches their info in the state, in an `{ fnName(args) => { energy, gradient } }` map
- write …
=> feat: [layout] add `evalFns` for individual opt fns, and compile each opt function

packages/browser-ui/package.json, packages/browser-ui/src/App.tsx, packages/browser-ui/src/inspector/views/Opt.tsx, packages/browser-ui/src/inspector/views/viewMap.tsx, packages/core/src/index.ts, yarn.lock
*Autostep and show inspector are now togglable across refreshes via localStorage. By default autostep's off and inspector's on.
* We added a simple sortable table with energies of functions. More features to come
=> feat: opt tab for inspector; localStorage settings

packages/core/src/compiler/Style.ts, packages/core/src/compiler/Substance.test.ts, packages/core/src/compiler/Substance.ts, packages/core/src/engine/EngineUtils.ts
Currently, the system would parse prelude values, but doesn't really include them in the rest of the compilation pipeline. This PR adds support for processing prelude values with nullary types in the Substance checker.
* Prelude declarations are retrieved from the Domain environment and translated to Substance statements by `toSubDecl``
* In `compileSubstance`, prelude values are appended to the parsed AST _before_ the checker runs (so that the checker can include metadata like varying mappings in the Substance environment)
* We do _not_ handle prelude values with dependent types for now.
* In `Substance.test.ts`, I added `value X: Set` to the common Domain program, and a test checks for prelude values.
=> feat: process prelude values in substance checker

packages/core/src/parser/Style.ne, packages/core/src/parser/StyleParser.test.ts
Related issue/PR: #543 
Parse comments and newlines after the GPI name in the Style parser
=> fix: K&R style braces in GPI exprs #543

packages/core/src/engine/Evaluator.ts, packages/core/src/renderer/Label.ts, packages/core/src/renderer/ShapeDef.ts, packages/core/src/utils/CollectLabels.ts
Related issue/PR: #294 
When the user `override` the `string` property of `Text` GPIs, the system reports an error in retrieving the label data. Our old code in `tex2svg` returns `undefined` whenever `string === ""`. Now that we have actual use cases from the domain expert study to "remove" a label, especially when `delete` is not straightforward.   
* Allow empty strings in `Text` and remove all the hacks in the system to handle them
* In `tex2svg`, check for `Infinity` to prevent `NaN` blow-up
https://panes.penrose.ink/gist/faf5f3cc108199b08c78c6da24a51531
=> fix: handle Text GPIs with empty strings #294

package.json
Add `chore(release): %s [skip ci]` to every release message. 
In general, our canary releases have two problems:
* The commit SHA is _not_ included in the NPM versions: https://github.com/lerna/lerna/issues/1893#issuecomment-583124032
* As a result, we run into duplicate version numbers immediately after a `latest` release. 
To avoid the duplicate canary releases, I added `[skip ci]` in the release commit message.
=> chore: add semantic commit message for release commits

examples/shape-spec/shape-spec.dsl, examples/shape-spec/shape-spec.sty, examples/shape-spec/shapes.sub, packages/browser-ui/src/inspector/views/Mod.tsx, packages/browser-ui/src/inspector/views/mod/AttrPicker.tsx, packages/browser-ui/src/inspector/views/mod/defmap.tsx, packages/browser-ui/src/inspector/views/mod/shapedefs/pathStr.json, packages/browser-ui/src/inspector/views/viewMap.tsx, packages/core/src/renderer/AttrHelper.ts, packages/core/src/renderer/Image.ts, packages/core/src/renderer/Label.ts, packages/core/src/renderer/PathString.ts, packages/core/src/renderer/ShapeDef.ts, packages/core/src/renderer/Square.ts, packages/core/src/renderer/shapeMap.ts, packages/core/src/utils/Util.ts
I added a `PathString` GPI.~~ It's not quite ready to merge because something's broken in the `mod` tab.~~ Fixed! I also need to document it in the wiki (?).
```ts
shapeType: "PathString",
properties: {
center: ["VectorV", vectorSampler],
w: ["FloatV", widthSampler],
h: ["FloatV", heightSampler],
rotation: ["FloatV", () => constValue("FloatV", 0)],
opacity: ["FloatV", () => constValue("FloatV", 1.0)],
strokeWidth: ["FloatV", strokeSampler],
strokeStyle: ["StrV", () => constValue("StrV", "solid")],
strokeColor: ["ColorV", colorSampler],
color: ["ColorV", colorSampler],
name: ["StrV", () => constValue("StrV", "defaultPolygon")],
data: ["StrV", () => constValue("StrV", DEFAULT_PATHSTR)],
viewBox: ["StrV", () => constValue("StrV", "0 0 100 100")],
},
positionalProps: ["center"],
```
It …
=> feat: PathString GPI

packages/browser-ui/package.json, yarn.lock
Related issue/PR: #557 
`canvas` is unused in `@penrose/browser-ui` and causes `gyp` related installation problems on platforms like Windows.
=> fix: remove `canvas` from dependency list #557

package.json
Related issue/PR: #578 
The instruction in our PR template asks contributors to run `yarn docs`, but it's unclear where to run it. To be consistent with the instruction about `yarn test`, I added a convenience script at the top level.
=> chore: add a top-level `docs` script

packages/core/src/analysis/SubstanceAnalysis.ts, packages/core/src/synthesis/Synthesizer.test.ts, packages/core/src/synthesis/Synthesizer.ts, packages/synthesizer/__tests__/geo-settings.json, packages/synthesizer/__tests__/geometry.dsl, packages/synthesizer/__tests__/tri-settings.json, packages/synthesizer/__tests__/tri-template.sub, packages/synthesizer/package.json
Added additional edit mutation to synthesizer, specifically **type-change**. For example, `Collinear(A,B,C)` -> `Triangle t := mkTriangle(A,B,C)`
Related issue/PR: # (issue/PR)
* Implemented type-change edit functionality for synthesizer
* Implemented cascading-delete functionality for synthesizer (if a ref is deleted, remove all other occurrences of the ref in the AST)
* Created additional substance file to use for testing the type-change and/or cascading delete functionality
* A bit of refactoring of current synthesizer code for modularity
* Fixed bug that was allowing fall-through in synthesizer
* Added some …
=> feat: type-change implemented for synthesizer

packages/core/src/analysis/SubstanceAnalysis.ts, packages/core/src/compiler/Substance.ts, packages/core/src/synthesis/Synthesizer.ts
Fixes a bug where `typeChange` mutation in the synthesizer module was adding undefined statements to the AST, because the way new `Bind` statements were being created was improper. 
* Refactored `Synthesizer` code to use `generateConstructor`, `generateFunction` and `generatePredicate` functions.
* Added option for each of these methods to take in a pre-selected declaration instead of randomly picking one (which will also help out with testing later on)
* Refactored so that `Add/Edit/Delete` mutation operations are added by the `Synthesizer` instead of by `SynthesizerContext`.
Validate correct functionality by running `yarn set-example` or `yarn tri-example` from `packages/synthesizer`
=> fix: type-change in synthesizer was adding improperly formed bind statements to AST

examples/graph-domain/disjoint-rect-line-horiz.sty, examples/graph-domain/disjoint-rect-line-vert.sty, examples/monoidal-category-domain/monoidal-test.sty, packages/core/src/contrib/Constraints.ts, packages/core/src/contrib/Functions.ts, packages/core/src/engine/BBox.ts, packages/core/src/types/ad.ts
Though `Square` is a rect-like shape, it does not expose the same interface of `w` and `h` like other rect-likes, which causes many constraint implementations to fail on squares.
This PR enhances the `bbox` function to compute `w`, `h`, and `center`.
Additionally, this PR moves the implementation of line-like bboxes into `bbox`. This also consolidates `disjointRectLineAAVert` and `disjointRectLineAAHoriz` into one constraint `disjointRectLineAA`.
=> fix: Unify BBox Computation in `Constraints.ts` and Make `Square` Rect-Like

packages/core/src/synthesis/Synthesizer.test.ts, packages/core/src/synthesis/Synthesizer.ts
Related issue/PR: #590 
Continuing the effort to localize calls to random generators in #590, I refactored the code base to only use random generators within the `Synthesizer` class. This will be useful for testing and some other future features to come.
* Replaced the default `choice` and `random` functions from `pandemonium` with custom ones using their `createChoice` and `createRandom` constructors. 
* The new custom `choice` and `random` functions can only be called within the `Synthesizer` class
* Added `seed` to the constructor arguments of `Synthesizer`, which defaults to `synthesizerSeed `
In `packages/synthesizer/index.ts`, add a fourth argument to `new Synthesizer(...)` and the results will change depending on your random seed.
=> refactor: add determinism to synthesizer

.circleci/config.yml
Related issue/PR: #597 
Instead of using the default `remote origin`, explicitly specify the repo URL when publishing docs via `gh-pages`. The default is no longer valid for unknown reasons.
=> fix(#597): invalid URL during docs deploy workflow

packages/core/src/contrib/Constraints.ts, packages/core/src/renderer/Arrow.ts, packages/core/src/renderer/Line.ts
Closes #586.
I extended the Line renderer in `renderer/Line.ts` to compute the heights of the arrowheads and shrink the main path accordingly. To compute the height of the arrowhead, you multiply the arrowhead style's height by the size specified in Penrose. This value controls the `markerHeight` of the arrowhead. You then have to multiply by the unit for the markerHeight, which is the `stroke-width` of the line. See https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/markerUnits for details.
To compute the amount of distance to shave off the ends of the path I used the formula in this Math Stack Exchange post: https://math.stackexchange.com/a/2045181. It is fairly straightforward: Compute the vector of the difference between the points, then shave off a fraction of that vector …
=> fix: arrowheads incorporated in the path length

.circleci/config.yml, .github/workflows/typedocs.yml
In preparation for a more unified workflow, we'll no longer use circleci to build typedocs (and other docs).
**PLZ SQUASH. LOTS OF EMBARRASSING ERRORS IN MY COMMITS**
Also, the typedoc will be moved to https://penrose.github.io/penrose/typedoc
=> chore: change typedoc build to gh-pages

packages/core/src/contrib/Constraints.ts, packages/core/src/contrib/Functions.ts, packages/core/src/synthesis/Synthesizer.ts, packages/synthesizer/__tests__/c4p1.sub, packages/synthesizer/__tests__/congruent-settings.json, packages/synthesizer/__tests__/euclidean.sty, packages/synthesizer/__tests__/geometry.dsl, packages/synthesizer/package.json
* Added ability to render right angle markers for Euclidean angles, using `RightMarked(a)` predicate
* Added ability to make an angle appear as though it is a right angle, without the marker, using the `RightUnmarked(a)` predicate
* Fixed a bug in the `Synthesizer` that was caused by the `Swap` mutation attempting to swap arguments in functions/predicates/constructors that only have one argument
* Added an `unordered_collinear` constraint to `Constraints.ts` as an option to make points collinear without needing to specify their order in substance. for ex the relevant substance for this diagram was `Collinear(B,C,D)`:
With the `collinear` constraint function, the points would be ordered as `B,C,D`, with `C` in the middle. However, since I used `collinear_unordered`, the points are ordered …
=> feat: add right angle marker to euclidean style

packages/browser-ui/src/inspector/views/Opt.tsx, packages/browser-ui/src/inspector/views/viewMap.tsx, packages/core/src/__tests__/overall.test.ts, packages/core/src/index.ts, packages/core/src/utils/OtherUtils.ts
Closes #593.
Closes #609.
The current optimization tab is misleading, because it groups constraints and objectives together even they they function differently. Constraints _must_ be 0 in a properly converged diagram. Objectives should be minimized, but neither their values nor their gradient norms are required to be 0.
This PR renames the optimization tab from `opt` to `optimization status` and separates the data into two tables with the following content:
Constraints:
- Expression
- Energy (now constrained to be non-negative)
- Satisfied? (now bounded by an epsilon)
Objectives:
- Expression
- Gradient Norm
Additionally, this PR improves pretty printing for UOp and BinOp nodes so they don't print as JSON.
- `evalFns` in `index.ts` now returns both the function value and its gradient.
- …
=> feat: Split Optimization Status Tab Into Constraints and Objectives

examples/geometry-domain/euclidean-simple.sty, packages/core/src/contrib/Constraints.ts, packages/synthesizer/__tests__/euclidean.sty
Using `repel` to ensure that text labels are a certain distance from a segment causes optimization times of between 10-15 seconds. Based on the discussion in related issue #607, implemented 2 changes:
* Added a constraint `closestPtToSeg` that ensures a given point is a certain distance away from the **nearest point on a given segment**. As @hypotext mentions in the issue, this is faster because it does not involve sampling the distance at multiple points of the segment. After implementing this objective, the resample time drops from 10-15 seconds to 2-6 seconds.
* Per @joshpoll suggestions, added a constraint `nonDegenerateAngle` to push angles to be within a reasonable range (avoid 0 and 180-degree angles). At the moment, this is implemented with a cutoff, so any angles between 10 and …
=> fix: repel objective on segments causes slow optimization time

packages/browser-ui/package.json, packages/browser-ui/src/App.tsx, packages/core/src/engine/Optimizer.ts, packages/core/src/types/errors.ts, packages/core/src/utils/Error.ts, yarn.lock
Related issue/PR: #592
Catch errors thrown in `core` in `browser-ui`. Also fix dependency error for cytoscape.
Use `try-catch` statement around any `browser-ui` call to `core` that might throw error, including `stepState` and `stepUntilConvergence`; report it in inspector and in console
Add a `throw Error` to anywhere in `core` (e.g. `NaN` in optimizer)
Questions that require more discussion or to be addressed in future development: 
- Get this functionality to work in the IDE
=> fix: Catch errors thrown in `core` in `browser-ui`

examples/set-theory-domain/venn.sty, packages/browser-ui/src/App.tsx, packages/core/src/__tests__/overall.test.ts, packages/core/src/engine/Optimizer.ts, packages/core/src/index.ts, packages/core/src/types/ad.ts, packages/core/src/types/errors.ts, packages/core/src/types/state.ts, packages/core/src/utils/Error.ts
Created a new subtype of RuntimeError to accommodate NaNs encountered at runtime.  The client should no longer hang when encountering a NaN. 
- [ X ] I have commented my code, particularly in hard-to-understand areas
- [ X ] My changes generate no new warnings
- [ X ] New and existing tests pass locally using `yarn test`
- [ X ] My code follows the style guidelines of this project (e.g.: no ESLint warnings)
=> chore: new nanerror Penrose error + full propagation 

examples/set-theory-domain/venn.sty, packages/core/src/index.ts
Related issue/PR: #498
Resolved NaN in nested.sub example by increasing maximum size of circles representing sets to accommodate the amount of nesting in this example without creating unsatisfiable constraints.
N/A
- Seems brittle; tests fail (the "cross-instance energy evaluation") if `maxSize`'s parameter is decreased to, e.g. `canvasSize/1.5`.
=> fix: resolved NaN in the nested.sub by increasing the max size of sets shapes #498

packages/browser-ui/src/App.tsx, packages/core/src/index.ts
=> fix: unwrap the result of `stepUntilConvergence` in `browser-ui`

examples/set-theory-domain/tree.sub, packages/automator/index.tsx, packages/browser-ui/src/App.tsx, packages/browser-ui/src/inspector/makeViewBoxes.tsx, packages/browser-ui/src/inspector/views/GraphUtils.ts, packages/browser-ui/src/inspector/views/Mod.tsx, packages/browser-ui/src/inspector/views/mod/AttrPicker.tsx, packages/browser-ui/src/inspector/views/mod/LabeledInput.tsx, packages/browser-ui/src/ui/Embed.tsx, packages/core/src/index.ts, packages/core/src/renderer/Renderer.ts, packages/core/src/types/io.ts, packages/synthesizer/index.ts
Currently in `main`, the functions exported from `@penrose/core` sometimes have `any` as their return types whenever a client package (e.g. `@penrose/browser-ui` use them. Notable behaviors are the lack of auto-completion when developing in VSCode and uncaught type errors across packages. 
This PR fixes this issue by __re-exporting functions from relative paths__ and further change all client packages to fix the errors uncaught in the past.
* Change all imports in `packages/core/index.ts` to use relative path
* Explicitly re-export the `Result` type from `true-myth` at the top level.
Although this solution works, the exact cause of this issue is still unknown. My guess is that this has something to do with our `rootDir` and `baseUrl` settings in `tsconfig.json`.
=> fix: return types in exported functions

examples/geometry-domain/euclidean.sty, examples/geometry-domain/textbook_problems/c07p22.sub, packages/core/src/contrib/Functions.ts
Previously, the `EqualLengthMarker` predicates would render `x` ticks directly on top of each other, making it look like there was only one tick at any given time. This PR makes them render properly.
* Used the new PathBuilder class to make the SVG path easily
* The function that was added in Functions.ts can be easily recycled in the future when we are able to iteratively add tick marks to any segments with `EqualLengthMarked` without explicitly calling `EqualLengthMarker1` `EqualLengthMarker2` `EqualLengthMarker3`
1. check out this branch, `yarn start`
2. `npx roger watch examples/geometry-domain/textbook_problems/ex.sub examples/geometry-domain/euclidean.sty  examples/geometry-domain/geometry.dsl`
3. This example will often lay the triangles directly on top of each other but you can …
=> feat: added multiple tick mark functionality to euclidean style

packages/core/src/engine/Evaluator.ts
Related issue/PR: #581
Allows vectors to be multiplied by a scalar
=> fix:  allow vectors to be multiplied by a scalar

.gitignore, .vscode/extensions.json
This PR adds `.vscode/extensions.json`, to automatically recommend useful extensions like Monorepo Workspace.
=> chore: Add VS Code recommended extensions

package.json
Related issue: #651 
Build sequentially in CI to avoid OOM error caused by default build parallelization in Circle CI medium Docker instance.  
Another fix option discussed: change the resource type on the Circle CI Docker instance to one with more RAM.  Removing parallelization allows us to avoid switching resource types and CI plans without much difference in build time.  
Instruct lerna to limit build concurrency to 1 vs. lerna's default, which is based on the underlying CPU & core count.
Repeatedly re-run build in CircleCI.  Observe consistently successful build vs. previous intermittent failures.
At a later point, provisioning more build resources and re-introducing build parallelization may be prudent.  But right now, our build times are short and we do not have a large number of …
=> fix: Circle CI OOM error when building #651

packages/core/src/contrib/Constraints.ts, packages/core/src/contrib/Functions.ts, packages/core/src/renderer/Renderer.ts, packages/core/src/renderer/ShapeDef.ts, packages/core/src/utils/CollectLabels.ts
For line-like shapes (e.g. `Line`), `RenderInteractive` set the `pointer-event` attribute to `bounding-box`. Changing it such that we use `isRectlike` and `isLinelike` to determine the correct value. For instance, `pointer-event: visibleStroke` works better for line-like shapes.
=> fix: determine `pointer-event` for dragging based on shape kind

package.json, packages/panels/package.json, packages/panels/src/App.tsx, packages/panels/src/DomainPane.tsx, packages/panels/src/StylePane.tsx, packages/panels/src/SubstancePane.tsx, packages/panels/src/languages/DomainConfig.ts, packages/panels/src/languages/StyleConfig.ts, packages/panels/src/languages/SubstanceConfig.ts, packages/panels/src/languages/common.ts, packages/panels/tsconfig.json
Related issue/PR: #659 
`@penrose/panels` doesn't highlight Domain programs. This PR adds language configuration for the Domain language.
* Separate `languageConfigs` into individual modules and add `DomainConfig`. 
* Fix small issue with errors related to `@brackets`
Run `yarn start:ide` at the top-level and write a Domain program!
* I noticed the Style config hard code a lot of things. Perhaps we can export the keywords, type annotations, or even constraint/computation dicts from `core` to fix this.
=> feat: Domain syntax highlighting

packages/core/src/engine/EngineUtils.ts, packages/core/src/engine/Evaluator.ts, packages/core/src/engine/Optimizer.ts, packages/core/src/index.ts, packages/core/src/renderer/Resample.ts, packages/core/src/renderer/dragUtils.ts, packages/core/src/types/shape.ts, packages/core/src/utils/Util.ts
Related issue/PR: #698 
The current implementation of `evalShapes` has unclear semantics: it takes in a `State` and return another. Instead, this PR refactors it (and related functions) s.t. it returns a list of shapes instead. Converstion from autodiff props to number props was done explicitly everywhere (e.g. `prepareState`).
=> refactor: make `evalShapes` number type agnostic

packages/core/src/contrib/Functions.ts, packages/core/src/engine/Autodiff.ts, packages/core/src/utils/Util.ts
Previously the documentation for `rot90` said that it rotates a point/vector clockwise. As far as I can tell, this is incorrect, so this PR modifies the documentation to say that it rotates counterclockwise.
=> fix: Document the fact that rot90 is counterclockwise

packages/core/src/contrib/Constraints.ts, packages/core/src/contrib/Functions.ts, packages/core/src/renderer/Path.ts, packages/core/src/renderer/ShapeDef.test.ts, packages/core/src/renderer/ShapeDef.ts, packages/core/src/types/ad.ts
Resolves #696.
This PR replaces the implementation of the `bboxFromShape` function (in `contrib/Constraints.ts`) with a call to the `bbox` method on the shape definition for the given shape type. That is, the `IShapeDef` interface (in `renderer/ShapeDef.ts`) is given a `bbox` field, and each shape definition in that file is given its own bbox implementation to use for that field.
The bbox implementations in this PR for the following shapes are precise modulo stroke width (as far as I am aware):
- `Circle`
- `Ellipse`
- `Rectangle`
- `Callout` (modulo some rendering weirdness)
- `Polygon` (see #709)
- `FreeformPolygon`
- `PathString` (I just use the given `center`, `w`, and `h`)
- `Polyline` (see https://github.com/penrose/penrose/issues/709#issuecomment-989203210)
- `Image` (modulo #712) …
=> feat: Define bounding box function for every shape

.gitignore, .vscode/extensions.json, .vscode/settings.json, penrose.code-workspace
When using the [Monorepo Workspace](https://marketplace.visualstudio.com/items?itemName=folke.vscode-monorepo-workspace) extension which we use for Penrose, a `*.code-workspace` file is automatically created to keep track of all the workspace folders (i.e. the root plus everything under `packages/`, when using standard [Lerna](https://lerna.js.org/) conventions).
So far, I had been simply keeping this in `~/penrose.code-workspace`, but earlier this morning I realized that using a `*.code-workspace` file causes everything in this repository's `.vscode/settings.json` file to be ignored. Then I learned that those [settings](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_settings) can actually be given in the `*.code-workspace` file itself, along with [extension …
=> chore: Use a .code-workspace instead of .vscode/ folder

packages/core/src/renderer/ShapeDef.test.ts, packages/core/src/renderer/ShapeDef.ts
Mostly resolves https://github.com/penrose/penrose/pull/698#issuecomment-1002015939
This PR accounts for the `strokeWidth` property when computing bounding boxes, as per @keenancrane's suggestion:
> So, let's consider what happens to the size of a shape if you stroke it by a stroke of width w. Giving a closed path a width w is equivalent to sweeping a circle of radius w/2 along that path. Hence, no matter which points are the extreme points along the path, the bounding box will need to grow by w/2 in all directions (top/bottom/left/right). So, just add w to both the bounding box width and height.
The only shape for which this PR does not use that strategy is `Square`, because in that case it is more correct to add half the `strokeWidth` in all directions _before_ doing the rotation …
=> feat: Handle strokeWidth in bbox

MathTODO.md, packages/core/src/contrib/Functions.ts, packages/core/src/engine/Autodiff.ts, util/ad/GenerateCode.pl, util/ad/GenerateDerivatives.nb, util/ad/MathTODO.md, util/ad/README.md
Related issue/PR: # (issue/PR)
This PR makes essentially all of the library functions from JavaScript Math available in Style (as well as the autodiff engine).  Up until now, math library functions have been made available in Style on an as-needed basis.  As a result, Style programmers have needed to pause and implement such functions.  This PR hopefully provides all the low-level functions that will "ever" be needed (…ok, there's always something else someone wants!).
In particular, this table lists the functions provided by the JavaScript Math Object, and the corresponding functions in the autodiff engine/Style.
| JavaScript  | Autodiff.ts | Functions.ts | Notes
|-------------|-------------|--------------|-------
| `abs(x)`    | `absVal(x)` | `abs`        |
| `acos(x)`   | `acos(x)`   | …
=> feat: Math functions

examples/geometry-domain/geometry.dsl, examples/graph-domain/graph-theory-extended.dsl, examples/graph-domain/graph-theory.dsl, examples/hyperbolic-domain/hyperbolic.dsl, examples/logic-circuit-domain/logic-gates.dsl, examples/mesh-set-domain/DomainInterop.dsl, examples/molecules/molecules.dsl, examples/structural-formula/structural-formula.dsl, packages/core/src/compiler/Domain.test.ts, packages/core/src/compiler/Domain.ts, packages/core/src/parser/Domain.ne, packages/core/src/parser/DomainParser.test.ts, packages/core/src/types/domain.ts
Resolves #722.
The first commit in this PR renamed the `type` `statement` rule to `type_decl`, because previously it was being combined with the other `type` rule below, which would have caused ambiguous parsing after adding the syntax extension this PR adds.
I'm not sure why `SubTypeDecl`'s fields are `Type` instead of `TypeConstructor` since the compiler throws an error if they aren't the latter, but I've kept that the same in this PR.
This PR updates most things in `examples/` to use the more concise syntax.
- Should we even keep around `SubTypeDecl` at all? (Note: a few places in `examples/` still use it.)
- Currently this PR only allows the comma syntax (for specifying multiple supertypes) in `TypeDecl`, not `SubTypeDecl`; should that syntax be allowed in the latter as well?
- Should …
=> feat: Allow subtypes inline

examples/existential-graph-domain/existential-graph.dsl, examples/geometry-domain/geometry.dsl, examples/graph-domain/graph-theory-extended.dsl, examples/graph-domain/graph-theory.dsl, examples/hyperbolic-domain/hyperbolic.dsl, examples/linear-algebra-domain/linear-algebra-test.dsl, examples/linear-algebra-domain/linear-algebra.dsl, examples/logic-circuit-domain/logic-gates.dsl, examples/mesh-set-domain/DomainInterop.dsl, examples/molecules/molecules.dsl, examples/monoidal-category-domain/monoidal-test.dsl, examples/set-theory-domain/setTheory.dsl, examples/structural-formula/structural-formula.dsl, packages/core/src/analysis/SubstanceAnalysis.test.ts, packages/core/src/compiler/Domain.test.ts, packages/core/src/compiler/Substance.test.ts, packages/core/src/parser/Domain.ne, packages/core/src/parser/DomainParser.test.ts, packages/core/src/parser/Style.ne, packages/core/src/parser/Substance.ne, packages/core/src/parser/macros.ne, packages/core/src/synthesis/Search.test.ts, packages/core/src/synthesis/Synthesizer.test.ts, packages/synthesizer/__tests__/geometry.dsl, packages/synthesizer/__tests__/setTheory.dsl, packages/synthesizer/__tests__/spec.dsl
Resolves #312. That issue only gives examples for `predicate`, and only mentions that and `function`, but this PR also updates the syntax for `constructor`.
A few things I noticed:
- Previously we had a special case for zero args, where no colon would be used. Now that we delimit the arglist with parentheses, I removed that special case for greater consistency.
- I'm a bit confused about the syntax for what look like generics? They seem to use round parentheses in the `type` declaration, then square brackets when listing them before the arglist for a `constructor`, then round parentheses again in the actual arglist. Those latter parentheses are a bit less readable with the new arglist syntax in my opinion, but not terrible; still, it seems like it may be a better idea to make them all …
=> feat: Use C-style syntax for Domain arglists

penrose.code-workspace
This PR enables **Search: Use Parent Ignore Files** (added by https://github.com/microsoft/vscode/pull/140022) in our VS Code workspace, preventing gitignored files (e.g. those in `packages/core/build/dist/`) from showing up in search when they shouldn't. Currently this setting is only available in VS Code Insiders, but even for Stable VS Code users, it causes no harm to include it now and will begin to take effect in the next VS Code release that includes this feature.
=> chore: Use parent ignore files in VS Code

penrose.code-workspace
This PR sets the VS Code formatter to [Prettier](https://github.com/prettier/prettier-vscode) for all the languages to which it seems to apply:
https://github.com/penrose/penrose/blob/d99c216255522b25b0a85baf395060baf86bfcb6/package.json#L22-L23
=> chore: Use Prettier in VS Code

package.json, yarn.lock
This PR removes our pre-push hook; it's unnecessary because
- `main` is protected so we can't push to it directly, and
- PRs can't be merged until they pass CI.
=> chore: Remove husky and its pre-push hook

packages/core/src/compiler/Style.ts, packages/core/src/compiler/Substance.test.ts, packages/core/src/compiler/Substance.ts, packages/core/src/types/substance.ts
Related issue/PR: #752 
When `NoLabel` is used or no labeling statements exist for a Substance variable, the current system doesn't insert a `label` field for that variable in the `Translation`. This often causes expected errors. In this PR, we change the default to __empty strings as default labels__ even when there's no labeling statements. 
* #752 also uncovers a bug in the Substance checker: we didn't check the variables of statements like `AutoLabel A, B, C`. Added the checking in the Substance checker.
* Changed Substance postprocessing to insert default `""` labels for every variable and insert `""` for `NoLabel` statements
=> fix: use empty string as the default label and check autolabel statements

packages/core/src/compiler/Style.ts, packages/core/src/types/state.ts
Fixes #756 
As reported in #756, the Style selector matching algorithm incorrectly matches constructors with the same arguments. The reason is that it doesn't check if the constructor names are actually the same before proceeding to checking the argument types and values.
Add an additional condition in `exprsMatchArr` and documented the matching conditions.
See #756.
=> fix: check constructor name match in Style selector

examples/set-theory-domain/venn.sty, packages/core/package.json, packages/core/src/compiler/Style.test.ts, packages/core/src/compiler/Style.ts, yarn.lock
Fixes #730 
When the partial layer orderings from Style (e.g. `A.text above A.icon`) contain cycles, our system throws an error and refuses to render a diagram since there's no topological ordering of shapes. In this PR, we introduce an approximation of topSort. Instead of failing directly, the system attempts a best-effort algorithm to approximate a global ordering. Here's a brief description from @keenancrane:
* We do cycle detection in `topSortLayering` and proceed as normal when the graph is a DAG
* Else, we use the new algorithm `pseudoTopsort`
* In `pseudoTopsort`, the heuristic is we always pick the node with the lowest in-degree to avoid breaking the cycles too early. The result tend to preserve most of the intended orderings.
* Added tests to `Style.test.ts`
See `Style.test.ts`. …
=> feat: allow cycles in partial layer orderings

.github/workflows/build.yml
This PR includes a couple additional commits that I meant to include in #755 but forgot. It also fixes another bug in the "Authenticate with registry" step that I didn't notice before but did notice after CI failed on `main`:
- https://github.com/penrose/penrose/runs/4742741785?check_suite_focus=true
=> fix: GitHub Actions canary release

packages/core/src/compiler/Style.test.ts, packages/core/src/compiler/Style.ts, packages/core/src/compiler/Substance.test.ts, packages/core/src/compiler/Substance.ts, packages/core/src/parser/Style.ne, packages/core/src/parser/StyleParser.test.ts, packages/core/src/parser/Substance.ne, packages/core/src/types/errors.ts, packages/core/src/types/style.ts, packages/core/src/types/substance.ts, packages/core/src/utils/Error.ts, packages/panels/src/languages/StyleConfig.ts
Closes #774 
In this PR, we introduce a new Style selector pattern: `X has <math|text> label`. When included in the `where` clause of a selector, the compiler checks if `label` exists and whether it matches with the specified descriptor. Examples:
* `Label x $\vec{x}$` will match with `where x has math label`
* `Label x "xxxx"` will match with `where x has text label`
* Both of the above will match with `where x has label`
* `NoLabel x` will not match with `where x has label` nor `where x has math/text label`
Error handling:
* Only `math` and `text` are valid field descriptors. All others will result in parse errors
* `label` is the only field name allowed, but instead of throwing a parse error, the compiler reports `SelectorFieldNotSupported` error:
```
Cannot match on field x.blah (line …
```
=> feat: check existence and type of labels in Style selectors

packages/roger/package.json
Continuing to try to fix the GitHub Actions canary release: https://github.com/penrose/penrose/runs/4743590685?check_suite_focus=true
=> fix: Upgrade TypeScript for roger prepack

.github/workflows/build.yml
Still trying to fix the GitHub Actions canary release: https://github.com/penrose/penrose/runs/4743970903?check_suite_focus=true
=> ci: Set env.CI to false in the entire build job

packages/core/src/compiler/Style.ts
Fix: #787 
When there's no field descriptor in the field selector pattern, the Style compiler incorrectly assumes the return must be true if there's an entry in the label map. However, there's the possibility of empty strings, so we need to explicitly check if the string is empty.
Add string length check in `relMatchesProg`.
https://500d1995.penrose-panes.pages.dev/gist/6a441188eb78ca88e7d495449cee2f1d
=> fix: empty label check in Style selector

.gitignore, packages/browser-ui/tsconfig.json
It seems that upgrading TypeScript in #798 broke CI again: https://github.com/penrose/penrose/runs/4766221596?check_suite_focus=true
```
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove the following changes before continuing:
lerna ERR! EUNCOMMIT  M packages/browser-ui/tsconfig.json
lerna ERR! EUNCOMMIT ?? .npmrc
```
So this PR attempts to fix those errors by doing the following:
- Update `packages/browser-ui/tsconfig.json` by running `yarn build` locally and committing that
- Add `.npmrc` to `.gitignore`
=> ci: Fix canary release

packages/core/src/engine/BBox.ts
This PR removes rectangle rotation due to performance issues in testing, particularly with testing in CI due to the heavy use of rectangles in the test suite.  Rotation of rectangles is presently less important than performance.
The performance issue behind rectangle rotation will need to be investigated and the functionality re-introduced into the codebase.
=> fix: Remove Rectangle Rotation BBox logic

packages/browser-ui/src/App.tsx, packages/browser-ui/src/ui/ButtonBar.tsx
Initially suggested by @keenancrane: the number of steps the optimizer takes when auto-stepping should be configurable in `browser-ui`. A smaller step size shows more of the optimization process as "animation", but will take longer to converge due to repeated evaluation. This PR updates the default step size to `50` for a good balance: 
If `autoStepSize === 1`:
=> fix: show animation when optimizing with configurable autostep size

packages/browser-ui/src/inspector/views/GraphUtils.ts
Related issue/PR: # (issue/PR)
This is a two-line fix to restore browser-ui after changes to graph navigation methods.
=> fix: two changes to browser-ui to adapt to the new navigation methods

README.md
I should have included this in #755 but forgot.
=> chore: Replace CircleCI badge with GitHub Actions

examples/fancy-text/fancy-text.sty, packages/core/src/parser/Style.ne
Closes #794
This PR adds the ability to use Greek letters in style identifiers.
Adapted style identifier regex to allow Greek characters in positions 1-n.
Run the fancy-text example, which now includes a Greek identifier.
None.
=> feat: Allow Greek letters in style identifiers

.github/workflows/build.yml, package.json, packages/core/.eslintrc.js, packages/core/src/engine/EngineUtils.ts, packages/core/src/engine/Evaluator.ts, packages/core/src/renderer/Staging.ts, packages/core/src/utils/Error.ts
This PR does the following:
- Add a `lint` script to our root `package.json` which runs `lint` in any packages that include it (currently just `core` and `browser-ui`, both of which just run ESLint)
- Add a `lint` job to our Build workflow in CI which runs `yarn lint`
- Eliminate all ESLint _errors_, so the `lint` job passes
- Get rid of ESLint _warnings_ too
=> ci: Enforce no ESLint errors

.github/workflows/build.yml, packages/browser-ui/src/inspector/views/CompGraph.tsx
This PR adds a message when our `format` job fails in CI, to tell people how to run Prettier locally. Example: https://github.com/penrose/penrose/runs/4820765638?check_suite_focus=true
```
yarn run v1.22.17
$ prettier . --check
Checking formatting...
[warn] packages/browser-ui/src/inspector/views/CompGraph.tsx
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Run this command from the repository root:
yarn format
Then commit and push to re-run CI.
Error: Process completed with exit code 1.
```
=> ci: Add a nice message about how to run Prettier

packages/core/src/contrib/ConstraintsUtils.ts, packages/core/src/contrib/__testfixtures__/TestShapes.input.ts, packages/core/src/contrib/__tests__/Constraints.test.ts
Related issue/PR: #810
Fixing regression introduced by #810. Labels in example `examples/set-theory-domain` (`npx roger watch nested.sub venn.sty setTheory.dsl`) were not optimized correctly. This PR fixes the issue and adds test cases to `Constraints.test.ts`.
=> fix: circle-rectangle interactions

packages/core/src/renderer/AttrHelper.ts, packages/core/src/renderer/Polygon.ts, packages/core/src/renderer/Polyline.ts, packages/core/src/shapes/Polygon.ts, packages/core/src/shapes/Polyline.ts
Fixes: #724
The `points` property for `Polyline` and `Polygon` are currently passthrough properties. This PR adds `attrPolyPoints` for transforming a list of points to screen coordinates.
=> fix: transform polygon/polyline points to screen space

examples/hyperbolic-domain/PoincareDisk.sty
In the hyperbolic domain example set, PointcareDisk.sty lacks a canvas definition.  This PR resolves that issue.
=> fix: PointcareDisk.sty missing canvas def

packages/core/src/contrib/Objectives.ts
@keenancrane mentioned a repeated pattern of `encourage equal(<some value>, 0)`. After some discussion, we decided to add `maximal` and `minimal` for sending single values to inf or -inf. This is similar to saying "minimize" and "maximize" in optimization problems.
=> feat: `maximal` and `minimal` objectives

packages/core/src/index.ts
For some reason the `diagram` function in `index.ts` is missing a few line of code, perhaps a side-effect of refactoring. This PR adds the missing lines back.
=> fix: missing code in top-level `diagram` function

examples/linear-algebra-domain/linear-algebra-paper-simple.sty
This PR fixes some small issues `linear-algebra-paper-simple.sty`:
* Change to `ensure` the dot product to be zero for `Orthogonal` vectors
* File formatting. Mostly tab size. Original is very inconsistent.
* Remove testing code and stray comments.
`roger watch twoVectorsPerp-unsugared.sub linear-algebra-paper-simple.sty linear-algebra.dsl`
=> refactor: tweak linear algebra Style example

packages/core/src/engine/Autodiff.ts
Closes #869 
This is a non-functional change to remove a duplicate 'pow' conditional that could be confusing to future developers.
=> fix: Remove duplicate 'pow' conditional

.github/PULL_REQUEST_TEMPLATE.md
As of #864, we now have a `diagrams/` folder to track changes to the generated diagrams for everything in the [registry](https://github.com/penrose/penrose/wiki/Registry). The workflow is to run `yarn test overall` in `packages/core/` (then commit and push the results) if a PR causes any of those to change. However, tracking these only has any real value if people actually review changes to that folder, so this PR adds an item to the checklist to encourage people to do that.
Our `.gitattributes` file includes this line:
https://github.com/penrose/penrose/blob/538661853dc231ca3379fb4c7748aea7575d23a0/.gitattributes#L1
This is because GitHub displays text diffs for SVG files by default, so it makes sense to hide those to avoid cluttering up the GitHub diff view. To view an actual image diff …
=> chore: Add "look at diagrams/" to PR checklist

penrose.code-workspace
While reviewing #897, I realized that VS Code doesn't have built-in support for [MDX](https://mdxjs.com/). Via a quick search, I found three extensions for the language:
- [MDX](https://marketplace.visualstudio.com/items?itemName=silvenon.mdx)
- [MDX Preview](https://marketplace.visualstudio.com/items?itemName=xyc.vscode-mdx-preview)
- [VSCode MDX](https://marketplace.visualstudio.com/items?itemName=JounQin.vscode-mdx)
This PR adds the most popular of those three as a recommended extension for working on Penrose.
(aside: [Prettier](https://prettier.io/) says it works on MDX, but it seems to completely ignore the `*.mdx` files in the Penrose repo... anyone know why?)
=> chore: Add MDX extension to penrose.code-workspace

.prettierignore, docs/graphical-api.md, docs/mathtransformer.md, packages/core/.gitignore
As I mentioned in https://github.com/penrose/penrose/pull/899#issuecomment-1055733958, we haven't been running Prettier on any folders named `docs/` due to a bug in our `.prettierignore`. This PR fixes that, and also adds `packages/core/docs/` to `.gitignore`.
=> style: Run Prettier on docs/ folders

penrose.code-workspace
I haven't yet noticed any discrepancies between Prettier and what VS Code is currently doing, but this can't hurt.
This is a followup to #899: https://github.com/silvenon/vscode-mdx/blob/v0.1.0/package.json#L26
=> chore: Explicitly use Prettier in VS Code for MDX

packages/synthesizer-ui/package.json
I'm guessing this is just an oversight?
=> chore: Prefix synthesizer-ui name with @penrose

packages/examples/package.json
Hopefully this fixes the canary release: https://github.com/penrose/penrose/runs/5431152530?check_suite_focus=true#step:6:78
> ```
> lerna http fetch PUT 402 https://registry.npmjs.org/@penrose%2fexamples 498ms
> lerna ERR! E402 You must sign up for private packages
> ```
=> ci: Make @penrose/examples private

packages/browser-ui/src/contexts.tsx
@jiriminarcik discovered today that `yarn start` currently gives this error:
```
@penrose/core: yarn run build-decls exited (0)
@penrose/browser-ui: src/contexts.tsx(1,1): error TS1208: 'contexts.tsx' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.
```
It seems to have been caused by the deletion of this line by #883:
https://github.com/penrose/penrose/blob/c1626cfdc7936fe7d4c0e6d7fcba9688f346313a/packages/browser-ui/src/contexts.tsx#L1
I'm very confused how none of us discovered this error earlier since that PR was merged a month ago, but in any case, this fixes it.
=> fix: Delete packages/browser-ui/src/contexts.tsx

packages/core/src/utils/Util.ts
This was originally added in #817 but for some reason I didn't realize that the length check condition is completely wrong.
=> fix: Strengthen length check in zip3

packages/core/src/engine/Evaluator.ts
Fix: #922 
In `evalBinOp`, pattern match on string-type arguments to `+`, and perform plain string concatenation of them.
This is only lightly tested, and we don't really have a suite for `Evaluator`. We should have one fairly soon though!
=> chore: evaluate binary addition on strings as concatenation

packages/docs-site/docusaurus.config.js, packages/docs-site/package.json, yarn.lock
The ["Writing Constraints & Objectives"](https://penrose.cs.cmu.edu/docs/tutorial/constraints) page in the tutorial contains some TeX expressions that are not rendered. This PR adds KaTeX support to render them.
Mostly followed the docs here: <https://docusaurus.io/docs/markdown-features/math-equations>
=> fix: math notations in tutorial pages

.github/workflows/build.yml, packages/core/.eslintrc.js, packages/core/.gitignore, packages/core/jest-bench.config.ts, packages/core/package.json, packages/core/src/__benchmarks__/compilation.bench.ts, packages/core/tsconfig.json, yarn.lock
Resolves #898.
We use [jest-bench](https://www.npmjs.com/package/jest-bench). Thanks @wodeni for figuring out how to get this to work with TypeScript!
Currently, the benchmarks get run in CI via a new `bench` job, which prints human-readable results in the log and also uploads machine-readable results as an artifact. Later we could add more sophisticated comparison/visualization if we want.
Run `yarn bench` from `packages/core/`.
- Currently the only benchmark is for energy graph compilation. We'll want other benchmarks before, e.g., merging #907.
=> perf: Add a benchmark suite

.github/workflows/lint-pr.yml
[Semantic PR](https://github.com/zeke/semantic-pull-requests)'s service is unstable. This PR adds a GitHub Action that does the same thing, which should be much more reliable.
=> ci: add semantic PR to GH Action

packages/automator/index.tsx
Fixes #935
The `draw` command in `@penrose/automator` calls `singleProcess` with the wrong arguments, notably missing `variation`. This PR adds an optional `--variation` option to the command and generate a random string for the variation seed if none is provided.
See #935
=> fix: `draw` command in `@penrose/automator`

packages/automator/README.md, packages/automator/index.tsx
This PR expands on PR #937 's fix (developed in parallel) to issue #935.  This PR additionally updates documentation and allows folder and cross-energy output in draw mode, similar to batch mode.
=> fix: Fix #935 Automator fails in draw mode

packages/core/src/compiler/Style.test.ts, packages/core/src/compiler/Style.ts, packages/core/src/compiler/Substance.test.ts, packages/core/src/compiler/Substance.ts
Related issue/PR: #638, #446  
(@samestep commented on the `disambiguateFunctions` function in #638, which reminded me of this issue)
There are two ambiguous parts of the Substance (and also Style selector) spec:
1. The right hand side of `Bind` could either be a constructor or function: `C := SubSet(A, B)`. It's syntactically impossible to see if `SubSet` is a function or constructor.
2. Nested predicate vs. anonymous function/constructor: In `Not(Intersecting(A, B))`, `Interesecting(A, B)`'s type cannot be determined by the parser.
To resolve 1 and 2, the current system parse both cases into a generic `Func` type and implements `disambiguateFunctions`, which mutates an AST, to resolve these issues. However, the Substance semantic checker is already doing similar work in functions like …
=>  refactor: produce semantically checked AST from the Substance checker

packages/core/src/compiler/Substance.ts
Mostly caused by interfering PR merges
=> fix: remove reference to `disambiguateFunctions` in `Substance.ts`

package.json, packages/browser-ui/index.html, packages/browser-ui/package.json, packages/browser-ui/src/App.tsx, packages/browser-ui/src/inspector/views/ShapeView.tsx, packages/browser-ui/src/inspector/views/viewMap.tsx, packages/browser-ui/src/vite-env.d.ts, packages/browser-ui/vite.config.js, packages/core/package.json, packages/panels/index.html, packages/panels/package.json, packages/panels/vite.config.js, yarn.lock
Resolves #913; see also #552 
As reported in #913, `serve-http` causes errors on Linux because it uses Node's `watch` function. We use `serve-http` for the estrella live-watch mode and unfortunately it's not actively maintained. Since we've already transitioned `synthesizer-ui` to vite, it makes more sense for us to use it for `panels` and `browser-ui`. 
* Add vite configuration to both packages
* Tested live-watch mode on OSX
* `yarn start` for `browser-ui`
* `yarn start:ide` for `panels`
* Still need to test on linux. @samestep can you try whenever you have a chance?
* I'm keeping estrella for building both packages, because I couldn't get `vite build` to work :(.
=> build: use vite for live-reload mode in `@penrose/panels` and `@penrose/browser-ui`

packages/automator/index.tsx
Resolves #887
This PR corrects an NPE in Automator's staged mode.  Starting with PR #825, `listOfCanvasData` was never initialized and executing in staged mode would always fail.  This bug was discovered via static analysis.
Initialized the variable `listOfCanvasData` prior to its use.
```
cd ./packages/automator
yarn start draw tree.sub venn.sty setTheory.dsl ./out/ --src-prefix=../examples/src/set-theory-domain --folders --staged
```
No open questions.
=> fix: Automator NPE in staged mode. Resolves #887

packages/automator/artifacts.ts, packages/automator/index.tsx, packages/automator/tsconfig.json
Recently we discovered some bugs in Automator.  These bugs would probably have been more obvious and had a briefer existence if more TypeScript checks were enabled in Automator.  This PR turns on most of the checks already enabled in core for Automator.  This required some code changes to correct uninitialized variables, etc. identified by these checks.
This PR enables the TypeScript checks currently present in core, with the exception of `noImplicitAny` and `strict`, which currently generate a fair number of errors if enabled.  The remaining work to resolve this is tracked in Issue #948 
Opened issue #948 to address the remaining two TypeScript checks.
=> chore: Enable more typescript checks for Automator

packages/components/src/Simple.tsx, packages/components/src/stories/Embed.stories.tsx, packages/components/src/stories/PenrosePrograms.tsx, packages/components/src/stories/Simple.stories.tsx, packages/core/src/compiler/Style.ts, packages/core/src/utils/CollectLabels.ts, packages/synthesizer-ui/src/components/Content.tsx, packages/synthesizer-ui/src/components/Gridbox.tsx
Related issue/PR: #535, #671
`Simple` is a raw canvas for Penrose-generated diagrams. In the past iterations, the component didn't handle errors and rendered a blank canvas. In this PR, whenever `Simple` encounters an error, it renders the pretty-printed error message directly on canvas.
* Remove `memoize` from `CollectLabels`
* Keep `error` in the state of `Simple`. This is mostly to let React handle re-rendering, which is a different case from `penroseState` (?)
* Used error rendering code from `browser-ui`
* Added errors to the storybook example
* Change Edgeworth to use `Simple` (see below)
In `synthesizer-ui`, I changed `Gridbox` so it's just a wrapper around `Simple`, a few minor notes:
* `Gridbox` has an overlay for mutation info and used to conditionally render the Penrose diagram …
=> feat: display errors in the `Simple` component

packages/components/src/Demo.tsx, packages/components/src/Listing.tsx, packages/components/src/editing/languages/SubstanceConfig.ts, packages/components/src/stories/Listing.stories.tsx, packages/core/src/analysis/SubstanceAnalysis.ts, packages/core/src/compiler/Domain.ts, packages/core/src/compiler/Substance.ts, packages/core/src/contrib/Minkowski.ts, packages/core/src/synthesis/Synthesizer.ts, packages/docs-site/package.json, packages/docs-site/src/components/DemoWrapper.js, packages/docs-site/src/pages/index.js, packages/panels/src/languages/SubstanceConfig.ts
This PR reenables the homepage demo which was added in #882 and then removed in #916. I don't remember the exact reasoning for removing the demo before; @cmumatt could you comment on this? If the problem is simply that the text should be tweaked, I can do that in this PR, I just wasn't sure exactly what needed to change.
In any case, now that #904 has made a `@penrose/examples` package available to `@penrose/docs-site`, we can simply use the more sophisticated trio we show in the README as of #955. The animation is pretty fun to watch, in my opinion.
Finally, thanks to @wodeni, this PR also adds dark mode support to the demo.
Webpack (which we use for Docusaurus) doesn't seem to correctly handle the spread operator for ES6 iterators. Specifically, given this:
```typescript
const [...foo] …
```
=> docs: Bring back the demo

packages/components/src/editing/languages/SubstanceConfig.ts, packages/core/src/analysis/SubstanceAnalysis.ts, packages/core/src/compiler/Domain.ts, packages/core/src/compiler/Substance.ts, packages/core/src/contrib/Minkowski.ts, packages/core/src/synthesis/Synthesizer.ts, packages/docs-site/babel.config.js, packages/panels/src/languages/SubstanceConfig.ts
This PR reverts all the iterator spread removal from #958, instead fixing the Docusaurus issue by disabling Babel's [`iterableIsArray`](https://babeljs.io/docs/en/assumptions#iterableisarray) assumption. This by itself doesn't quite work, as it introduces another error, but that can be resolved by setting `sourceType` to `"unambiguous"`: https://github.com/babel/babel/issues/9187#issuecomment-447704595
The relevant plugin for the original issue seen in #958 is `@babel/plugin-transform-spread`, which [uses `options.loose` as a fallback for the `iterableIsArray` assumption](https://github.com/babel/babel/blob/6dc633e71ef65943554e4087c39a4b939b0eadd0/packages/babel-plugin-transform-spread/src/index.ts#L16). Thus, my guess is that the problem was caused by Docusaurus's Babel preset [enabling …
=> build: Disable Babel's iterableIsArray assumption

packages/core/src/compiler/Domain.test.ts, packages/core/src/compiler/Domain.ts, packages/core/src/parser/Domain.ne, packages/core/src/types/domain.ts, packages/core/src/types/errors.ts, packages/core/src/utils/Error.ts
Previously `TypeDecl`'s `superTypes` field, `SubTypeDecl`'s `subType` and `superType` fields, and `PreludeDecl`'s `type` field were `Type`, but `compiler/Domain` checked that they were actually `TypeConstructor` and errored otherwise. This PR puts `TypeConstructor` into our grammar and gets rid of the `NotTypeConsInSubtype` and `NotTypeConsInPrelude` error types.
=> feat: Make NotTypeConsIn... into ParseError

packages/automator/index.tsx, packages/core/src/compiler/Domain.test.ts, packages/core/src/compiler/Domain.ts, packages/core/src/compiler/Style.ts, packages/core/src/compiler/Substance.test.ts, packages/core/src/contrib/Functions.ts, packages/core/src/parser/DomainParser.test.ts, packages/core/src/parser/StyleParser.test.ts, packages/core/src/parser/SubstanceParser.test.ts, packages/synthesizer/index.ts
This PR replaces [`map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) with [`forEach`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) whenever the returned array is ignored. See also: https://dev.to/smeijer/stop-mutating-in-map-reduce-and-foreach-58bf
- Is there a way to lint this automatically for the future?
=> refactor: Replace map with forEach when possible

packages/core/src/compiler/Domain.ts
When compiling a `TypeDecl`, the Domain compiler needs to wrap the `name` (an `Identifier`) into a `TypeConstructor`. Previously it was using the range of the whole `TypeDecl` statement as the range of this `TypeConstructor`, when it really should have just been using the range of the `Identifier`.
=> fix: Make TypeDecl subType range more precise

packages/core/.eslintrc.js, packages/core/package.json, packages/core/src/compiler/Style.ts, packages/core/src/contrib/Functions.ts, packages/core/src/parser/ParserUtil.ts, packages/core/src/utils/CollectLabels.ts, yarn.lock
This PR uses [`eslint-plugin-eslint-comments`](https://mysticatea.github.io/eslint-plugin-eslint-comments/) to disallow `eslint-disable` comments in `@penrose/core`. Many of the ones we already had were added by me in #817, and a couple by @wodeni in #829, but some of them were simply outdated.
=> test: Disallow eslint-disable comments in core

packages/core/.eslintrc.js, packages/core/src/compiler/Style.ts, packages/core/src/compiler/Substance.ts, packages/core/src/engine/EngineUtils.ts, packages/core/src/engine/Optimizer.ts, packages/core/src/synthesis/Synthesizer.ts, packages/core/src/utils/CollectLabels.ts
The [typescript-eslint docs](https://typescript-eslint.io/docs/linting/) recommend extending from both `plugin:@typescript-eslint/recommended` and `eslint:recommended`. Previously we were only using the former, so this PR adds the latter and fixes the resulting lint errors:
- [no-case-declarations](https://eslint.org/docs/rules/no-case-declarations)
- [no-constant-condition](https://eslint.org/docs/rules/no-constant-condition)
- [no-prototype-builtins](https://eslint.org/docs/rules/no-prototype-builtins)
- [no-useless-escape](https://eslint.org/docs/rules/no-useless-escape)
=> test: Extend from eslint:recommended in core

packages/core/.eslintrc.js, packages/core/src/analysis/SubstanceAnalysis.ts, packages/core/src/compiler/Domain.ts, packages/core/src/compiler/Style.ts, packages/core/src/compiler/Substance.ts, packages/core/src/contrib/Functions.ts, packages/core/src/engine/BBox.ts, packages/core/src/engine/EngineUtils.ts, packages/core/src/engine/Evaluator.ts, packages/core/src/engine/Optimizer.ts, packages/core/src/engine/PropagateUpdate.ts, packages/core/src/index.ts, packages/core/src/renderer/Image.ts, packages/core/src/synthesis/Mutation.ts, packages/core/src/synthesis/Synthesizer.ts, packages/core/src/utils/CollectLabels.ts, packages/core/src/utils/toCustomAD.ts
This PR enables [`@typescript-eslint/consistent-type-assertions`](https://github.com/typescript-eslint/typescript-eslint/blob/v4.5.0/packages/eslint-plugin/docs/rules/consistent-type-assertions.md) with `{ assertionStyle: "never" }` in `@penrose/core`, at the `"warning"` level because we currently have a bunch of them. I got rid of as many as I could without making nontrivial code changes:
- many were completely unnecessary and could be removed without any further changes
- many could be directly replaced with type annotations, which are safe and should always be preferred
- some could be replaced with non-null assertions, which are still unsafe but are less general and thus preferable
- we already have [`@typescript-eslint/no-non-null-assertion`](https://github.com/typescript-eslint/types …
=> test: Warn about type assertions in @penrose/core

packages/core/.eslintrc.js, packages/core/src/compiler/Style.ts, packages/core/src/contrib/Utils.ts, packages/core/src/engine/Autodiff.ts, packages/core/src/engine/EngineUtils.ts, packages/core/src/engine/Evaluator.ts, packages/core/src/renderer/Path.ts, packages/core/src/synthesis/Search.ts, packages/core/src/synthesis/Synthesizer.ts, packages/core/src/utils/CollectLabels.ts, packages/core/src/utils/Util.ts
This PR enables a few good typescript-eslint rules:
- [`@typescript-eslint/no-base-to-string`](https://github.com/typescript-eslint/typescript-eslint/blob/v4.33.0/packages/eslint-plugin/docs/rules/no-base-to-string.md) catches a bunch of places where we try to stringify things that would just show up as `"[object Object]"`; I didn't have the bandwidth in this PR to fix these so I just set this rule to `"warning"`, but they are all genuine bugs as far as I can tell
- [`@typescript-eslint/no-confusing-void-expression`](https://github.com/typescript-eslint/typescript-eslint/blob/v4.33.0/packages/eslint-plugin/docs/rules/no-confusing-void-expression.md) might be a bit more of a stylistic thing, but I think it's pretty good for clarity
- …
=> test: Enable a few good typescript-eslint rules

packages/core/src/analysis/SubstanceAnalysis.ts, packages/core/src/compiler/Domain.ts, packages/core/src/contrib/Constraints.ts, packages/core/src/contrib/ConstraintsUtils.ts, packages/core/src/contrib/Functions.ts, packages/core/src/contrib/Objectives.ts, packages/core/src/contrib/Utils.ts, packages/core/src/engine/EngineUtils.ts, packages/core/src/engine/Evaluator.ts, packages/core/src/engine/Optimizer.ts, packages/core/src/engine/PropagateUpdate.ts, packages/core/src/renderer/Image.ts, packages/core/src/synthesis/Mutation.ts, packages/core/src/synthesis/Search.ts, packages/core/src/utils/CollectLabels.ts, packages/core/src/utils/toCustomAD.ts
This PR eliminates 32% of the 215 ESLint warnings currently in `@penrose/core`. All the changes are fairly trivial; I didn't do any significant refactoring.
=> refactor: Fix some lint warnings in @penrose/core

.github/bench.sh
This PR modifies `.github/bench.sh` (originally added in #907 to diff the timings generated by the `bench` CI job for a branch with those from `main`) to use `@penrose/automator`'s [static-site-generation](https://github.com/penrose/penrose/tree/bfdbe4303cc9732e4e7a258830c2d9c5d50383ba/packages/automator#static-site-generation) to generate visual performance charts instead of just running [`icdiff`](https://www.jefftk.com/icdiff) on the raw numbers.
I realized that the previous strategy to cache the downloaded artifacts under `.github/artifacts/diagrams/$branch/` was foolish, because that makes it very easy to see incorrect diffs if one doesn't habitually delete `.github/artifacts/diagrams/`. Thus, I changed it to store them under `.github/artifacts/diagrams/$commit/` instead. However, …
=> chore: Use Automator renderer in .github/bench.sh

packages/browser-ui/package.json, packages/browser-ui/src/inspector/views/GraphUtils.ts, packages/components/package.json, packages/panels/package.json, packages/synthesizer-ui/package.json
Fixes #866. @wodeni and I made some progress toward this in #941 and #942, but #943 seems to have caused some regression, because [Vite doesn't typecheck code](https://vitejs.dev/guide/features.html#typescript):
> Vite only performs transpilation on `.ts` files and does **NOT** perform type checking. It assumes type checking is taken care of by your IDE and build process (you can run `tsc --noEmit` in the build script or install `vue-tsc` and run `vue-tsc --noEmit` to also type check your `*.vue` files).
Thus, this PR adds `tsc --noEmit` as a [`prebuild`](https://docs.npmjs.com/cli/v8/using-npm/scripts#pre--post-scripts) script before every `vite build` script (except for `@penrose/components`, which seems to do something special and for which `tsc --noEmit` fails). This exposes a couple …
=> build: Run tsc --noEmit as prebuild for vite build

penrose.code-workspace
Previously I left this setting out of our `penrose.code-workspace` file because I was guessing that different people have different preferences about this, but now I think it's more likely that some people simply didn't know this setting exists.
=> chore: Enable Format On Save in VS Code

packages/core/src/utils/Error.ts
Simple typo fix for an error message.
=> fix: typo in DeconstructNonconstructor error msg

diagrams/allShapes-dashedShapes.svg, diagrams/circle-example-euclidean.svg, diagrams/collinear-euclidean.svg, diagrams/congruent-triangles-euclidean.svg, diagrams/continuousmap-continuousmap.svg, diagrams/hypergraph-hypergraph.svg, diagrams/incenter-triangle-euclidean.svg, diagrams/lagrange-bases-lagrange-bases.svg, diagrams/midsegment-triangles-euclidean.svg, diagrams/non-convex-non-convex.svg, diagrams/parallel-lines-euclidean.svg, diagrams/persistent-homology-persistent-homology.svg, diagrams/small-graph-disjoint-rect-line-horiz.svg, diagrams/small-graph-disjoint-rects-large-canvas.svg, diagrams/small-graph-disjoint-rects-small-canvas.svg, diagrams/small-graph-disjoint-rects.svg, diagrams/tree-venn-3d.svg, diagrams/tree-venn.svg, diagrams/two-vectors-perp-vectors-dashed.svg, packages/core/src/renderer/AttrHelper.ts
Fixes issue #1024 
This year we added svg-passthrough functionality, which allows unknown properties to be passed through to the SVG output.  Around this time, we also renamed most internal Style properties to correspond with the SVG names so most properties could flow right through the renderer into the SVG.  This approach eliminated code and make life easier for the Style developer who happens to already be familiar with SVG.
The tradeoff is that we sometimes have properties that are purely internal that we do not want to "leak" into the SVG.  This is implemented as an exclusion list in AttrHelper.ts.  Issue #1024 observes leakage of two internal-only properties, `name` and `ensureOnCanvas`.  This PR adds these two properties to the exclusion list to elide them from the SVG output. …
=> fix: issue #1024 exclude name, ensureOnCavas in SVG

packages/core/src/renderer/Renderer.ts, packages/core/src/types/io.ts, packages/editor/src/App.tsx, packages/editor/src/components/DiagramPanel.tsx, packages/editor/src/components/RogerPanel.tsx, packages/editor/src/state/atoms.ts, packages/editor/src/state/callbacks.ts, packages/roger/src/commands/watch.ts
Related issue/PR: #1000
This PR adds support for Style-included images for (1) `roger` local development mode and (2) the example registry. We assume that image paths in Style are relative to the Style file parent directory, and they are all relative paths, not absolute ones. 
First, `WorkspaceLocation` now keeps necessary data for file path resolution. Then for (1), we send a `retrieve_file_from_style` packet via the websocket connection (now a part of `RogerState` managed by Recoil), and resolve the image on `file_change` response with the same token. For (2), we keep track of the directory that the Style program is in and construct the URL for the image by calling `new URL`. 
* `roger` will not perform HTTP requests and only does local file fetching
* Similarly, (2) doesn't resolve …
=> feat: resolve image paths in `@penrose/editor`

packages/core/src/compiler/Style.ts
Related issue/PR: #566 
This PR slightly improves the performance of the selector matching algorithm. The current implementation enumerates all possible substitutions for each type declaration in the selector head position, and return a Cartesian product with all previous substitutions found. For example, take the following sub/sty pair:
```
-- .sub
T t1, t2, t3, t4
-- .sty
T s1, s2 {
}
```
Current impl will produce `4^2 = 16` substitutions. However, it would include cases such as `{s1: t1, s2: t1}` because the Cartesian product doesn't produce a bijection. 
Instead, this PR adds a duplicate check in `cartesianProduct`, and now this step of selector matching will be `n choose m` time instead of `n^m`, which is [asymptotically faster](https://proofwiki.org/wiki/N_Choose_k_is_not_greater_tha …
=> fix: selector matching `n^m` complexity

packages/core/src/__tests__/overall.test.ts, packages/core/src/compiler/Domain.test.ts, packages/core/src/compiler/Style.test.ts, packages/core/src/compiler/Substance.test.ts, packages/core/src/parser/StyleParser.test.ts
This is a followup to #920. As noted in https://github.com/facebook/jest/issues/11698, Jest 27 switched the default runner to one which does not include a `fail` function, but `@types/jest` doesn't reflect this: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/55803
We didn't notice this until just now while I was working on #984, because #920 itself did not cause any of our tests to `fail`. This PR fixes the issue by replacing `fail` with `throw Error`, as suggested by https://github.com/facebook/jest/issues/11698#issuecomment-922351139.
=> test: Replace fail with throw Error

packages/editor/src/App.tsx, packages/editor/src/components/Settings.tsx, packages/editor/src/state/atoms.ts
`@penrose/editor` current displays the debug tabs on the right regardless if it's in production or development mode. This PR adds an explicit "debug mode" checkbox in the "settings" tab. This option is on by default in local dev mode and off in production. Currently, checking this box will display the debug tabs on the right:
Un-checking it hides them:
If the user drags one of the tabs out of the right tab group, unchecking the box will not hide it. Not sure if it's a bug or feature:
* Added a flag in `Settings`
* Added a `onSet` effect for hiding/showing the right border group
=> feat: add debug mode setting to `@penrose/editor`

packages/roger/package.json
In the [wiki](https://github.com/penrose/penrose/wiki/Building-and-running), we instructed users to run `yarn install-global` immediately after `yarn`. But `roger` also needs to build to the `dist` folder for the `watch` command to work. This PR adds a `preinstall-global` script to call `yarn build` first.
NOTE: this PR also changes from `npm link` to `yarn link` for `install-global`. If you experience issues with running `roger`. Please run `npm unlink` in `packages/roger` and run `yarn install-global` again.
=> build: run `build` automatically before `install-global` in `@penrose/roger`

packages/automator/index.tsx, packages/editor/src/components/DiagramPanel.tsx, packages/examples/src/set-theory-domain/venn-3d.sty
Fixes issue #1032
This PR provides support for absolute image URLs in Style programs within the IDE and Automator.  When a URL is absolute, it is fetched directly and thus bypasses the normal example/roger/local/gist handlers.
Detect and handle absolute image URLs.  Only handle relative URLs using the existing logic in the IDE and Automator.
- Local image fetching in the IDE is currently marked as TODO.  See issue #1035.  This needs to be implemented in a separate PR.
- Absolute image resolution in the IDE does not use a proxy to bypass CORS.  If the web server hosting the image does not provide headers indicating a cross-origin request is allowed (e.g., `Access-Control-Allow-Origin: *`) then the browser will not fulfill the request and the placeholder image will be displayed instead.
=> fix: Add Support for images with absolute URLs

diagrams/3d-projection-fake-3d-linear-algebra.svg, packages/examples/src/fake-3d-linear-algebra/fake3d.dsl, packages/examples/src/fake-3d-linear-algebra/fake3d.sty, packages/examples/src/fake-3d-linear-algebra/projection.sub, packages/examples/src/registry.json
DSL and STY files that can draw rudimentary pseudo-3d diagrams from linear algebra, projected onto a 2d viewing surface. In particular, we include an illustration of a projection of a 3d vector onto a 2d hyperplane in a 3d ambient space, as well as onto the hyperplane's orthogonal complement.
=> feat: Fake 3d linear algebra examples

packages/core/src/compiler/Style.test.ts, packages/core/src/compiler/Style.ts
Related issue/PR: #1068 
This PR fixes the bug listed in #1068: that symmetric predicates does not match if it appears within a nested predicate.
Previously, we only check the symmetry of the outer-most predicate. In the case of matching `Not(Bond(A, B))` against `Not(Bond(B, A))`, we only check the symmetry of `Not`, and then it compares `Bond(A, B)` and `Bond(B, A)` without ever considering symmetry. The fix essentially applies this symmetric consideration on _all_ levels of the predicate recursively.
A test case has also been added to consider this case.
```
-- dsl
type Atom
type Hydrogen <: Atom
type Oxygen <: Atom
symmetric predicate SBond( Atom a1, Atom a2 )
predicate Not(Prop)
-- sty
canvas {
width = 50
height = 40
}
forall Hydrogen h; Oxygen o
where Not(SBond(o, h)) {
myText = …
```
=> fix: symmetry in nested predicates

packages/core/src/engine/Autodiff.ts
This PR deletes the `ops.angleBetween2` function, because it is currently unused and is identical to `ops.angleFrom`.
=> refactor: Delete ops.angleBetween2

packages/core/src/contrib/Functions.ts
Similar to #1077, this PR deletes the `lineLength` function (unused and redundant with `len`), and replaces usages of `rot90` and `rot90v` with the identical `ops.rot90`.
=> refactor: Replace rot90v and delete lineLength

packages/core/src/compiler/Domain.ts, packages/core/src/compiler/Style.ts, packages/core/src/compiler/Substance.ts, packages/core/src/parser/ParserUtil.ts, packages/core/src/parser/StyleParser.test.ts
Resolves #1052.
[The `reportError` function](https://github.com/kach/nearley/blob/6e24450f2b19b5b71557adf72ccd580f4e452b09/lib/nearley.js#L382-L386) @wodeni mentioned makes use not just of the `Parser`, but also of the specific `token` that caused the error. I didn't know how to access that token from the error we `catch`, although after looking more closely at [the Nearley code](https://github.com/kach/nearley/blob/6e24450f2b19b5b71557adf72ccd580f4e452b09/lib/nearley.js#L343-L346), it seems to be available via the `token` field. Thus, to me it seemed that we would need to do some textual processing of the error message regardless, just to get the line and column number.
In any case, the `prettyParseError` function I've written here is fairly small and easy to read, and (because of the …
=> feat: Make parse errors more readable

.github/workflows/build.yml, packages/automator/README.md, packages/automator/artifacts.ts, packages/automator/index.tsx, packages/automator/types.ts
This PR adds a `textchart` mode to `@penrose/automator` which generates a simple Markdown file with performance stats, for use as a [GitHub Actions job summary](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/). It also uses [marocchino/sticky-pull-request-comment](https://github.com/marocchino/sticky-pull-request-comment) to generate a comment on the pull request containing those same stats (and also linking to the page containing that summary).
This will make it easier for people to glance at the performance characteristics of a pull request in their browser, without having to locally check out the PR and run the `.github/bench.sh` script as previously required by solutions like #972.
I added safety checks to ensure that really large numbers in the JSON …
=> ci: Put stats in a text chart on every CI run and PR

penrose.code-workspace
This PR migrates our VS Code MDX extension recommendation from [silvenon.mdx](https://marketplace.visualstudio.com/items?itemName=silvenon.mdx) to [unifiedjs.vscode-mdx](https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-mdx). From the former's README:
> _**Note**: This extension has been deprecated in favor of the [official MDX extension](https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-mdx)._
=> chore: Migrate to official VS Code MDX extension

packages/components/src/editing/languages/StyleConfig.ts
@keenancrane asked:
> Is a pop-up color picker something that could be easily integrated into the framework you're using for the IDE?
This PR adds support for `ColorProvider` in our monaco editor for Style, which displays a color icon and on-hover color picker for all `rgba` function calls.
Since we do not have a language server, this PR is implemented in the simplest way: parsing the document with a regex for valid `rgba` function calls. Currently, this feature does not support `hsva` or any other functions that return colors. In addition, the arguments to `rgba` have to be floating-point literals; inline expression are not supported yet.
Ideally, we should have a language server that supports [Color decorators](https://code.visualstudio.com/api/language-extensions/p …
=> feat: Style inline color widgets

packages/components/src/editing/EditorPane.tsx
`editor` uses the default line cursor in both normal and vim modes. Block cursor seems to be a more conventional default for vim.
=> chore: use block cursor in vim mode

turboConfig.js
This PR makes the `turboConfig.js` script added in #1081 not crash if there exists a `packages/*/` directory not containing a `package.json` file. This came up in the meeting on Friday, because I had been working on #1092, but when I switched from that branch to a different branch without `packages/optimizer/`, any `turbo` command would crash.
```sh
mkdir packages/foo/
yarn typecheck
```
=> build: Skip missing package.json in turboConfig.js

packages/editor/src/components/DiagramPanel.tsx
Resolves #1051 
This PR ensures the diagram always appears entirely in the diagram panel of `editor`. 
* Added some flexboxes and width/height settings so all elements in `DiagramPanel` can be as visible as possible.
* Rearranged these elements so errors and buttons are on the top of the div. Somehow this fixes a lot of the layout issues. CSS is dark magic.
Perhaps I overused flexboxes here? Can't really figure out a minimal solution. This one behaves okay, but it's a bit tedious to specify.
=> fix: resize behaviors of diagram panel components

packages/editor/src/components/SavedBrowser.tsx, packages/editor/src/state/callbacks.ts
When working with a trio in `editor`'s local storage, there's no good way to create a "fork" of the current workspace. For now, I added a "duplicate workspace" button to quickly fork the current workspace.  
Pretty much reused the code for `saveLocally`
Perhaps longer term it's better to have an experience similar to [mermaid](https://mermaid.live/)
=> feat: add "Duplicate Workspace" button to `editor`

packages/editor/src/components/DiagramOptions.tsx, packages/editor/src/components/DiagramPanel.tsx, packages/editor/src/state/atoms.ts
Related issue/PR: #644 
Although we want to disable dragging for end-users until there's a good technical solution to interactivity, the default interactive mode is still useful for debugging. This PR adds interactivity as an optional debug feature.
Conditionally call `RenderStatic` or `RenderInteractive` depending on the value 
* In "settings": check debug mode
* in "options": check interactive mode
* Re-compile or resample go get a draggable diagram.
=> chore: add optional diagram interactivity to `editor`

.github/workflows/build.yml
codecov deprecated `codecov.io/bash`, causing `test` to fail on `main`. Updating to the new `codecov-action@v3`.
=> ci: use `codecov-action@v3` in the `test` action

packages/core/src/compiler/Style.test.ts, packages/core/src/compiler/Style.ts, packages/core/src/types/errors.ts, packages/core/src/utils/Error.ts
Related issue/PR: #1086, #730 
#730 approximates a global ordering of shapes when `layer` statements lead to cycles. We decided to give a warning when that happens, but only in the form of `log.warn`. This PR returns the warning as Style compiler diagnostics and remove the `log.warn` message so it won't print it out during testing.
NOTE: this PR doesn't fully resolve #1086. Still needs to investigate another case of an unwanted console message.
* Simplify layering code to use `{ below, above }` thought
* `computeShapeLayering` returns an optional warning
=> chore: return instead of logging cyclic layering warning

.prettierignore
=> chore: Make Prettier ignore shapedefs.json

packages/components/src/stories/PenrosePrograms.tsx, packages/core/src/contrib/Functions.ts, packages/docs-site/docs/ref/style/functions.mdx, packages/examples/src/linear-algebra-domain/linearalgebra-paper-dashes.sty, packages/examples/src/shape-distance/box-arrow.sty
@keenancrane suggests to rename `len` to something more readable. The function takes in a line-like shape and return its length, which is distinct from `norm`. 
Without static type-checking of Style functions, the semantics of `length` is still not immediately clear to a Style writer. One could always do `norm(A.icon.start, A.icon.end)`, but I think it's still useful to keep `length` around.
=> chore: rename `len` to `length` for readability

packages/components/src/editing/languages/StyleConfig.ts, packages/core/src/compiler/Style.test.ts, packages/core/src/compiler/Style.ts, packages/core/src/index.ts, packages/core/src/parser/ParserUtil.ts, packages/core/src/parser/Style.ne, packages/core/src/types/errors.ts, packages/core/src/types/style.ts, packages/core/src/utils/Error.ts, packages/core/src/utils/Util.ts, packages/examples/src/set-theory-domain/continuousmap.sty
Related issue/PR: #1094 
The non-standard `rgba` format Style used had been a pain to work with. This PR adds native support for hexadecimal color literals as specified in [web standards](https://developer.mozilla.org/en-US/docs/Web/CSS/hex-color), i.e.:
```
#RGB        // The three-value syntax
#RGBA       // The four-value syntax
#RRGGBB     // The six-value syntax
#RRGGBBAA   // The eight-value syntax
```
Both upper- and lower-case hex digits are supported.
Style writers can use standard hex colors with highlighting and color picker support in the IDE. 
* `RGBA` is the ground-truth storage format in the Style compiler, and `#rrggbbaa` is the output format used by the color picker.
* Add tests to validate values of hex literals
* Updated `continousmap.sty` to use hex literals
* Side …
=> feat: hexadecimal color literals in Style

.gitattributes
This PR deletes the `.gitattributes` file. Two of its lines (added in 207f8e636338f8127c2e551a820ea3b2a014bf10 and updated in d41d3907bd89a5c0fda570664bf875a688e9e5e5) refer to files from Haskell Penrose that no longer exist. The other line was added in #864 to try to cut down on diff noise for PRs that touch `diagrams/`, as per [this GitHub Docs page](https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github). It doesn't seem to have any effect for `*.svg` files though, so this whole file seems to currently be effectively useless.
=> chore: Delete .gitattributes

packages/components/src/Demo.tsx, packages/components/src/Listing.tsx, packages/docs-site/src/pages/index.js, packages/examples/src/lagrange-bases/example.sub
This PR replaces our current demo set of diagrams (just venn diagram with three different seeds) with four nice diagrams chosen from our registry.
One of those is the `lagrange-bases` example, from which this PR also removes a couple lines that were previously commented out, for nicer presentation.
=> docs: Diversify our homepage demo

packages/examples/src/structural-formula/pseudo-3d-reaction.sty
@keenancrane added a Style program for reactions in #734. Because it uses `Text`, we don't currently include it in the registry, so we did not catch that it broke when we merged #984. This PR fixes the issue, which was caused by reusing the variable name `c` in one of the Style blocks.
- `structural-formula/reactions/methane-combustion.sub`
- `structural-formula/pseudo-3d-reaction.sty`
- `src/structural-formula/structural-formula.dsl`
=> fix: Reaction example Style

packages/core/src/compiler/Style.test.ts, packages/core/src/compiler/Style.ts
Resolves #1126
Some symmetric predicates do not match. For example,
```
forall Set x, y, z
where Equal(x, y); Equal(y, z) {
Text {
string: "Hello"
}
}
```
should match against
```
Set A, B, C
Equal(B, A)
Equal(B, C)
```
where `Equal` is symmetric. Using mapping `x --> A, y --> B, z --> C`, the `where`-clause becomes `Equal(A, B)` and `Equal(B, C)`. `Equal(A, B)` should match against `Equal(B, A)` due to symmetry, and `Equal(B, C)` also successfully matches. But, this matching is not admitted.
The reason is that when we first consider `Equal(x, y)`, we will only consider the version that is present in the Substance program. If that does not exist, then we will consider the alternative, symmetric version. But sometimes we actively seek for the symmetric version that is _not_ present in the …
=> fix: some symmetric predicates don't match

packages/editor/src/components/DiagramPanel.tsx
Fixes: #1135 
By default, `<svg>` has `auto` width and height, which is supposed to [be treated at 100%](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/width#svg), but somehow the mobile browsers don't seem to respect that. This PR manually set them to `100%`.
=> fix: canvas disappears on mobile browsers

packages/synthesizer-ui/src/components/Content.tsx
This PR allow `synthesizer-ui` to export both the Substance files and mutation record upon "Export All."
The implementation basically uses existing data stored in the state and serialize them using standard pretty-print functions.
=> chore: allow user to export mutation metadata in `synthesizer-ui`

packages/core/src/compiler/Style.ts, packages/core/src/contrib/Functions.ts, packages/core/src/contrib/SDF.test.ts, packages/core/src/engine/Optimizer.ts, packages/core/src/index.ts, packages/core/src/renderer/Renderer.ts, packages/core/src/renderer/dragUtils.ts, packages/core/src/shapes/Equation.ts, packages/core/src/shapes/Samplers.ts, packages/core/src/shapes/Text.ts, packages/core/src/types/state.ts, packages/core/src/utils/Util.ts
Related issue/PR: #644, #1115 
The current dragging behavior is counter-intuitive. After a user drags a shape in interactive mode, the optimizer steps all variable in the state, including the one the user interacted with. If a user drags a shape from point A to B, the shape might end up in point C. This PR allows the system to programmatically specify "frozen" variable during optimization, which gives zero gradient and therefore stays during optimization.
This feature was initially developed in #1115. Since it's an experimental PR, I'm separating this feature out, which is stable and ready to be merged.
Note: this mode of optimization requires the frozen variables to be in the feasible region. In the context of dragging, if the user drags a shape off screen and the system freezes the `x, …
=> feat: "follow the cursor" dragging mode

packages/core/src/renderer/Equation.ts
Closes: #535 
Currently, we cache the rendered SVG node in `LabelCache` and `appendChild` in `renderer/Equation.ts`. However, `appendChild` doesn't clone the node and therefore remove the existing node from the DOM tree, causing the labels to disappear.
`cloneDeep` the SVG node after retrieving it from the label cache.
=> fix: clone rendered SVG node for `Equation` at render-time 

.github/workflows/edgeworth.yml, packages/synthesizer-ui/src/App.tsx, packages/synthesizer-ui/vite.config.ts
For running experiments and standardize deployment, this PR adds a workflow for Edgeworth (`synthesizer-ui`) to deploy each commit in `edgeworth/*` branches to `gh-pages`. Edgeworth is not yet ready for public use yet, so I'm only deploying to GH Pages as nightly releases.
* Added a separate workflow configuration.
* Fixed some vite issues with `synthesizer-ui`: relative base path, unnecessary react config
=> ci: build and deploy edgeworth on feature branches

packages/core/src/contrib/Minkowski.ts, packages/core/src/contrib/Utils.ts
Related issue/PR: #907 
Aside from the main optimizer, other parts of the system sometimes need to get the numerical values of autodiff nodes. Notably, `convexPartitions` needs to evaluate points in a polygon before the optimizer runs. Similarly, any computation in `Function.ts` that needs JS `number` from `ad.Num` will need to run such evaluation. Currently, we go through these steps to achieve this:
1. Construct a `secondaryGraph` with `inputs` that are sources of the output nodes of interest
2. Run `genCode` on the graph, and evaluate the generated code with the input values.  
This PR modifies `numsOf` and `numOf` in `contrib/Util.ts` to perform 1 so we can just call `numsOf(xs)` or `numOf(x)` without doing the steps manually.
=> refactor: `numsOf` for evaluating autodiff numbers

packages/core/src/engine/Autodiff.test.ts, packages/core/src/engine/Autodiff.ts
Previously, in `makeGraph`, we would first add all the nodes reachable from the primary output, then make gradient nodes for each of those, then add all the nodes reachable from the secondary output, and finally make a gradient output array from all the inputs we've seen so far. This means that, for nodes reachable from the secondary outputs but not the primary output, we would still make entries in the `gradient` array, for no reason. Those entries are redundant with the check in our `objectiveAndGradient` wrapper function created by `genOptProblem`:
https://github.com/penrose/penrose/blob/94da0ffdce15a93bbd87379f08aafe4587c78625/packages/core/src/engine/Optimizer.ts#L824-L827
Thus, this PR rearranges the end of `makeGraph` to create the `gradient` array before processing the `secondary` …
=> refactor: Only make gradient nodes from primary output

packages/core/src/compiler/Style.test.ts, packages/core/src/compiler/Style.ts, packages/core/src/types/errors.ts, packages/core/src/types/styleSemantics.ts, packages/core/src/utils/Error.ts
Related issue/PR: #760 
Style doesn't allow the user to assign values cyclically. For instance, `a = a + 1` is not a valid Style expression. Currently, the system fails silently whenever that happens. This PR adds an explicit check and report such errors in a human-readable way.
* Accumulate source location when building up the dependency graph in the first compilation pass
* Retrieve the source location and pretty-print them in error reporting
TODO
Generally the Style compiler doesn't keep source locations around for long. Is there a more principled way to keep track of them?
=> feat: detect and report cyclic assignments in Style

packages/core/src/contrib/Objectives.ts, packages/examples/src/fake-3d-linear-algebra/fake3d.sty, packages/examples/src/geometry-domain/euclidean-teaser.sty, packages/examples/src/geometry-domain/euclidean.sty, packages/examples/src/graph-domain/graph-theory-simple.sty, packages/examples/src/graph-domain/graph-theory.sty, packages/examples/src/mesh-set-domain/DomainInterop.sty, packages/examples/src/molecules/molecules-basic.sty, packages/examples/src/molecules/molecules-elegant.sty, packages/examples/src/molecules/molecules.sty, packages/examples/src/set-theory-domain/tree.sty
Closes #300 
* Used "Find in files" in VSCode to replace all instances.
=> chore: rename `repel` to `notTooClose` #300 

.github/workflows/build.yml
CI has been failing today because of the `grep -L` we use to ensure the CI stats summary doesn't contain the substring `EOF`. I guess GitHub Actions upgraded their `grep` version and now `grep -L` doesn't work? In any case, I'm just removing this check for now.
=> ci: Don't grep for EOF in summary

CONTRIBUTING.md
This PR makes a documentation change I forgot to make in #1142.
=> docs: Fix formatting of expected yarn start output

packages/automator/index.tsx, packages/automator/package.json, packages/automator/tsconfig.json, yarn.lock
Resolves #1082 
Now that #1160 bumped `ts-node` to 10+, this PR uses [the swc transpiler](https://typestrong.org/ts-node/docs/swc/) for `autormator`, which is significantly faster than the previous config.
Testing on my 2021 M1 mbp, the startup time went from 10+ seconds to 2~4 seconds.
* add necessary dependencies according to the [docs](https://typestrong.org/ts-node/docs/swc/)
* tested swc with both with and without `transpileOnly`, no obvious difference
Run `yarn start batch registry.json ../../diagrams/ --src-prefix=../examples/src` and notice a faster startup time.
=> perf: speed up `automator` using SWC

cloudflare.sh
This PR creates a `cloudflare.sh` script, with the intention that we set our Cloudflare Pages build command to `./cloudflare.sh`, so that, for instance, we can add extra things to this in pull requests (such as #1092, which needs to install Rust) without modifying the `yarn build:docs-site` script itself.
=> build: Create a dedicated cloudflare.sh script

CONTRIBUTING.md
Currently `CONTRIBUTING.md` includes instructions to delete build artifacts, but if you do that, Nx will just restore them from cache. This PR adds instructions to delete the Nx cache.
=> docs: Add instructions to delete Nx cache

penrose.code-workspace
I don't think it provides value, as of #732. Obviously this only removes it from our workspace's recommendations, and doesn't actually delete it from anyone's local setup; people are free to keep it installed if they wish.
=> chore: Remove VS Code Monorepo Workspace extension

packages/editor/package.json, yarn.lock
This PR removes the unused [Cytoscape](https://www.npmjs.com/package/cytoscape) from `editor`'s dependencies. It was added in #1000 for `packages/editor/src/components/CompGraph.tsx`, which was deleted in #984.
=> build(deps): remove Cytoscape dependency

.prettierignore
#939 added `out/` to `packages/automator/.gitignore` but forgot to add it to `.prettierignore`. This PR does the latter so that running `yarn format` after something like the following doesn't try to format all the `packages/automator/out/*/meta.json` files:
```sh
yarn start batch registry.json out/ --src-prefix=../examples/src/ --folders
```
=> chore: add automator's `out/` to `.prettierignore`

packages/core/package.json
#1092 added a new package, `@penrose/optimizer`, to the `dependencies` of `@penrose/core`. However, we avoid publishing it via `"private": true`, so currently people can't use `@penrose/core` from npm because `@penrose/optimizer` is missing. This PR attempts to fix that problem by changing `@penrose/optimizer` to be a dev dependency instead, since we currently just bundle it using esbuild. See also #1173.
=> build: move `optimizer` into `devDependencies`

CONTRIBUTING.md, nx.json, packages/components/package.json, packages/core/package.json, packages/docs-site/package.json, packages/editor/package.json, packages/examples/package.json, packages/optimizer/package.json, packages/roger/package.json, packages/synthesizer-ui/package.json
This PR removes the monorepo build artifact caching added by #1081 and #1142, also removing the need for #1175. In practice, my observation has been that most of our tasks are either very fast (e.g. esbuild) or already cache automatically (e.g. Cargo), and that for the ones that aren't super fast (e.g. Vite build in components or editor), Nx usually doesn't cache those anyway because their dependencies changed. Furthermore, it requires a lot of configuration to correctly identify cache hits; so far we've only been specifying the outputs of each task and not the inputs, so Nx usually reruns tasks unnecessarily because it sees changes in the output artifacts of downstream tasks and conservatively assumes that those might affect things. On the flipside, I've also often found myself running …
=> build: don't use Nx cache

packages/docs-site/index.md
After #1172 was merged, @keenancrane noticed that one of our homepage "try" links was still giving a 404 error. This PR fixes that.
=> fix: avoid 404 in homepage try link

packages/core/src/compiler/Domain.ts, packages/core/src/compiler/Style.ts, packages/core/src/types/domain.ts
This PR rewrites all our remaining usages of [`graphlib`](https://github.com/dagrejs/graphlib/wiki/API-Reference) to instead use the better-typed wrappers we added in #984. Now our only `graphlib` import is inside `packages/core/src/utils/Graph.ts`.
=> refactor: consistently use our graph wrappers

packages/core/src/__tests__/overall.test.ts, packages/core/src/compiler/Style.ts, packages/core/src/engine/Autodiff.test.ts, packages/core/src/engine/Autodiff.ts, packages/core/src/index.ts, packages/core/src/renderer/dragUtils.ts, packages/core/src/utils/Wasm.ts, packages/optimizer/source.ts, packages/optimizer/src/lib.rs
Prerequisite for #1115. This PR replaces our current heterogeneous system of `frozenValues`, `inputKinds`, `numObjEngs`, and `numConstrEngs` with a more homogeneous system of three masks: `gradMask`, `objMask`, and `constrMask`, each of which is a `boolean[]`. The codegen is also modified to generate an extra parameter as a mask for its addend subgraphs.
=> feat: allow autodiff addends to be masked

packages/docs-site/.vitepress/config.ts
Currently if you refresh the page on the website, it adds a trailing slash to the URL and breaks subsequent routing. This PR fixes that by switching our [VitePress `cleanUrls` setting](https://vitepress.vuejs.org/config/app-configs#cleanurls-experimental) to [the one VitePress uses for its own website](https://github.com/vuejs/vitepress/blob/v1.0.0-alpha.33/docs/.vitepress/config.ts#L10).
=> fix: make website routing work

packages/components/src/Demo.tsx, packages/docs-site/.vitepress/theme/index.ts, packages/docs-site/index.md, packages/docs-site/package.json, packages/docs-site/src/components/DemoWrapper.vue, packages/docs-site/src/components/Layout.vue, yarn.lock
Following up on #1172, this PR replaces the big logo on our homepage with a live demo component like we had before.
- The specific diagrams we use here could be improved. Most of them have too-small text and don't look great in dark mode. We can make them more presentable for the homepage in a followup.
=> feat: put the demo in the VitePress site

packages/optimizer/source.ts
#1188 deleted `ready` from `@penrose/optimizer`; this PR deletes lingering references to it from a couple docstrings.
=> docs: remove references to `ready` in docstrings

CONTRIBUTING.md
Installing on Ubuntu breaks on the `wasm-bindgen` step. Fixed by following to [this comment](https://github.com/sfackler/rust-openssl/issues/649#issuecomment-308605644).
=> docs: update prerequisites for Ubuntu

penrose.code-workspace
This PR removes VS Code Prettier config for a bunch of languages that we don't use.
=> chore: clean up Prettier VS Code settings

packages/optimizer/.gitignore, packages/optimizer/README.md, packages/optimizer/package.json, packages/optimizer/tsconfig.json, yarn.lock
Depends on #1221. Prerequisite to #1173. This PR sets some metadata in `@penrose/optimizer` and cleans it up for packaging, preparing for us to publish it to npm.
=> build: prepare `@penrose/optimizer` for publishing

packages/components/.storybook/preview-head.html
@wodeni is adding this in #1225, but we actually need it even before that PR is merged; for instance, it's a prerequisite for #1227.
=> fix: `ReferenceError` in storybook

.github/workflows/build.yml
As mentioned in #1092:
> As you can verify by running `strings packages/optimizer/target/wasm32-unknown-unknown/release/penrose_optimizer.wasm`, the built WebAssembly binary contains absolute paths (starting with `/Users/samueles/.cargo/registry/src/github.com-1ecc6299db9ec823/` in my case) to local files on whatever machine built the binary. See this Rust issue: rust-lang/rust#40552
This PR will allow us to publish `@penrose/optimizer` to npm without paths from our local machines, by downloading this new artifact and then rebundling via esbuild.
=> ci: upload optimizer Wasm artifact

packages/core/src/renderer/dragUtils.ts
Related issue/PR: #1199 
In #1199, we changed `optStages` from a list to `Map` last minute and the type checker didn't catch the wrong usage in `dragUtils.ts`. This PR uses `get` instead of `[]` for stage reset.
=> fix: Stage reset after dragging

packages/core/src/compiler/Style.test.ts, packages/core/src/compiler/Style.ts, packages/core/src/utils/Error.ts
Related issue/PR: #1123
This PR fixes the uncaught error in the Style compiler when selector relations refer to a variable not declared in the selector, but exists in the substance program. It now throws an error. We added a test case on this error. Finally, we improved upon how the "suggested" variables in the error message distinguish between Style and Substance variables.
The style compiler checks through the relations in the `where` clause, primarily using functions within the Substance checker, which checks the consistency of expressions with respect to a `SubstanceEnv`. In particular, it checks that each variable referred in the expressions are declared inside `SubstanceEnv`.
In order to call the Substance checker, we would need to provide a `SubstanceEnv` that contains all the …
=> fix: style relation checker using substance variables

packages/components/package.json, packages/core/package.json
Version 2.0.0 of [`@penrose/core`](https://www.npmjs.com/package/@penrose/core) and [`@penrose/components`](https://www.npmjs.com/package/@penrose/components) are missing a lot of files, specifically everything under `dist/` that isn't a direct child of `dist/`, because I tested them using `yarn pack` instead of `npm pack`, and the two commands handle globs differently. This PR fixes the issue.
=> build: fix `npm pack`

.github/workflows/release.yml
This PR adds a GitHub Actions workflow to automatically publish to npm when we create a new GitHub release, following [these docs](https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry).
=> ci: add a workflow to automatically publish to npm

packages/editor/vite.config.ts, packages/synthesizer-ui/vite.config.ts
In our [docs](https://github.com/penrose/penrose/blob/main/CONTRIBUTING.md), the default port for `editor` for local development is `3000`, but Vite updated it to another port. This PR explicitly set the ports for `editor` and `synthesizer-ui` (to avoid collision).
An explicitly specified port also allow all Penrose devs to log in through GitHub when developing locally.
=> chore: change server ports for `editor` and `synthesizer-ui`

CHANGELOG.md, lerna.json, packages/automator/CHANGELOG.md, packages/automator/package.json, packages/components/CHANGELOG.md, packages/components/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/docs-site/CHANGELOG.md, packages/docs-site/package.json, packages/editor/CHANGELOG.md, packages/editor/package.json, packages/examples/CHANGELOG.md, packages/examples/package.json, packages/optimizer/CHANGELOG.md, packages/optimizer/Cargo.lock, packages/optimizer/Cargo.toml, packages/optimizer/package.json, packages/roger/CHANGELOG.md, packages/roger/README.md, packages/roger/package.json, packages/synthesizer-ui/CHANGELOG.md, packages/synthesizer-ui/package.json, packages/synthesizer/CHANGELOG.md, packages/synthesizer/package.json
We need to release a new version because of #1241. This PR was generated by running the following commands:
```sh
yarn new-version 2.1.0
yarn format
```
I also manually modified `packages/optimizer/Cargo.toml`, and then VS Code automatically generated the change to `packages/optimizer/Cargo.lock`.
=> chore: bump version to 2.1.0

packages/synthesizer/package.json
The v2.1.0 autorelease script worked, but it gave an error at the end: https://github.com/penrose/penrose/actions/runs/3955406466/jobs/6773664245
```
npm notice name:          @penrose/synthesizer                    
npm notice version:       2.1.0                                   
npm notice filename:      @penrose/synthesizer-2.1.0.tgz          
npm notice package size:  3.4 kB                                  
npm notice unpacked size: 10.4 kB                                 
npm notice shasum:        7743e6c6cbc4207f30380241838c6713bc7275a2
npm notice integrity:     sha512-jJzksFjHDEyOP[...]+6ZunKCgBjy1A==
npm notice total files:   3                                       
npm notice 
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to …
```
=> build: don't set Yarn registry for synthesizer

packages/core/package.json, packages/synthesizer/package.json
Currently, trying to use `@penrose/core` v2.1.0 can result in errors because we use [pandemonium](https://www.npmjs.com/package/pandemonium) in `packages/core/src/synthesis/Synthesizer.ts` but don't list it as a dependency of `core`. This PR fixes the issue by moving pandemonium from `@penrose/synthesizer`'s `dependencies` to `@penrose/core`'s `dependencies`.
=> fix: make pandemonium a dependency of core

packages/core/README.md
Now that `core` is modules-only and bundle-less, the user can't just import `core` through CDNs such as unpkg because it's difficult to resolve dependencies. The unpkg `?module` suffix doesn't seem to work in our case. Therefore, this PR updates the README to include an example that uses JSPM, a service that resolves ES modules properly and generates import maps.
=> docs: update `core` usage in README

CHANGELOG.md, lerna.json, packages/automator/CHANGELOG.md, packages/automator/package.json, packages/components/CHANGELOG.md, packages/components/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/docs-site/CHANGELOG.md, packages/docs-site/package.json, packages/editor/CHANGELOG.md, packages/editor/package.json, packages/examples/CHANGELOG.md, packages/examples/package.json, packages/optimizer/CHANGELOG.md, packages/optimizer/Cargo.lock, packages/optimizer/Cargo.toml, packages/optimizer/package.json, packages/roger/CHANGELOG.md, packages/roger/README.md, packages/roger/package.json, packages/synthesizer-ui/CHANGELOG.md, packages/synthesizer-ui/package.json, packages/synthesizer/CHANGELOG.md, packages/synthesizer/package.json
We need to release a new version because of #1249 and #1250. Diff generated using analogous commands to #1244, plus again modifications to `packages/optimizer/Cargo.{toml,lock}`:
```sh
yarn new-version 2.1.1
yarn format
```
=> chore: bump version to 2.1.1

packages/components/README.md
The example `import` in the `@penrose/components` README is broken. This PR fixes it.
=> docs: fix `import` typo in components README

packages/examples/src/registry.json
Temporary removes the full-moon trio as a workaround for issue #1258.
=> chore: remove full moon trio

packages/core/src/contrib/Constraints.ts, packages/core/src/contrib/__tests__/Constraints.test.ts, packages/examples/src/atoms-and-bonds/atoms-and-bonds.sty
Resolves #1262.
Somehow the implementation changed to `minN` of all triangle inequalities instead of just one. This PR reverts that change since `collinear` already has an implementation based on cross product.
The `wet-floor` example has been changed to use `collinearOrdered` since that's what we intended.
=> fix: enforcing ordering in `collinearOrdered` constraint

packages/docs-site/docs/ref.md
This PR adds a link to the GitHub wiki as a stopgap solution to the fact that the doc site is missing a lot of critical information needed to get end users up and running.  It literally adds a single sentence to the docs on the docs landing page, making readers aware that the GitHub wiki exists.
=> feat: Add link to Wiki

.github/workflows/release.yml, CHANGELOG.md, lerna.json, packages/automator/CHANGELOG.md, packages/automator/package.json, packages/components/CHANGELOG.md, packages/components/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/docs-site/CHANGELOG.md, packages/docs-site/package.json, packages/editor/CHANGELOG.md, packages/editor/package.json, packages/examples/CHANGELOG.md, packages/examples/package.json, packages/optimizer/CHANGELOG.md, packages/optimizer/Cargo.lock, packages/optimizer/Cargo.toml, packages/optimizer/package.json, packages/roger/CHANGELOG.md, packages/roger/README.md, packages/roger/package.json, packages/synthesizer-ui/CHANGELOG.md, packages/synthesizer-ui/package.json, packages/synthesizer/CHANGELOG.md, packages/synthesizer/package.json, packages/vscode/CHANGELOG.md, packages/vscode/package.json
We need to release a new version because of #1253, #1280, and #1271. Diff generated using analogous commands to #1252, plus again modifications to `packages/optimizer/Cargo.{toml,lock}`:
```sh
yarn new-version 2.2.0
yarn format
```
In this case I also made a manual change to `.github/workflows/release.yml` because I realized it had an error.
=> chore: bump version to 2.2.0

.github/workflows/release.yml
Fix attempt for #1292 using https://github.com/microsoft/vscode-vsce/issues/300#issuecomment-978256849 (which worked for me to manually publish v2.2.0).
=> build: fix VS Code extension publishing

packages/examples/src/registry.json, packages/examples/src/triangle-mesh-3d/README.md, packages/examples/src/triangle-mesh-3d/triangle-mesh-3d.domain, packages/examples/src/triangle-mesh-3d/triangle-mesh-3d.style, packages/examples/src/triangle-mesh-3d/two-triangles.substance
This example is basically a "what if..." experiment, as in, "what if we had 3D types in Penrose?"  It draws a diagram that is relatively simple from the 3D perspective, but which has some neat consequences in terms of the ability to declare constraints/objectives that optimize the 3D geometry so that its projection yields a legible 2D diagram.  See the README for more info.
This example has been added to the registry and gallery.  Here are a few random samples (not cherry picked):
=> feat: experimental example emulating 3D diagramming

packages/examples/src/triangle-mesh-3d/README.md, packages/examples/src/triangle-mesh-3d/triangle-mesh-3d.style, packages/examples/src/triangle-mesh-3d/two-triangles.substance
Simplifies example to make use of `vec3` type, and updates README accordingly.  Also adds labels to vertices, and disables shadow constraint (that makes optimization tougher for no clear visual gain).
=> feat: triangle-mesh-3d example improvements

packages/core/src/contrib/Constraints.ts, packages/core/src/contrib/__tests__/Constraints.test.ts, packages/examples/src/geometry-domain/euclidean.style, packages/examples/src/registry.json
Resolves #860. Resolves #1296 
The current `inRange` implementation is wrong. This PR fixes it.
Turn the multiplication into sum of differences guarded by `ifCond`s.
=> fix: `inRange` implemented incorrectly

CONTRIBUTING.md
This PR adds a guide to creating new releases, mostly following and expanding the description in #1290.
=> docs: guide for creating new releases

.github/workflows/build.yml
Resolves #1266 via [an output parameter](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter).
=> ci: link to specific commit for registry diff

.prettierignore
We removed `build/` from `.prettierignore` in #1173, and remembered to add `/packages/docs-site/build/`, but forgot to add `/packages/optimizer/build/`.
=> chore: add optimizer `build/` to `.prettierignore`

packages/components/src/editing/EditorPane.tsx
Resolves #1272 
"ctrl+enter" now functions identically to `:w` in VimMode.
=> feat: added "ctrl+enter" binding for recompiling

.github/actions/setup/action.yml, .github/workflows/release.yml
GitHub action updated to, by default, use Node 18, which breaks some dependencies. See [here](https://github.com/actions/runner-images/issues/7002).
For now, we are forcing GitHub action to use Node 16.
=> fix: github action node version

packages/automator/index.tsx, packages/components/src/Demo.tsx, packages/components/src/Embed.tsx, packages/components/src/Grid.tsx, packages/components/src/Gridbox.tsx, packages/components/src/Simple.tsx, packages/core/package.json, packages/core/src/__tests__/overall.test.ts, packages/core/src/index.ts, packages/core/src/renderer/Line.ts, packages/core/src/renderer/Renderer.ts, packages/editor/src/components/DiagramPanel.tsx, packages/synthesizer-ui/src/components/Content.tsx
Resolves #1312.
* In `Line.ts`, stop using `uuid.v4` for unique ID generation
* Instead, `Render*` functions take in `name`, a client-provided id for the diagram instance to be rendered. And names in the SVG are disambiguated from others instances by a unique instance id. 
* Similarly, `Simple` and `GridBox` take in `name` too.
* Remove `uuid` from `core`'s dependencies
* Note that this PR doesn't solve #1307
=> fix: nondeterminism in renderer

packages/components/src/Simple.tsx
Because the render doesn't set SVG width and height, `<Simple>` will overflow if the diagram height exceed 90% of the diagram width. 
This PR sets the SVG width and height after rendering, thereby scaling the SVG to the parent `<div>`.
=> fix: SVG overflow in `Simple` component

packages/core/src/renderer/Renderer.ts
Resolves #1312  
Following up on #1316 
Instead of `Promise.all`, sequentially `await` for each shape to render in `RenderStatic`.
=> fix: render shapes in order for determinism

packages/docs-site/docs/team.md
This PR updates https://penrose.cs.cmu.edu/docs/team in the following ways:
- update @liangyiliang's title to "Research engineer @ CMU"
- move @cmumatt from "Current" to "Past" members
- rearrange current members list in rough order of current involvement (modulo professorship)
- use a proper emdash in the opening paragraph
- is @hsharriman still a current member? :eyes:
=> docs: update Team page

.github/actions/setup/action.yml, .github/workflows/build.yml, .github/workflows/edgeworth.yml
Currently our CI runs get [a lot of warnings](https://github.com/penrose/penrose/actions/runs/4287377814). Some of those warnings say the following:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/cache@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
This PR fixes most of our CI warnings, by upgrading our [`actions/checkout`](https://github.com/actions/checkout), [`actions/cache`](https://github.com/actions/cache), and [`actions/upload-artifact`](https://github.com/actions/upload-artifact) usages from v2 to v3.
The only remaining warnings are these two from the `registry` job:
> Node.js 12 actions are deprecated. Please …
=> ci: upgrade Node.js 12 actions

.github/PULL_REQUEST_TEMPLATE.md
Sometimes ESLint warnings are necessary, as in #1211.
=> chore: remove ESLint from PR template checklist

packages/docs-site/.vitepress/config.ts, packages/docs-site/docs/ref/domain/usage.md, packages/docs-site/docs/ref/style/shapes-overview.md, packages/docs-site/docs/ref/style/shapes/equation.md, packages/docs-site/docs/ref/style/shapes/group.md, packages/docs-site/docs/ref/style/shapes/path.md, packages/docs-site/docs/ref/style/shapes/text.md, packages/docs-site/docs/ref/style/syntax.md, packages/docs-site/docs/ref/style/usage.md, packages/docs-site/docs/ref/substance/usage.md
Resolves #1314.
Moves applicable parts of the wiki documentations to the docs-site, including:
* `override` and `delete`
* strings
* matrix / vector
* type annotations
* some details of shapes
* colors
* computation functions
* labeling
Renamed `syntax and semantics` to `usage` with appropriate ordering.
Each page's outline is now a deep-outline, meaning that each sections and subsections will be shown in the outline. This makes navigation easier.
=> docs: move wiki

packages/core/src/contrib/Objectives.ts, packages/core/src/engine/Autodiff.ts, packages/docs-site/docs/ref/constraints.md, packages/examples/src/registry.json, packages/optimizer/src/builtins.rs
Prior to this PR, `inverse` (both its implementation and its derivative) added `EPS_DENOM = 10e-6` before taking the reciprocal. It seems bad to have this sort of arbitrary tweak in the implementation of a basic autodiff primitive, so this PR removes that and also simplifies several of our other derivative definitions.
A couple of our test cases initially broke, so I fixed them by manually adding `EPS_DENOM` to the implementations of our `repelPt` and `repelScalar` objectives.
I also had to change the variation for `circle-example-euclidean`, because that particular example is pretty unreliable. I tried resampling that example a few times on `main` and I got similarly bad results for many variations, so the issue wasn't introduced by this PR.
- How can we remove the usage of `EPS_DENOM` …
=> fix: avoid `EPS_DENOM` in core autodiff

CHANGELOG.md, lerna.json, packages/automator/CHANGELOG.md, packages/automator/package.json, packages/components/CHANGELOG.md, packages/components/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/docs-site/CHANGELOG.md, packages/docs-site/package.json, packages/editor/CHANGELOG.md, packages/editor/package.json, packages/examples/CHANGELOG.md, packages/examples/package.json, packages/optimizer/CHANGELOG.md, packages/optimizer/Cargo.lock, packages/optimizer/Cargo.toml, packages/optimizer/package.json, packages/roger/CHANGELOG.md, packages/roger/README.md, packages/roger/package.json, packages/synthesizer-ui/CHANGELOG.md, packages/synthesizer-ui/package.json, packages/synthesizer/CHANGELOG.md, packages/synthesizer/package.json, packages/vscode/CHANGELOG.md, packages/vscode/package.json
Diff generated using analogous commands to #1290, plus again modifications to `packages/optimizer/Cargo.{toml,lock}`:
```sh
yarn new-version 2.3.0
yarn format
```
Also, for some reason, when I ran those commands, it deleted the contents of the "Commands" section in `packages/roger/README.md`, so I added that back manually. @wodeni, any idea why that might be happening?
=> chore: bump version to 2.3.0

packages/core/src/renderer/Line.ts
On Chrome, the `arrowheads-arrowheads` example breaks and shows this:
where every arrow head is the same.
The issue is that while rendering a `Line` shape's arrowheads, we refer to the actual arrowhead `marker` SVG using an ID. Previously, the IDs are constructed as follows:
```
const unique = `${namespace}-${variation}`;
const startArrowId = unique + "-startArrowId";
const endArrowId = unique + "-endArrowId";
```
It appears that `unique` only depends on `namespace` and `variation` and nothing else. If there are multiple lines on the screen, they may be rendered with the same arrowheads. This is not desirable.
The fix essentially adds the shape name (guaranteed to be unique) to `unique`:
```
const unique = `${namespace}-${variation}-${
(shape.properties.name as StrV).contents
}`;
const …
```
=> fix: unique line arrow

packages/synthesizer-ui/src/examples.ts
This PR changes all our Edgeworth `weights` and `opWeights` to sum to 100%. Also, since our `weights` were already almost the same across all domains, I changed them so now they are actually the same across all domains (so that we can say as much in the paper). Then for everything that was previously weighted `0.01`, I just set it to actually zero.
=> chore: sum Edgeworth weights to 100%

packages/examples/src/geometry-domain/euclidean.style, packages/examples/src/geometry-domain/textbook_problems/c04p12.substance, packages/examples/src/geometry-domain/textbook_problems/c07p06.substance, packages/examples/src/geometry-domain/textbook_problems/c11p25.substance, packages/examples/src/geometry-domain/textbook_problems/c12p20.substance, packages/examples/src/registry.json
This PR fixes two minor issues with geometry examples in `synthesizer-ui`:
* The diagrams are not very legible with the current canvas size of `(800, 700)`. Adjusted to `(500, 500)`
* Three examples (c07p06, c11p25, c12p20) errored out because of the new `notTooClose` on all labels. They failed because some shapes are auto-labeled but don't have `.text` shapes assigned. 
* Also removed `Plane` in `c04p12` because it's not meaningful.
=> fix: broken Edgeworth geometry examples

packages/core/src/contrib/Functions.ts
Resolves #1350.
This PR uses the actual shape types in the function signature of the library function `triangle`. Previously, each parameter is a `ShapeTuple` which was removed as a result of the consolidation shape types. For some reasons, this got left in.
=> fix: corrected `triangle` function signature

packages/optimizer/src/lib.rs
We use [L-BFGS](https://en.wikipedia.org/wiki/Limited-memory_BFGS) instead of [BFGS](https://en.wikipedia.org/wiki/Broyden%E2%80%93Fletcher%E2%80%93Goldfarb%E2%80%93Shanno_algorithm), so we shouldn't be materializing any $n \times n$ matrices in the optimizer. Previously we were doing so in one place, due to a naive interpretation of a diagonal matrix in the algorithm. This PR gets rid of the diagonal matrix by inlining its one usage. I also added a comment clarifying the source for some of the other reference comments.
=> perf: don't materialize any Hessian estimate

packages/editor/src/components/DiagramPanel.tsx
Resolves #1356.
Now the error pane looks like this:
=> feat: line wrap in error pane

CONTRIBUTING.md
[`wasm-bindgen` v0.2.85](https://github.com/rustwasm/wasm-bindgen/releases/tag/0.2.85) just released, so to follow up on the little doc change in #1338, this PR modifies the instructions in our `CONTRIBUTING.md` to give an exact command to specify our particular version of `wasm-bindgen-cli`.
=> docs: give exact `wasm-bindgen` version command

.github/workflows/delete-branches.yml
This PR adds a daily cron job using https://github.com/dawidd6/action-delete-branch to automatically delete the `ci/refs/pull/*/merge` branches created by #988, now that the autogenerated PR comment links to commits instead of branches as of #1313.
=> ci: delete CI-generated branches

.github/workflows/delete-branches.yml
Followup to #1375. See these doc pages:
- https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
=> ci: allow manual triggering of branch deletion

packages/core/package.json, yarn.lock
After #1371, `jscodeshift` is not needed.
=> build(deps): remove `jscodeshift` from `core`

.github/workflows/delete-branches.yml
After #1380 we're getting this error:
> a step cannot have both the `uses` and `run` keys
This PR fixes it.
=> ci: fix typo in delete branches workflow

.github/workflows/delete-branches.yml
Still broken after #1382, now getting this error:
```
fatal: invalid refspec ''
```
That error means both that the `git for-each-ref` command is returning zero branch names and that the list of branch names is being passed as a single arg to `git push`. This PR fixes both issues by using `git remote set-branches`, `git fetch`, and `xargs`.
=> ci: fix CI branch deletion commands

packages/core/src/compiler/Style.test.ts, packages/core/src/compiler/Style.ts, packages/core/src/types/errors.ts, packages/core/src/types/styleSemantics.ts, packages/core/src/utils/Error.ts, packages/examples/src/geometry-domain/euclidean-teaser.style
Resolves #776 
This PR allows updates to global namespaces Style. The current semantics do not allow users to insert/delete/override values in global namespaces (e.g. `Colors`). For example:
```
Colors {
color red = rgba(1.,0.,0.,1.)
color green = rgba(0.,1.,0.,1.)
}
Colors {
red = #e00 -- updates the definition of Colors.red
-- also removes Colors.green because the entire block is re-declared
}
OverrideColors {
Colors.red = #e00 -- throws `AssignGlobalError`
}
```
This is an arbitrary decision we made, but now it seems to be useful to allow namespace updates for Style modules (#776). 
This PR allows updates to global namespaces, but disallows re-declaration of global namespaces to prevent multiple definitions scattered in one or multiple Style files. For instance:
```
Colors {
color red …
```
=> feat: allow namespace updates in Style

packages/core/src/index.ts, packages/core/src/types/errors.ts, packages/editor/src/components/DiagramPanel.tsx, packages/editor/src/state/atoms.ts, packages/editor/src/state/callbacks.ts, packages/examples/src/geometry-domain/euclidean-teaser.style, packages/examples/src/geometry-domain/euclidean.style, packages/examples/src/group-theory/CayleyGraph.style, packages/examples/src/molecules/lewis.style
Resolves #1305.
This PR displays warnings in `editor`. The current implementation simply shows them in the diagram panel, just like errors but in a different color:
Like shown in the screenshot, some of our gallery diagrams contain warnings (mostly `ImplicitOverrideWarning`). 
Basically copied the implementation for the error UI.
=> feat: show warnings in `editor`

packages/core/src/renderer/AttrHelper.ts
In #1337, while adapting the passthrough auto-fill feature to work with the consolidated shape types, I introduced a bug where the `style` would not correctly map.
This PR fixes it by reverting the logic of the `attrAutoFilSvg` to the version before #1337.
=> fix: passthrough auto fill

packages/components/src/Simple.tsx, packages/core/src/renderer/Renderer.ts, packages/editor/src/components/DiagramPanel.tsx
In the renderer, we set the `width` and `height` of the rendered SVG element to be `100%` for best browser compatibility and responsiveness (#1105). However, tools like Figma and Adobe Illustrator have their own interpretation of these fields and resize their imports. To make sure they use the width and height defined in Penrose, this PR leaves the dimensions in `viewport` and removes `width` and `height` from downloaded SVGs in `editor` for compatibility with external tools.
=> fix: remove width and height attributes in `editor` SVG export

.github/actions/setup/action.yml, package.json
In #904 I realized that we need to invalidate our CI deps cache anytime we add a package, which I implemented by removing the wildcard from `"packages"` in `lerna.json`, meaning that now anyone adding a package needed to remember to also list it in that file. Then in #1081 I put back the wildcard in `lerna.json` and moved the explicit list to our root `package.json` instead. But now that #1412 is merged, I realized that we can get rid of this error-prone need to explicitly list our `packages/` by instead just hashing _all_ the `package.json` files in the repo, which will automatically detect when packages are added, removed, etc. This PR does that, so now adding a package doesn't have any necessary hidden steps beyond creating a new folder under `packages/`.
=> ci: hash all `package.json` files for dep caching

packages/components/src/Gridbox.tsx
#1344 accidentally merged an old `componentDidUpdate` function in `Gridbox`, which causes all `Grid` components to break due to repeated state updates. This PR moves the function and restores the grids in `edgeworth` and `editor`.
=> fix: repeated state updates in `Gridbox` of `components`

CONTRIBUTING.md
Resolves #.
Thanks to @rjainrjain and @keenancrane, who reported some issues with `roger` and the initial build process, this PR updates our dependency requirements on Node and Python (due to `node-canvas` requiring Python 3.10 and Node 18 and below) in CONTRIBUTING.md. The docs also favor `npm link` to install `roger`, and explain how to render the registry via `yarn registry`.
=> docs: update dependency and add instructions on `roger` and the registry

package.json
We've been meaning to do this for a while, since #1142.
Now the whole build log gets printed when you run `yarn start`.
=> build: pass `--verbose` to `yarn start`

packages/core/src/renderer/Equation.ts, packages/core/src/renderer/Renderer.ts, packages/core/src/utils/CollectLabels.ts, packages/editor/src/components/DiagramPanel.tsx, packages/roger/index.ts
Resolves #303.
This PR implements a version of option (1) in #303 :
> Automatically convert all Equation shapes to Text shapes, replacing the string S with the string $S$ so that it gets typeset as math when imported into TeX. (Note that with this conversion, existing Text shapes are unaffected will still get rendered properly within TeX.)
The implementation strategy is simpler than the proposal: we allow an additional flag (`texLabels`) to `RenderStatic` to indicate if we want to render TeX strings. This flag is then passed to the `Equation` renderer, which will render the equation as a plain `<text>` element with surrounding `$`s so that they can be rendered by an external TeX engine like the `svg` package mentioned in #303. We explicitly forward the following properties to this …
=> feat: export SVGs with plain TeX labels

packages/core/src/compiler/Style.test.ts, packages/core/src/compiler/Style.ts
This fixes a bug in the generation of the dependency graph when it sees `Path` expressions with indices.
Conceptually, the expression `arr[index]` depends on both `arr` and `index`. When handling the dependency graph for this expression, it only adds `arr`, not `index`. This sometimes result in `arr[index]` being evaluated before `index` even exists in the translation.
In `findPathsExpr` we modify the case for `Path` to return the `arr` part and the `index` part:
```
return [
{
...expr,
indices: [],
}, // this is the `arr` part
...expr.indices.flatMap((index) => findPathsExpr(index, context)), // this is the `index` part
];
```
=> fix: dependency graph for paths with indices

packages/core/src/renderer/Equation.ts
Resolves #1445.
Follow up on #1445, this PR shifts all `Equation`s exported as TeX SVG by `h/2 - descent` to get the center on the baseline, like the TeX `svg` package does.
=> fix: baseline center for TeX SVG `Equation`s

packages/docs-site/.vitepress/config.ts
Since we updated our VitePress dependency version from 1.0.0-alpha.35 to 1.0.0-beta.1 in #1427, we've had a type error in `packages/docs-site/.vitepress/config.ts`, since [`cleanUrls` is now a `boolean`](https://vitepress.dev/reference/site-config#cleanurls). This PR fixes that.
Open `packages/docs-site/.vitepress/config.ts` in VS Code before vs after this PR.
=> build: update VitePress `cleanUrls` setting

packages/optimizer/src/lib.rs
I didn't know this [existed](https://docs.rs/serde-wasm-bindgen/0.4.5/serde_wasm_bindgen/struct.Serializer.html#method.json_compatible) until writing more in #1325 just now. As a followup to #1191, this allows us to use maps in our exported Rust types and have [ts-rs](https://github.com/Aleph-Alpha/ts-rs) type them properly. I don't think we currently have any plans to do that, but it'll be nice to eliminate this potential footgun in case we eventually do.
=> fix: use `Serializer::json_compatible()`

packages/editor/src/components/DiagramPanel.tsx
The "Diagram" panel in `editor` is empty on Safari 15.2 and iOS 16.0.2 Chrome & Safari. Not sure which commit caused this, but adding `100%` as `width` and `height` of the SVG element seems to fix this. Perhaps it's a default value issue?
=> fix: Diagram panel empty on iOS Chrome and iOS/macOS Safari

packages/editor/src/components/DiagramPanel.tsx
Reverts penrose/penrose#1465
This PR caused display issues in our gallery (SVG gradients not rendering properly).
Since it's a minor change, and the most recent one, I'm rolling it back until we have a fix.
=> chore: Revert "fix: Diagram panel empty on iOS Chrome and iOS/macOS Safari"

packages/editor/src/components/DiagramPanel.tsx
=> Revert "chore: Revert "fix: Diagram panel empty on iOS Chrome and iOS/macOS Safari""

packages/roger/bin/run.js, packages/roger/index.ts, packages/roger/package.json, yarn.lock
Resolves #1439.
This PR contains 2 strategies to mitigate the `roger` startup time, which is mostly caused by the node runtime. 
1. Switch from `tsx` to `ts-node --esm --swc` because we observed a 40% speedup when using `ts-node`. This will hopefully reduce the cost of a single `roger` run.
2. Add `roger trios [trios..] -o <output-path>` to support batch-rendering multiple trios. This command expects a list of `.trio.json` files (the extension is necessary for accurate guessing of the output svg file) and render them to `<output-path`.
A small thing: `ts-node` prints out a warning for our `package.json` import for version printing (see [issue](https://github.com/TypeStrong/ts-node/issues/1661)). This is a Node problem, but I've disabled `roger --version` for now to avoid the noisy output. …
=> feat: add command to render multiple trios in `roger`

packages/edgeworth/src/analysis/SubstanceAnalysis.ts, packages/edgeworth/src/synthesis/Synthesizer.ts
Deduplication of program statements within a mutated Substance program exists in Edgeworth, but until now deduplication between mutated Substance programs themselves has not existed. This PR introduces such deduplication of programs themselves. 
We add a function `dedupSynthesizedSubstances` to [SubstanceAnalysis.ts](https://github.com/penrose/penrose/blob/main/packages/edgeworth/src/analysis/SubstanceAnalysis.ts), which `reduce`s together the prettyprint strings of each program statement, compares the concatenated strings of each program supplied to it, and removes duplicates. Then, in the `generateSubstances` function in [Synthesizer.ts](https://github.com/penrose/penrose/blob/main/packages/edgeworth/src/synthesis/Synthesizer.ts) we run `dedupSynthesizedSubstances` until the desired …
=> feat: deduplication of mutated Substance programs in `edgeworth`

packages/examples/codegen.js, packages/examples/src/registry.json
Resolves #1483.
Follows up on #1391 to re-introduce solid examples to the registry by fixing the generated imports. 
The old implementation imports solid examples no matter if the example is used. This PR wraps it around an async function to make sure it's only imported when `f` is invoked.
=> fix: async loading of solid examples in the registry

packages/core/src/renderer/Line.ts
https://github.com/penrose/penrose/pull/1423 refactored the implementation for `Line`s, rendering them as `<line>` rather than `<path>`. This caused a regression when the line length is zero if there's an arrowhead. This PR fixes the default behavior so zero-length `Line`s render correctly.
=> fix: render zero-length `Line`s

packages/docs-site/docs/team.md
This PR adds @ravenrothkopf and @rjainrjain to the team page. Welcome!
=> docs: add @rjainrjain and @ravenrothkopf to team page

packages/docs-site/src/components/Function.vue
Following up on #1427, this PR adds a "Default Value" column to the function documentation page when any of the parameters have a default.  
* The conditional rendering is repeated for both table header and each row to avoid incomplete tables.
https://fix-fn-docs.penrose-72l.pages.dev/docs/ref/style/functions
=> docs: show default values of function parameters

packages/docs-site/docs/ref/style/shapes/group.md
=> docs: syntax highlight docs for Group

packages/editor/src/components/ExamplesBrowser.tsx
Following up on #1464. There's a bug in https://github.com/penrose/penrose/pull/1464/commits/843728a3b6783589c12be03bed71fd802ca9ebfb that causes 404 when a user loads an example from the example browser and then refresh the page. This PR prepends the query string with `?` to make sure the link is valid.
=> fix: query string for examples in `editor`

packages/components/src/Gallery.tsx, packages/editor/src/components/ExamplesBrowser.tsx
This PR resolves the problem of diagram previews being cropped to the tightest bounding box even when the intended view box is zoomed in on a portion of the total shapes, which makes some previews look wholly unlike the actual diagrams in the gallery and the editor.
We introduce a check to compare the areas of (1) the existing view box and (2) the tightest bounding box of all shapes, and set the SVG `viewBox` to the smaller of the two.
Since this is done after the SVGs have been produced, we parse the widths and heights of the `viewBox` and `croppedViewBox` strings from these SVGs to calculate the area. We only set the `viewBox` to the values in `croppedViewBox` if the area of the latter is smaller than the former. 
Here is a screenshot of the previously badly cropped diagram in the …
=> feat: cropping picks smaller viewbox in gallery and `editor`

packages/components/src/Demo.tsx, packages/components/src/Gallery.tsx, packages/components/src/stories/Demo.stories.tsx, packages/docs-site/.vitepress/config.ts, packages/docs-site/docs/ref.md, packages/docs-site/index.md, packages/docs-site/src/components/DemoWrapper.vue, packages/docs-site/src/components/GalleryWrapper.vue, packages/examples/src/geometry-domain/euclidean-teaser.style, packages/examples/src/set-theory-domain/venn-3d.style, packages/examples/src/structural-formula/molecules/caffeine.trio.json, packages/examples/src/structural-formula/pseudo-3d.style
This PR makes a few changes to our homepage:
* Add discord server invitation
* Tweak landing page design
* Better `Demo` component positioning and sizing
* More demo examples: hexagonal graph, caffeine, 3D euler diagram
* Update footer to include copyright and license info   
* Gallery page: rounded corners and dark-mode shadow
=> docs: homepage tweaks

packages/components/src/editing/EditorPane.tsx, packages/core/src/compiler/Domain.ts, packages/core/src/compiler/Style.ts, packages/core/src/compiler/Substance.ts, packages/core/src/index.ts, packages/core/src/types/errors.ts, packages/core/src/utils/Error.ts, packages/core/src/utils/Util.ts, packages/editor/src/components/ProgramEditor.tsx
Since many types of warnings and errors include source location information, we can utilize these information to mark them in the IDE editor.
1. We write a function, `errLocs`, that extracts the location information (which file, which row, which column) from each error and warning, _except `StyleErrorList`_. `StyleErrorList` essentially stores multiple Style errors, so we handle them specially.
2. For errors and warnings with location information, the IDE editor now draws red squiggly lines at places for errors, and yellow squiggly lines at places for warnings.
3. These squiggly lines update after every time the "compile" button is pressed.
=> feat: error and warning markings in IDE editor

packages/examples/src/curve-examples/catmull-rom/catmull-rom.trio.json, packages/examples/src/exterior-algebra/vector-wedge.trio.json, packages/examples/src/geometry-domain/textbook_problems/c11p12.trio.json, packages/examples/src/stochastic-process/stochastic-process.trio.json
Since we now have a different set of example diagrams, some diagrams issue warnings like `BBoxApproximationWarning` and `NoopDeleteWarning`. This PR modify the trio files of affected examples to exclude these warnings from being reported.
=> fix: warnings in example diagrams

packages/core/src/engine/Autodiff.ts
I was staring at our derivative expression for division and realized we don't need to call `squared`.
=> refactor: simplify derivative of `div`

packages/docs-site/docs/ref/style/functions.data.ts, packages/docs-site/docs/ref/style/functions.md
Following up on #1427. The previous solution was client-side. This PR does [build-time data loading](https://vitepress.dev/guide/data-loading) for Style functions.
=> docs: load Style function data using SSR

packages/docs-site/docs/ref/domain/examples.md, packages/docs-site/docs/ref/style/examples.md, packages/docs-site/docs/ref/substance/examples.md
Just points each of the `Examples` pages in the documentation to the [examples gallery](https://penrose.cs.cmu.edu/examples), since these working examples may give a better sense of how to actually use the language than some of the smaller tutorial examples.
=> chore: Point to gallery

packages/core/src/overall.test.ts
Look.
```diff
diff --git a/packages/core/src/overall.test.ts b/packages/core/src/overall.test.ts
index 705ea2847..058c39771 100644
--- a/packages/core/src/overall.test.ts
+++ b/packages/core/src/overall.test.ts
@@ -274,13 +274,16 @@ describe("Cross-instance energy eval", () => {
constrFns: state1Done.value.constrFns,
objFns: state1Done.value.objFns,
};
-        expect(evalEnergy(await crossState21)).toBeCloseTo(0);
+        const energy21 = evalEnergy(crossState21);
+        expect(energy21).toBeCloseTo(0);
const crossState12 = {
...state1Done.value,
constrFns: state2Done.value.constrFns,
objFns: state2Done.value.objFns,
};
-        expect(evalEnergy(await crossState12)).toBeGreaterThan(0);
+        const energy12 = evalEnergy(crossState12);
+        expect(energy12).toBeGreaterThan(0);
+ …
```
=> test: get rid of cross-instance energy eval

CHANGELOG.md, Cargo.lock, lerna.json, packages/components/CHANGELOG.md, packages/components/package.json, packages/components/src/Gallery.tsx, packages/components/src/stories/Gallery.stories.tsx, packages/core/CHANGELOG.md, packages/core/package.json, packages/docs-site/.vitepress/config.ts, packages/docs-site/CHANGELOG.md, packages/docs-site/package.json, packages/docs-site/src/components/GalleryWrapper.vue, packages/edgeworth/CHANGELOG.md, packages/edgeworth/package.json, packages/editor/CHANGELOG.md, packages/editor/package.json, packages/examples/CHANGELOG.md, packages/examples/package.json, packages/optimizer/CHANGELOG.md, packages/optimizer/Cargo.toml, packages/optimizer/package.json, packages/roger/CHANGELOG.md, packages/roger/README.md, packages/roger/package.json, packages/solids/CHANGELOG.md, packages/solids/package.json, packages/vscode/CHANGELOG.md, packages/vscode/package.json
This PR follows up on #1542, releasing another beta with a few fixes:
- fixed link in [`@penrose/roger`](https://www.npmjs.com/package/@penrose/roger/v/3.0.0-beta.0) README
- `@penrose/components` now _actually_ doesn't depend on `@penrose/examples`
- Discord link now properly points to welcome channel
=> chore: bump version to 3.0.0-beta.1

packages/docs-site/public/vanilla-js-demo.html
Regenerate JSPM boilerplate and use v3 API for https://penrose.cs.cmu.edu/vanilla-js-demo.html
=> docs: update Vanilla JS usage for v3

packages/docs-site/blog/v3.md
Adding a short intro to Penrose to the beginning of https://penrose.cs.cmu.edu/blog/v3 for better context.
=> docs: add a short intro to v3 blog post

packages/docs-site/.vitepress/theme/BlogHome.vue, packages/docs-site/blog.md
For some reason tailwind's dark mode doesn't play well with our site. This PR makes sure we vitepress instead of tailwind for dark/light mode styling. We also change from `home` to `page` layout so the left bar is always visible.
=> docs: improve blog excerpt styling

packages/docs-site/.vitepress/config.ts
This PR enables the Vitepress [edit link feature](https://vitepress.dev/reference/default-theme-edit-link) so viewers can directly open a PR to edit our documentation pages.
=> docs: add "Edit this page" button to pages

.vscode/settings.json
Earlier today I made a `*.jsx` file in the Penrose repo and was confused that Prettier wasn't autoformatting it. We don't currently have any such files in our repo, but this PR adds that file type to our `.vscode/settings.json` to prevent such confusion in the future. I also added a comment explaining why we specifically enable only for certain file types.
=> chore: enable Prettier for `*.jsx` in VS Code

packages/docs-site/docs/ref.md
This PR answers a frequent question from various HN discussions in the past: why did you pick "penrose" as the project name? Added a small section to the documentation landing page:
> We named Penrose after Sir Roger Penrose, who, in addition to possessing a euphonious name, is known for his Escher-inspired illustrations of impossible objects, Penrose notations, and Penrose diagrams. "Pen" and "rose" also encapsulate our goal of turning notations ✍️ to beautiful diagrams 🌹.
=> docs: explain the origin of the project name

packages/core/src/compiler/Style.test.ts, packages/core/src/compiler/Style.ts, packages/core/src/types/errors.ts, packages/core/src/utils/Error.ts
Resolves #1557 .
This PR fixes the bug of uncaught error when a `layer` directive is applied to nonexistent objects. As an example,
```
canvas {
height = 800
width = 700
layer a above b
}
```
The compiler doesn't check that `a` and `b` actually exist, nor does it confirm that indeed, `a` and `b` are shapes.
When translating `layer` statements, the compiler now resolves each expression and ensures that each object exists and are of `Shape` type. If not, it reports an error.
The Style code used in the example now properly reports an error when necessary.
=> fix: layering on nonexistent objects

.github/workflows/edgeworth.yml
The automatic Edgeworth deployments are taking up a lot of space in `gh-pages` branch. This PR removes the automatic deployment triggers and move to a manual workflow, where we go to "Actions" and trigger the deployment. 
The deployment script takes a single string for the path to the deployment: `penrose.github.io/penrose/edgeworth/<path>`.
=> ci: deploy Edgeworth manually

packages/core/src/contrib/Functions.ts
Resolves #1563.
This PR adds a `mod` function to `Functions.ts`, allowing the modulus to be calculated in Style.
We obtain `mod(a, n)` by computing `a-n*floor(a,n)`.
The following program is an example usage of the `mod` function in Style, which should display a circle of radius 1:
```
canvas {
height = 10
width = 10
Circle {
r: mod(75,2)
}
}
```
=> feat: added `mod` function to `Functions.ts`

packages/docs-site/docs/ref/using.md
In the reference "Using Penrose" docs, the `npx` command suggestion seems to install [this package named `roger`](https://www.npmjs.com/package/roger), not the one we want.
=> docs: fix `npx` command for roger

packages/examples/src/geometry-domain/euclidean.style
`CircleCenter` previously overrides the `vec` field of `Circle`, which can cause a circular assignment error when the `Circle` is defined with the same center:
```substance
Point A, B
Circle c := CircleR(A, B) -- circle with `A` as center and passing `B` 
CircleCenter(c, A) -- error: circular assignment of A.vec = A.vec
```
This PR changes to a more lenient approach by adding a constraint ensuring the circle center.
=> fix: `CircleCenter` behavior in Euclidean geometry Style

packages/components/src/editing/languages/StyleConfig.ts, packages/core/src/compiler/Style.test.ts, packages/core/src/compiler/Style.ts, packages/core/src/parser/Style.ne, packages/core/src/types/style.ts, packages/examples/src/group-theory/CayleyGraph.style, packages/examples/src/group-theory/MultiplicationTable.style
Resolves #1065 .
We implement Solution 1 from #1065 to support nondistinct matching.
A new keyword, `repeatable`, is added to selectors and collectors. The `repeatable` essentially allows the selector / collector block to match multiple Style variables to the same Substance variable. This is done by disabling the filter when the `repeatable` flag is enabled:
```
if (repeatable) {
return filteredSubsts.toArray();
} else {
const correctSubsts = filteredSubsts.filter(uniqueKeysAndVals);
return correctSubsts.toArray();
}
```
We modify the "Quaternions as table" example and the "Quaternions as Cayley graph" example to use `repeatable`.
=> feat: nondistinct matching

CHANGELOG.md, Cargo.lock, lerna.json, packages/components/CHANGELOG.md, packages/components/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/docs-site/CHANGELOG.md, packages/docs-site/package.json, packages/docs-site/public/vanilla-js-demo.html, packages/edgeworth/CHANGELOG.md, packages/edgeworth/package.json, packages/editor/CHANGELOG.md, packages/editor/package.json, packages/examples/CHANGELOG.md, packages/examples/package.json, packages/optimizer/CHANGELOG.md, packages/optimizer/Cargo.toml, packages/optimizer/package.json, packages/roger/CHANGELOG.md, packages/roger/package.json, packages/solids/CHANGELOG.md, packages/solids/package.json, packages/vscode/CHANGELOG.md, packages/vscode/package.json
This PR bumps the version to `v3.1.0`
=> chore: bump version to 3.1.0

packages/docs-site/docs/ref/style/functions.md
On the "Style Functions" reference page the function heading elements don't have unique IDs, so they can't be permalinked to and the "On this page" links on the right hand side don't work.
This change sets a unique ID on each of the headings, so each function can be linked to individually.
I'm not super familiar with `markdown-it`, but I couldn't find a nice way to get the ID from markdown `###` syntax, so we just write a `<h3>` element manually.
There are these issues in VitePress, but I don't think they handle this yet. vuejs/vitepress#785 and vuejs/vitepress#960. Maybe in the future this commit can be reverted.
This change might break if we can't assume that:
a. Function names will be valid in a URL
b. …
=> docs: fix anchors for functions

packages/docs-site/src/components/Function.vue
Our [Style function docs page](https://penrose.cs.cmu.edu/docs/ref/style/functions) renders the markdown syntax in function descriptions correctly, but not the parameter descriptions. This PR fixes it.
=> docs: render markdown in function param description

packages/docs-site/blog/v3.md
This PR fixes three single-quotation marks in the blog page about Penrose 3.0.
=> docs: fix single quotation mark

packages/examples/src/registry.json, packages/examples/src/spectral-graphs/3d.style, packages/examples/src/spectral-graphs/examples/dodecahedral-graph.trio.json, packages/examples/src/spectral-graphs/examples/generator.py, packages/examples/src/spectral-graphs/examples/periodic-hexagonal-lattice.substance, packages/examples/src/spectral-graphs/examples/periodic-hexagonal-lattice.trio.json, packages/examples/src/spectral-graphs/examples/torus.substance, packages/examples/src/spectral-graphs/examples/torus.trio.json, packages/examples/src/spectral-graphs/examples/truncated-cube-graph.substance, packages/examples/src/spectral-graphs/examples/truncated-cube-graph.trio.json
Updated 3D style of spectral graphs from #1487. Added 3 examples to the registry.
Heavily uses blur effect from SVG enabled by #1517.
Added a python script for generating substance files for more complex examples:
`packages/examples/src/spectral-graphs/examples/generator.py`
- Use perspective projection instead of orthogonal (using matrix operations from #1538)
=> feat: Update 3D Spectral Graphs

packages/roger/tsconfig.json
Followup to #1576 since [`noImplicitThis`](https://www.typescriptlang.org/tsconfig#noImplicitThis) and [`strictNullChecks`](https://www.typescriptlang.org/tsconfig#strictNullChecks) are both implied by [`strict`](https://www.typescriptlang.org/tsconfig#strict).
=> chore: remove redundant TSConfig stuff for Roger

packages/examples/src/alloy-models/dining-philosophers/table.style
After merging the PR #1583 (which introduces `numberof` and `nameof`), I immediately merged PR #1584 (which contains some Alloy examples).
I then realized that the dining-philosophers example can benefit from `numberof` and `nameof`. This PR makes the dining-philosophers example use `numberof` and `nameof`.
=> fix: Alloy example dining-philosophers use `numberof` and `nameof`

packages/docs-site/src/components/Function.vue
Our main site uses KaTeX (https://github.com/penrose/penrose/pull/926) to allow math notations in markdown. This PR add support for math notations in the core Style function library docs as well.
=> docs: allow TeX in Style function docs

packages/docs-site/docs/ref/style/functions.data.ts, packages/docs-site/src/components/Function.vue
Following up on #1592, this PR moves the markdown rendering code into a [build-time data provider](https://vitepress.dev/guide/data-loading).
=> docs: render Style function docstrings at build-time

packages/core/src/compiler/Style.test.ts, packages/core/src/compiler/Style.ts
Resolves #1509.
This PR allows Style writers to extract an entire row from a matrix. Previously, we only allow indexing for a specific element of matrix with two indices.
We add a case when the number of indices is 1. In that case, after checking for out-of-bound errors, we directly extract that row as a vector.
=> feat: row-indexing of matrices

CONTRIBUTING.md, rust-toolchain.toml
While [packaging penrose for Nix](https://github.com/jhvst/nix-config/commit/d749ea86b31782f51c0cf10c0b407b636063bd84), I found that a common practice to add Rust toolchains or select specific version is by doing [overrides](https://rust-lang.github.io/rustup/overrides.html). Nix in particular likes the toolchain file, which if present, will automatically run the equivalent "rustup" command. In penrose case, the file can be used to add the wasm toolchain required to compile the roger binary.
As this helped me, I was wondering if you would be interested in merging this request and/or possibly pinning the Rust version furthermore using the toolchain file. For me, having this file on upstream skips a patch over the source repository.
N/A
N/A?
See above
=> build: add rust-toolchain.toml for automatic toolchain installation

packages/core/package.json
Currently, the unpacked size of `@penrose/core` is 1.32M. As a first step to reduce the size of the package, this PR excludes test files from the npm distribution. 
We might want to consider providing bundles of core in CJS and ESM (related issue with size in #423) along with the ES modules. It's a bit surprising that `core` is this big without any bundles. Wondering what the best practices are for distribution.
=> build: exclude test files from `core` npm pack

packages/core/package.json, packages/core/vite.config.ts, packages/docs-site/docs/ref/vanilla-js.md, yarn.lock
This PR adds a bundled ES module release format to `@penrose/core`. 
When building a [plugin for Obsidian](https://github.com/wodeni/obsidian-penrose-plugin), I ran into build issues about top-level `await`. Specifically, the Obsidian plugin system expects a CommonJS module, and plugin builders usually use `esbuild` to convert from ESM code to the expected CJS format. However, [CJS does not support top-level `await`](https://github.com/nodejs/node/issues/21267) and this prevents the default `esbuild` script to build any plugins that includes `@penrose/core`, as it has TLA from `@penrose/optimizer`.
To work around this, we historically use `vite-plugin-top-level-await` to work around it (see [docs](https://penrose.cs.cmu.edu/docs/ref/bundle)). However, clients like Obsidian plugins can't …
=> build: experimental `core` bundle

CHANGELOG.md, Cargo.lock, lerna.json, packages/components/CHANGELOG.md, packages/components/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/docs-site/CHANGELOG.md, packages/docs-site/package.json, packages/docs-site/public/vanilla-js-demo.html, packages/edgeworth/CHANGELOG.md, packages/edgeworth/package.json, packages/editor/CHANGELOG.md, packages/editor/package.json, packages/examples/CHANGELOG.md, packages/examples/package.json, packages/optimizer/Cargo.toml, packages/optimizer/package.json, packages/roger/CHANGELOG.md, packages/roger/package.json, packages/solids/CHANGELOG.md, packages/solids/package.json, packages/vscode/CHANGELOG.md, packages/vscode/package.json
This PR bumps all package versions to `v3.2.0`
=> chore: bump version to 3.2.0

packages/examples/src/registry.json
#1505 tried to add the `mobius/mobius` example to the gallery, but this was prevented by a duplicate `mobius/mobius` entry further down in the `registry.json` file without `"gallery": true`, which took precedence. This PR fixes the issue by removing the latter entry.
Look at [the website's gallery page](https://penrose.cs.cmu.edu/examples).
=> chore: remove duplicate Möbius registry entry

packages/docs-site/docs/tutorial/functions.md, packages/examples/src/tutorials/solutions/tutorial3.md, packages/examples/src/tutorials/supplementary/tutorial3/walkthrough.md
=> docs: replace outdated `arrowheadSize` in tutorial

packages/core/src/parser/Substance.ne
Resolves #1620.
The online IDE fails because of a faulty regex for integer literals in the Substance parser introduced in #1572. This PR removes the `?<` group (possibly intended for [lookbehind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Lookbehind_assertion) but incorrect anyway).
=> fix: regex for int literals

packages/core/src/contrib/Functions.ts
Resolves #1616.
We make `averagePoint` use `sumVectors` (which correctly handles vectors with >2 elements) instead of performing the summation ourselves. We also update the documentation to specify, correctly, that the function takes in vectors of length N and outputs one vector of length N.
The function `sumVectors` was implemented inline. We extract the implementation of `sumVectors` to outside of the computation function dictionary so that it can be used in `averagePoint`.
=> fix: averagePoint for vectors with more than two elements

packages/core/src/contrib/Functions.ts
We add a computation function `TeXify` that takes in a string separated by underscores (`_`) and returns "reasonable" version of the string that can be gracefully rendered by LaTeX.
As an example, if we just try to render `"hello_world"` as an equation, it would look like $hello_world$. If we instead render `TeXify("hello_world")`, it would look like ${hello}_{world}$ which is more reasonable. This is because `TeXify("hello_world")` outputs `"{hello}_{world}"` which is rendered reasonably by LaTeX.
Another instance where this comes up is, with substance indexed sets, we can easily generate objects with large indices. For example,
```
Node n_i for i in [0, 105]
```
would generate `n_0, n_1, ..., n_103, n_104, n_105`. If we just render an `Equation` shape with `"n_105"`, it would look like …
=> feat: TeX-ifying strings using braces

packages/docs-site/src/components/Gallery.vue
#1631 introduced a relatively "long" SVG for our gallery, which overflowed the grid box container. 
This PR changes the CSS to use flex box to contain and center the SVG inside. I also reduced the padding a bit to make the diagrams more visible
=> docs: change gallery grid to use flex boxes

.github/workflows/bench.yml
This PR adds a simple manual CI workflow for comparing two commits on `main`. The workflow takes two commit SHAs and run `yarn registry` on both commits. For consistency, the workflow runs them on the same runner sequentially. 
Tested by switching to `pull_request` trigger but testing `workflow_dispatch` requires merging into `main` first.
N/A
=> perf: CI workflow for comparing registry performance

packages/docs-site/.vitepress/config.ts, packages/docs-site/community.md, packages/docs-site/docs/team.md, packages/docs-site/src/components/Contributors.vue, packages/docs-site/src/components/GitHubIssue.vue, packages/docs-site/src/components/GitHubPR.vue, packages/docs-site/src/contributors.data.ts
This PR adds a "getting involved" page on the website to encourage visitors to join the Penrose community and guide them to action items. The content on the page is by no means final. This PR mainly focuses on adding the infra for content in future PRs.
* To de-clutter the nav bar, I removed the news and join discord buttons. The content under news are mostly papers, which we should link to in the getting involved page as examples of research outcome. The discord link is already associated with the top-right icon.
* Add github icons of contributors to the team page
* Add a roadmap section and components for linking to github issues and prs. The content is TBD 
See deployment
=> docs: "getting involved" page

packages/editor/src/components/DiagramPanel.tsx
Resolves #1586.
The cause is an extra `svg.appendChild(metadata)` call at the end of the `SVGAddCode` function introduced in https://github.com/penrose/penrose/pull/1171. This line should only be executed when there isn't already a `<penrose>` node.
=> fix: duplicate `<penrose>` tags in exported SVGs

packages/examples/src/ray-tracing/ray-tracing.style
While implementing experiments like #1636, #1657, and #1658, I was getting errors for our ray tracing examples. I was able to fix these errors by applying the diff in this PR, which deletes a labeling nearness objective when the position of the label has been directly overridden to be near by construction. I believe that this was just an oversight in the Style program, so this PR fixes the bug.
=> chore: fix labeling objective in ray tracing Style

packages/core/src/compiler/Style.ts, packages/core/src/engine/Autodiff.ts, packages/core/src/engine/EngineUtils.ts, packages/core/src/index.ts, packages/core/src/lib/Minkowski.ts, packages/core/src/shapes/Shapes.ts, packages/core/src/utils/CollectLabels.ts, packages/core/src/utils/Graph.ts, packages/core/src/utils/GroupGraph.ts, packages/core/src/utils/Util.ts
#412 added a utility function called `safe` which guards against `null` and `undefined` values, then #873 changed it to only handle `undefined`. The function takes a mandatory `message: string`, which it uses to construct a `TypeError`. This has a couple disadvantages:
1. it discourages usage with non-constant error messages, because the message string is always constructed regardless of whether the value is `undefined`
2. it discourages usage in general, because having to come up with an error message every time takes effort and adds verbosity, especially since often the chosen error message actually adds no value; making [`!`](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#non-null-assertion-operator-postfix-) attractive in comparison
To address those downsides, this …
=> refactor: replace `safe` util with nicer `unwrap`

packages/core/.eslintrc.json
While working on #1662 I noticed that we were using the wrong name for typescript-eslint's [no-non-null-assertion](https://typescript-eslint.io/rules/no-non-null-assertion/) rule, causing those warnings to be hidden. Not sure when this changed; maybe when we upgraded typescript-eslint to v6?
=> chore: fix `no-non-null-assertion` lint rule name

packages/examples/src/registry.test.ts
Followup to #1664, since the `data.json` file size should be linear in the number of tests, but the `stats.md` file can also grow according to `MAX_SECONDS`, configured in #1657 for example.
=> test: wait until the end to write the text chart

packages/docs-site/community.md
@weavermarquez is developing `ob-penrose`, an org babel package to support literate programming w/ diagrams made by penrose (thanks!!). This PR adds a link to this package in the "Getting Involved" package for visibility.
=> docs: add `ob-penrose` to tool integration section

packages/docs-site/docs/ref/api.md
Currently the example on this page does not compile. Fixed here to match the (working) "Sets as Venn Diagram" example at https://penrose.cs.cmu.edu/try/?examples=set-theory-domain%2Ftree-venn
Resolves #1669 
I replaced the code in `trio.js` with the code from https://penrose.cs.cmu.edu/try/?examples=set-theory-domain%2Ftree-venn, which works.
=> fix: Update api.md

packages/core/src/compiler/Substance.test.ts, packages/core/src/compiler/Substance.ts, packages/core/src/parser/Substance.ne, packages/core/src/types/errors.ts, packages/core/src/utils/Error.ts
Resolves #1671 .
This PR addresses the issue by removing separate parse rules for `int_literal` and adding a compile-time check for integer.
=> fix: Substance parsing of floating-point numbers

packages/components/src/editing/languages/StyleConfig.ts, packages/editor/src/state/atoms.ts
On start, `editor` starts the trio with empty strings, and it's a bit tedious to type `canvas { ... }` every time. This PR inserts a default canvas block to the Style pane by default and exposes a code snippet `canvas` that inserts a template for the canvas block:
```
canvas {
width = 400
height = 400
}
```
* Go to deployment IDE
* Hit "compile"
* Observe no errors are thrown because the canvas is already pre-populated.
=> chore: add default canvas block to `editor`

packages/core/src/compiler/Style.ts
The algorithm that matches Style selector function calls against Substance function calls don't work if the function take in zero arguments.
Suppose we have Style selector expression `MyFunc(a, b, c)` and Substance expression `MyFunc(A, B, C)`. Naturally, we have substitution `{a -> A, b -> B, c -> C}`. That is, the substitution contains one entry for each argument. This is a valid substitution.
What happens if `MyFunc` takes in no arguments? In other words, what happens if we match Style selector expression `MyFunc()` against Substance expression `MyFunc()`? Naturally, it should generate a valid substitution, but with no entries. That is, the substitution should be `{}`. This is a valid but empty substitution.
The bug occurs because instead of returning `{}` which is a valid …
=> fix: improper Style matching of functions without parameters

packages/core/src/compiler/Substance.test.ts, packages/core/src/compiler/Substance.ts
Resolves #1685.
This PR adds a check to `evalISet` - for a range `i in [low, high]`, if `high < low`, then return empty set since there are no valid `i`s.
We modified the test `indexed set decl - no satisfying indices`. The modified test would fail in the current version but will pass in this PR.
 
=> fix: improper handling of flipped index ranges

package.json, yarn.lock
@samestep reported that the CI is not bundling `core` during `build` and this PR adds another target to the top-level `build` script to also run `bundle` (and only `core` as it currently). Bumped `nx` to 15.4 for the `--targets` flag.
=> ci: bundle `core` in `build`

packages/editor/src/components/LayoutTimelineSlider.tsx, packages/editor/src/worker/OptimizerWorker.ts, packages/editor/src/worker/message.ts, packages/editor/src/worker/worker.ts
This PR fixes an issue introduced by #1681. The slider always lags by 1 when the user drags it around. This is caused by an error in the update effect, where I mistakenly used the state variable instead of the fresh value immediately. State updates later than the worker request, causing the off-by-one.
I also simplified the `ComputeShapes` message to remove `min` and `max`. I think it's premature optimization at the moment and also the client now should have the information to sample the layout timeline.
=> fix: off-by-one error in time-travel slider

.github/workflows/bench.yml, .github/workflows/build.yml
Updated GitHub Actions workflows to use the latest upload-artifact action v4.1.0
which According to GitHub 90% faster and storage efficient
Revised workflows
- bench.yml
- build.yml
[https://github.com/actions/upload-artifact#v4---whats-new](https://github.com/actions/upload-artifact#v4---whats-new)
=> feat: update upload-artifact action to latest version

packages/examples/src/structural-formula/molecules/caffeine.trio.json
> The caffeine example is laughable.
This PR fixes the caffeine example to be less laughable.
=> feat: Update variation for caffeine example

packages/docs-site/docs/ref/style/shapes/line.md, packages/docs-site/src/components/PropValue.vue, packages/docs-site/vite.config.ts
Resolves #1689.
Add an `Embed` component on the doc page to showcase all arrowhead styles.
https://arrowhead-docs.penrose-72l.pages.dev/docs/ref/style/shapes/line
=> docs: add documentation and an example of arrowhead styles

packages/components/src/Gridbox.tsx, packages/components/src/Simple.tsx, packages/edgeworth/src/components/Settings.tsx, packages/edgeworth/src/problems/all.tsx, packages/edgeworth/src/problems/chemistry.tsx, packages/edgeworth/src/problems/geometry.tsx, packages/edgeworth/src/problems/graphs.tsx, packages/edgeworth/src/synthesis/Synthesizer.ts, packages/edgeworth/vite.config.ts
This PR fixes a few superficial bugs in Edgeworth that impacted the first-use experience.
=> fix: UI bugs in `edgeworth`

packages/core/src/compiler/StyleFunctionCaller.ts, packages/core/src/shapes/Samplers.ts, packages/core/src/types/errors.ts, packages/core/src/utils/Error.ts, packages/core/src/utils/Util.ts
Resolves #1713.
When there's an internal error in computation functions, the compiler adds the entire function including its body as metadata for the error. This is fine on the main thread but not ok in webworkers because functions are not clonable. This PR omits the function body in the `FunctionInteralError` type.
=> fix: exclude function body from `FunctionInternalError`

packages/examples/src/molecules/ammonia.substance, packages/examples/src/molecules/bromateanion.substance, packages/examples/src/molecules/caffeine.substance, packages/examples/src/molecules/carbontetrachloride.substance, packages/examples/src/molecules/glutamine.substance, packages/examples/src/molecules/hydrazine.substance, packages/examples/src/molecules/hydrogencyanide.substance, packages/examples/src/molecules/lewis.style, packages/examples/src/molecules/methane.substance, packages/examples/src/molecules/molecules-basic.style, packages/examples/src/molecules/molecules-elegant.style, packages/examples/src/molecules/molecules.domain, packages/examples/src/molecules/molecules.style, packages/examples/src/molecules/nitricacid.substance, packages/examples/src/molecules/nitrogen.substance, packages/examples/src/molecules/nitrousacid0.substance, packages/examples/src/molecules/phosgene.substance, packages/examples/src/molecules/phosphorustrichloride.substance, packages/examples/src/molecules/water.substance, packages/examples/src/molecules/xenontetroxide.substance
Changed chemistry Domain program and example Substance programs to make predicates shorter — `MakeSingleBond`, `MakeDoubleBond`, and `MakeTripleBond` have been changed to `SingleBond`, `DoubleBond`, `TripleBond`.
=> refactor: `Bond` constructor names in the chemistry domain

packages/roger/index.ts
Related: #1697 
Requested by @keenancrane for collecting timing information for diagrams. `roger` internally collects timing for compilation, optimization, and rendering. This PR adds a `--dump-metadata` option in `roger` for writing the metadata as a JSON file to disc.
Running `roger trio exterior-algebra.domain exterior-algebra.style  vector-wedge.substance --dump-metadata  meta.json --out diagram.svg` in `examples/src/exterior-algebra` produces:
[meta.json](https://github.com/penrose/penrose/files/14589470/meta.json)
=> feat: `--dump-metadata` in `roger`

packages/docs-site/community.md
It's a bit more convenient to maintain a GitHub project than a webpage on the site for our current technical roadmap (https://github.com/orgs/penrose/projects/10). This PR updates the links to the roadmap to point to the GH project instead of a section on https://penrose.cs.cmu.edu/community.
=> docs: update links to the technical roadmap

packages/docs-site/community.md
=> docs: remove link to planned subsection on the contributing page

packages/docs-site/blog/staged-layout.md
Fixes one typo for link formatting.
=> docs: typo in staged layout blog post

packages/editor/src/worker/OptimizerWorker.ts
Resolves #1721.
The IDE shows unresolved toasts because it requests to compile the cached diagram on start, before the worker is loaded sometimes. Once the worker gets loaded, however, the IDE only resolves the most recent pending request, losing the earlier ones.
Implement a simple queue of requests along with their callbacks for cleanup and resolve them once the worker is loaded.
=> fix: queue and resolve pending requests in optimizer worker

packages/docs-site/.vitepress/config.ts, packages/docs-site/blog/v3.md, packages/docs-site/docs/ref/using.md, packages/docs-site/docs/ref/vanilla-js.md, packages/docs-site/docs/tutorial/basics.md, packages/docs-site/docs/tutorial/functions.md, packages/docs-site/docs/tutorial/predicates.md, packages/docs-site/vite.config.ts
_Originally reported by `WormEmperor` on discord (thanks!)_
This PR replaces all `pathname://` links on `docs-site` with `<a href="..." target="blank">` to fix broken links. For context, we updated vitepress in #1704, the new version of which removed `pathname://` support. 
* In addition to the `pathname://` fixes, this PR also updates the vite config to match `editor`'s to include the following for web worker support:
```js
{
server: {
headers: {
"Cross-Origin-Embedder-Policy": "require-corp",
"Cross-Origin-Opener-Policy": "same-origin",
},
},
preview: {
headers: {
"Cross-Origin-Embedder-Policy": "require-corp",
"Cross-Origin-Opener-Policy": "same-origin",
},
},
}
```
Test the first link to the IDE in `/docs/ref/using`, and all other links to workspaces in the tutorial in the preview …
=> fix: public links and build config in `docs-site`

packages/roger/index.ts
The default `version` function of `yargs` will automatically pull the package version from `package.json`. Therefore, this PR adds the `.version()` call back so `roger --version` is no longer `unknown`.
=> fix: show `roger` version

packages/editor/src/state/callbacks.ts
Resolves #1740 
Previously, when a workspace was deleted, sometimes another saved workspace would be highlighted and if "save" was clicked on the new workspace, this would override the highlighted space.
The overriding bug was because in useDeleteLocalFile in state/callbacks.ts previously the currentWorkspaceState was only reset to the default. This caused the id in the metadata to be identical to the default result of the uuid() call which could conflict with an existing saved file. Thus on deletion, the currentWorkspaceState would be reset with "blank" substance, style, and domain files, but the metadata id of another existing saved file. 
I solved this by setting the currentWorkspaceState metadata id to a new randomly generated uuid, thus avoiding collision.
The diagram panel …
=> fix: Solves deletion override and diagram panel not updating

packages/core/src/compiler/StyleFunctionCaller.ts, packages/core/src/types/errors.ts, packages/core/src/utils/Error.ts
Resolves #1745.
Like PR #1714, this PR removes the function bodies from `TooManyArgumentsError` so that it plays nicely with WebWorker.
=> fix: Style function body should not be in errors

packages/editor/src/state/atoms.ts
After new button was added, in the .style file the canvas width and height lacked indentation. This is a minor fix to have the auto indent.
=> fix: style canvas default indent error

packages/editor/src/components/SvgUploader.tsx
Resolves #1751 
SVG Upload logic works properly. However, currently SVG Upload exits silently when user is on an unsaved workspace. Solved this by adding a confirmation box that lets the user know SVG Upload will only continue if they click confirm.
=> fix: fixed SVG upload 

packages/editor/src/components/ExportButton.tsx, packages/editor/src/state/callbacks.ts
Resolves #1761 
Previously if a user wanted to copy a trio to their clipboard they would have to copy and paste each piece individually which feels time consuming and clunky. 
As a solution, I added a "Copy to Clipboard" option beneath the Export button in the ide. Clicking this option copies each element of the trio separated by a -- .(file name)
=> feat: Added copy trio to clipboard feature

packages/editor/src/components/DiagramPanel.tsx, packages/editor/src/state/callbacks.ts, packages/editor/src/utils/renderUtils.ts
#1678 refactored the download callbacks in `editor`, but accidentally hard-coded the `texLabels` option in `toSVG`, causing the "SVG (TeX)" option to download SVGs with rendered labels. This PR restores the expected behavior, where `Equation`s are rendered as plain text labels in TeX syntax.
=> fix: regression of TeX SVG download

packages/editor/src/state/callbacks.ts
Resolves #1768
Recent OptimizationWorker refactor (#1765) incorrectly displays certain errors. This has been corrected.
=> fix: compilation errors not displaying properly

packages/core/src/index.ts, packages/core/src/utils/Error.ts, packages/editor/src/state/callbacks.ts, packages/editor/src/worker/OptimizerWorker.ts
As noted by @liangyiliang, #1765 broke error markers in the editor (by not properly updating the diagram state on compilation errors). This change addresses that.
=> fix: no error markers

packages/editor/src/state/callbacks.ts
Resolves #1760
Problem: Previously, it was not clear that the link the share button redirected the user to is a shareable link. 
Solution: Once the user clicks share, the shareable link is automatically copied to the user's clipboard and after redirecting, a notification saying "Copied shareable link to clipboard" is shown. See video below for behavior. 
https://github.com/penrose/penrose/assets/85892844/288a4780-86e3-4192-be96-ed75597581ff
The copy link and display notification is triggered by a url parameter. The way the share button flow works is once the user clicks share, they are redirected to a page with the gist id as a url parameter. Since we don't have explicit routing setup, the only way to pass state from the page the share button was clicked on to the page the user is …
=> feat: Making gist sharing clearer (editor ux)

packages/editor/src/components/DiagramPanel.tsx, packages/editor/src/components/LayoutTimelineSlider.tsx, packages/editor/src/components/SegmentedSlider.tsx, packages/editor/src/components/TopBar.tsx, packages/editor/src/state/atoms.ts, packages/editor/src/state/callbacks.ts, packages/editor/src/worker/OptimizerWorker.test.ts, packages/editor/src/worker/OptimizerWorker.ts, packages/editor/src/worker/common.ts, packages/editor/src/worker/errors.ts, packages/editor/src/worker/worker.ts
Many small bugfixes and improvements
- Worker no longer errors on stale update responses (simply ignores)
- Created `WorkerError` type to distinguish recoverable errors more cleanly
- ~~Editor no longer hangs when several compiles are queued quickly~~ **Disabled recompilation before compilation has finished** (in accordance with previous behavior)
- Slider no longer throws out of range error when compiled immediately after a drag
- Slider no longer "falls behind" after a drag + resample 
- Allow `startOptimize` to interrupt ongoing optimization instead of erroring
- Display compiler warnings properly
- Hide excluded warnings
=> fix: misc. webworker + IDE fixes

CONTRIBUTING.md
Following up on #1777, this PR edits `CONTRIBUTING.md` to explicitly recommend [Pyenv](https://github.com/pyenv/pyenv) for Linux and Mac, just as we already do for [nvm](https://github.com/nvm-sh/nvm).
=> docs: recommend Pyenv

packages/core/src/compiler/Style.ts, packages/core/src/compiler/StyleTypeChecker.ts, packages/core/src/engine/EngineUtils.ts, packages/core/src/lib/Functions.ts, packages/core/src/lib/__tests__/Functions.test.ts, packages/core/src/renderer/Path.ts, packages/core/src/renderer/PathBuilder.ts, packages/core/src/types/types.ts, packages/core/src/types/value.ts, packages/core/src/utils/Util.ts, packages/editor/src/state/callbacks.ts
**Draft**
(Partially) resolves #1767.
This implements two style functions, `concatenatePaths` and `connectPaths` which both turn a list of `PathDataV` into one `PathDataV`, according to different connection policies
- Added `PathDataListV` as a style list type
- New style functions mirror the format of existing path factory functions
```
concatenatePaths : (PathDataListV) => PathDataV
```
Connect a list of paths by exactly concatenating their SVG commands. Visually, this has the effect of taking the union of the paths.
```
connectPaths : (PathTypeV, PathDataListV) => PathDataV
```
Connect a list of paths by drawing a line between the end and start point of each path. If "closed" is passed as the path type, a line is drawn from the end of the last path to the start of the first.
``` …
```
=> feat: join paths

CONTRIBUTING.md
On commit 42ea8ec954655fabdd0eea0e208cd2f4810afeca, trying to install using Node v19 gives this error:
```
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning penrose-vs@4.0.0-alpha.0: The engine "vscode" appears to be invalid.
error vitest@1.6.0: The engine "node" is incompatible with this module. Expected version "^18.0.0 || >=20.0.0". Got "19.9.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
And trying to install with Node v20 or v21 gives this error: https://pastebin.com/uUcHasWM
This PR modifies `CONTRIBUTING.md` to clarify that only Node v18 actually works.
=> docs: clarify that only Node v18 works

CONTRIBUTING.md
Following up on #1777 and #1778, this PR adds a warning note about how Homebrew can adjust the Python version on one's `PATH` even if it's correct before running any `brew install` commands.
=> docs: warn about Homebrew Python

packages/core/src/lib/Constraints.ts, packages/examples/src/alloy-models/file-system/icicle-plot-file-system.domain, packages/examples/src/alloy-models/file-system/icicle-plot-file-system.style, packages/examples/src/alloy-models/file-system/icicle-plot-file-system.substance, packages/examples/src/alloy-models/icicle-plot-file-system.trio.json, packages/examples/src/registry.json
I added two additional constraint functions to the constraint function library. These functions, called distributeHorizontally and distributeVertically respectively, both take in a list of shapes and an optional padding margin as parameters. My original use case for this feature was for an icicle plot diagram I was making in Penrose. For context, icicle plots are one neat way to visualize file systems, or any general hierarchy-based system. Previously, I had to use the disjoint and touching functions in different instances to replicate what I was was envisioning. However, these constraints were difficult to balance and I ran into some consistency issues when resampling. This new constraint function simplified my work and allowed the more difficult alignments of my visualization to be …
=> feat: distribute horizontal and vertical constraint functions

packages/editor/src/worker/OptimizerWorker.ts
Resolves #1799.
Fixes an issue where compiler errors may enter the optimizer worker into an error state if there were no previosuly successful compiles.
=> fix: optimizer entering error state on compile error from init

packages/docs-site/docs/team.md
This PR updates the team page to include @KyleleeSea and @griffinteller, moves @ravenrothkopf to past members, and changes @liangyiliang's title to PhD student.
=> docs: summer 24 team

packages/core/src/engine/Lbfgs.ts
This PR corrects an error in a docstring in our current implementation of L-BFGS, introduced in #1355.
=> chore: fix typo in L-BFGS docstring

.github/workflows/build.yml, packages/components/package.json, packages/components/src/editing/tests/domainTests.test.ts
Following up on #1798, this PR changes the "test" job in our CI to run the test suite in `@penrose/components`, which includes some editor-specific tests and parser tests (which are to be ported to `core`). 
The `components` test suite currently has two failing tests:
* "tree integrity": contains a case of #1814, which is refactored to not test this case
* "dangling output type conflict with subtype decls": explicitly tests for #1814, which is to be un-skipped after the issue is resolved.
=> test: run components tests in CI

packages/components/src/editing/EditorPane.tsx, packages/editor/src/components/ProgramEditor.tsx
Feature existed prior to Codemirror migration. This PR adds it back in. 
1) In Vim mode, :w will compile diagram. 
https://github.com/penrose/penrose/assets/85892844/79b776c8-a747-4acd-b399-ae2704d62773
2) Cntrl/Cmd+Enter will compile diagram
**Notes**
Listing uses EditorPane and does not pass in an onWrite property. In this case onWrite will be undefined and thus no keymaps will be added.
=> feat: added cntrl/cmd+enter and :w to compile diagram

packages/core/src/compiler/Domain.test.ts, packages/core/src/compiler/Domain.ts
Resolves #1818.
This PR moves the check on prohibiting literal types to whenever a subtyping relation is registered. That way, no matter where the subtyping relation appears (in `TypeDecl` or in `SubtypeDecl`), the checker will prohibit subtyping on literal types.
A test has been added.
=> fix: prohibiting inline subtyping on literal types

packages/components/src/editing/hooks/style/styleAutocomplete.ts, packages/components/src/editing/hooks/style/styleAutocompleteUtils.ts, packages/components/src/editing/tests/styleTests.test.ts, packages/components/src/editing/tests/testUtils.ts
Adds stage name autocomplete based on the names users defines after `layout = [...]`
Adds four tests to test suite both testing layout stage names obtained correctly and autocomplete fires for stage names.
=> feat: Layout stage autocomplete + corresponding tests

packages/core/src/compiler/Style.test.ts, packages/core/src/utils/Util.test.ts, packages/core/src/utils/Util.ts
Resolves #1806 .
This PR makes all delimitation after scopes in pretty-printed paths to be dots instead of colons. Some tests have been added.
The registry diagram changes reflect this change from colons to dots.
=> fix: pretty-printed paths use dots consistently

packages/core/src/parser/Substance.ne
@KyleleeSea reported that empty predicates aren't parsed by the substance nearley parser. This PR is a quick fix just to unblock him, knowing that we will deprecate the nearley parsers soon
=> fix: parse empty predicates

packages/components/src/editing/EditorPane.tsx
Reported by @keenancrane: 
> It seems visual block selection in vim mode (ctrl-v) no longer works.  Maybe it got overriden with a higher-priority interpretation of ctrl-v? 
> Also, ctrl-u moves up, but ctrl-d deletes
codemirror, and by extension`@uiw/react-codemirror`, include emacs-style keymaps in its default settings: https://github.com/uiwjs/react-codemirror/issues/356#issuecomment-1180503509
This PR adds `Prec.highest` around the `vim` extension to force prioritize vim keybindings.
=> fix: prioritize vim keymaps in vim mode

CHANGELOG.md, CONTRIBUTING.md, lerna.json, packages/components/CHANGELOG.md, packages/components/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/docs-site/CHANGELOG.md, packages/docs-site/package.json, packages/edgeworth/CHANGELOG.md, packages/edgeworth/package.json, packages/editor/CHANGELOG.md, packages/editor/package.json, packages/examples/CHANGELOG.md, packages/examples/package.json, packages/roger/CHANGELOG.md, packages/roger/package.json, packages/solids/CHANGELOG.md, packages/solids/package.json, packages/vscode/CHANGELOG.md, packages/vscode/package.json
bumps to `v4.0.0-alpha.1` for #1827 mainly. added docs for the pre-release process.
=> chore: bump version to 4.0.0-alpha.2

packages/components/src/editing/EditorPane.tsx
Follow up on #1828 to fix the mistake of adding vim bindings by default
=> fix: default vim keybindings

packages/editor/src/components/SvgUploader.tsx, packages/editor/src/state/atoms.ts, packages/editor/src/state/callbacks.ts
by request of overlord sam
- Unedited unstored workspaces will not trigger a "unsaved" notification anymore (example: on example click or tab exit)
- This also applies to unedited SVG uploaded workspaces
=> feat: no unsaved notif on unedited workspace

packages/components/src/editing/parser/substance/substance.grammar
Shoutout Leo for finding this bug 
In Mobius Strip, the parser throws an error on the "mod" statements in substance
This adds mod as a arithmetic operator to the lezer parser
=> fix: fixed mod err in substance

packages/editor/package.json, packages/editor/src/components/SavedBrowser.tsx, packages/editor/src/components/Settings.tsx, packages/editor/src/components/TopBar.tsx, packages/editor/src/state/callbacks.ts, yarn.lock
Post cloud storage merge, users no longer see their old locally saved diagrams. This adds a button to settings which automatically traverses local storage and saves all locally saved diagrams to cloud storage and syncs the system.
https://github.com/user-attachments/assets/44dbc551-f3b7-47ce-817e-fff76141f9cd
Function loops over all locally saved file ids and saves diagrams whose ids are not in the cloud storage saved list. This required adding the package ["localForage-getItems"](https://github.com/localForage/localForage-getItems/tree/master) which traverses local storage with a driver. localForage did not have this capability built in.
This strategy has two implications:
1 - If a user deletes some of these diagrams from cloud storage, clicking this button a second time will restore the …
=> feat: added recover button to Settings

packages/editor/src/state/callbacks.ts
Previously for recover all if user had in their localstorage a non dictionary object as a value, the button would fail
Example:
We now check object is dictionary before checking for key in dict
=> fix: Fixed traversal for recover all when exists string content file

packages/components/src/editing/EditorPane.tsx
This PR correctly passes the `readOnly` flag for CodeMirror editors.
=> fix: read-only flag in codemirror

packages/components/src/editing/hooks/hooksUtils.ts, packages/components/src/editing/hooks/style/styleTooltips.ts, packages/core/src/index.ts
Uses valueTypeDesc object to map function parameter types to more intuitive names
Creates a map for shape prop type names with names similar to those used in valueTypeDesc
=> fix: Better Hover + info box type names

packages/docs-site/src/components/Gallery.vue
`Gallery.vue` currently loads the preview SVGs sequentially, which is unnecessary and slows down pageload. This PR changes it to an async approach.
=> fix: load gallery examples asynchronously

packages/docs-site/.vitepress/config.ts, packages/docs-site/docs/ref/style/functions.md
Related: https://github.com/penrose/penrose/pull/1704
In #1704 we hacked the vitepress config to have anchor links to functions in the generated [functions docs page](https://penrose.cs.cmu.edu/docs/ref/style/functions). While search will show the functions now, the links to constraints don't jump to the actual `h3` of the function docs entry. The cause was inconsistent casing of the links, e.g. `#constraint-distributeVertically` vs. `#constraint-distributevertically`. This PR removes `toLowerCase` to constraints to make sure the links are consistent.
=> docs: consistent links to all functions

packages/docs-site/docs/bloom/tutorial/getting_started.md, packages/docs-site/docs/bloom/tutorial/hello_diagram.md
Added a note to Bloom tutorial instructing the user to install `vite-plugin-top-level-await` when using vite.
=> docs: added vite plugin note to bloom tutorial

packages/bloom/src/core/builder.ts, packages/bloom/src/core/diagram.ts, packages/bloom/src/core/types.ts
Adds a `renderStatic` method to the `Diagram` class in Bloom, returning a static svg of the diagram. `renderStatic` does not render any shapes marked as `interactiveOnly`, and does not perform any optimization.
=> feat: Bloom - static rendering

packages/docs-site/docs/ref.md
Thanks @tangent-vector for pointing out these broken links!
=> docs: fix broken links in reference overview

.envrc, .gitignore, CONTRIBUTING.md, flake.lock, flake.nix
Recently I tried to dust off Penrose to build on my machine, and I had a lot of difficulty getting it to work, because it has a _very_ tight set of constraints on all the dependencies before you can even run `yarn`. This PR helps with that a bit by adding a Nix environment that includes the right versions of all the dependencies.
=> docs: add a Nix flake for reproducibility with direnv

.envrc, .gitignore, CONTRIBUTING.md
Followup on #1886, since I've realized that checking a one-line `.envrc` into Git is bad practice for a couple reasons:
1. It messes up people who use direnv but want a different setup, e.g. configuring extra environment variables or pointing to an out-of-tree flake instead.
2. The "default" or "recommended" `use flake` is just one line, so it's easy to create that `.envrc` manually after cloning the repo.
=> chore: add `.envrc` to `.gitignore`

CONTRIBUTING.md
At @hsharriman's request, this PR follows up on #1886, #1887, and #1888 by adding a lot more explanation of how to use [Nix](https://nixos.org/) to build Penrose from source. I didn't originally add this because I thought I would be the only Nix user here and didn't want to clutter the `CONTRIBUTING.md`, but apparently it's useful for others besides me as well.
=> docs: explain Nix usage more
